Upload artifacts as output of check-plugins check for debugging
rancher/dashboard pull request #10118
Opened 2023-12-06 17:28 UTC by cnotv

### Summary
Fixes #10116

### Occurred changes and/or fixed issues

Added artifacts upload on failure with 2 days of retention for the paths:
```
          /tmp/tmp.**/test-app
          !/tmp/tmp.**/test-app/node_modules/
          !/tmp/tmp.**/test-app/pkg/test-pkg/node_modules/
```

### Technical notes summary

- ~Commented removal logic for the process.~ Conditionally persisted build, default to remove
- Added logs for removed paths
- Updated RegEx to include `-alpha.x`, `-releasex.x.x` and `-rc.x` while selecting versions
- Excluded paths for `elemental-ui/` and `kubewarden-ui/` for eslint

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-12-07 10:52 UTC, aalves08 submitted a review, later dismissed
I don't see any problems with it. lgtm. @nwmac any input here?

2023-12-07 11:13 UTC, nwmac submitted a review, later dismissed
Like the idea - one ask on the folder removes, so that it still works cleanly when run locally for dev.

2023-12-07 12:22 UTC, cnotv commented on shell/scripts/test-plugins-build.sh
> +# rm -rf ${BASE_DIR}/pkg/test-pkg
I've also added a log with the path, so it's easier to see if it runs and what it removes.

2023-12-07 12:32 UTC, cnotv commented
@aalves08 Overnight this error started to appear:

```
npm ERR! code EPUBLISHCONFLICT
npm ERR! publish fail Cannot publish over existing version.
npm ERR! publish fail Update the 'version' field in package.json and try again.
npm ERR! publish fail 
npm ERR! publish fail To automatically increment version numbers, see:
npm ERR! publish fail     npm help version
```

Any hint?

2023-12-07 14:47 UTC, cnotv commented
> @aalves08 Overnight this error started to appear:
> 
> ```
> npm ERR! code EPUBLISHCONFLICT
> npm ERR! publish fail Cannot publish over existing version.
> npm ERR! publish fail Update the 'version' field in package.json and try again.
> npm ERR! publish fail 
> npm ERR! publish fail To automatically increment version numbers, see:
> npm ERR! publish fail     npm help version
> ```
> 
> Any hint?

@aalves08 @nwmac the issue seems to appear since the publication in NPM just to let you know https://www.npmjs.com/package/@rancher/components

2023-12-07 15:26 UTC, cnotv commented
@aalves08 Solved 😄

2023-12-07 16:32 UTC, aalves08 submitted a review, later dismissed
LGTM

2023-12-07 16:55 UTC, cnotv commented
@aalves08 we need @nwmac approval due change file request

2023-12-11 11:35 UTC, richard-cox requested changes
three minor comments about indentation.

i haven't tested the `sed` reg ex, but tested the non-escaped reg ex for semver and look ok

2023-12-11 11:35 UTC, richard-cox commented on shell/scripts/test-plugins-build.sh
> +  echo "Removing folder ${DIR}"
indentation

2023-12-11 11:35 UTC, richard-cox commented on shell/scripts/test-plugins-build.sh
> +  echo "Removing folder ${BASE_DIR}/$REPO_NAME"
indentation

2023-12-11 11:35 UTC, richard-cox commented on shell/scripts/test-plugins-build.sh
> +sed -i.bak -e "s/\"version\": \"[0-9]*.[0-9]*.[0-9]*\(-alpha\.[0-9]*\|-release[0-9]*.[0-9]*.[0-9]*\|-rc\.[0-9]*\)\{0,1\}\",/\"version\": \"${SHELL_VERSION}\",/g" ${SHELL_DIR}/package.json
comment only. at some point we should just use the suggested semver regex https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string. if this is tested and works though, no need to go through another round

2023-12-11 11:52 UTC, richard-cox approved these changes

2023-12-11 21:04 UTC, merged