Fixed comments on PR #9735
rancher/dashboard pull request #10160
Opened 2023-12-14 19:26 UTC by eva-vashkevich

### Summary
Fixes #10159

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-12-19 16:20 UTC, richard-cox requested changes
- one re-opened comment https://github.com/rancher/dashboard/pull/9735#discussion_r1431632508
- 4 similar requests to move components only used by their tab components

2023-12-19 16:20 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/tabs/Etcd.vue
> +import S3Config from '@shell/edit/provisioning.cattle.io.cluster/S3Config';
this is only used from this component. to keep things neat in the prov cluster folder can the same be done for this?

provisioning.cattle.io.cluster/tabs/etcd/index.vue
provisioning.cattle.io.cluster/tabs/etcd/S3Config.vue

2023-12-19 16:20 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/tabs/Networking.vue
> +import ACE from '@shell/edit/provisioning.cattle.io.cluster/ACE';
same as per etcd and S3Config,  this ACE can move in to it's parent components folder

2023-12-21 17:32 UTC, aalves08 approved these changes
Testing and codewise, LGTM @eva-vashkevich , so I think this can go in.

For another issue, perhaps, but I've seen that the `additional manifest` doesn't reset if you change the `Container Network` under `Basics` tab. I don't know if this is the correct behaviour or not.

https://github.com/rancher/dashboard/assets/97888974/a58eb330-81c8-4be0-a6ef-75d91bc1a671

This was already happening on `v2.8.0` so I don't think it's a problem for this PR. 

What's your opinion @nwmac or @richard-cox ?

2023-12-21 17:57 UTC, merged