fix(ContainerLogs): fix display error if log is truncated
rancher/dashboard pull request #10197
Opened 2023-12-22 03:39 UTC by ly5156

### Summary
Fixes #10196

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-12-22 11:02 UTC, aalves08 requested changes
Left some comments. Overall a bit lost reviewing this as I don't have any experience with these kind of operations done by your functions.

We do need to add some unit tests to this PR in order to verify the integrity of the basic usecases that this component covers + the functionality you are adding here.

2023-12-22 11:02 UTC, aalves08 commented on shell/components/nav/WindowManager/ContainerLogs.vue
> +        data.trim().split('\n').forEach((line) => {
understand why you do the `trim` but `data.trim().split('\n')` I feel it's again a sequence of operations that might throw an error if something doesn't start off with the correct type or expected content

2023-12-25 01:35 UTC, ly5156 commented
@aalves08 
Thanks for reviewing the code, I've added some comments.

2024-01-02 15:36 UTC, aalves08 approved these changes
LGTM

2024-01-02 17:37 UTC, merged