Bugfix/10171 yaml pod spec
rancher/dashboard pull request #10208
Opened 2024-01-02 22:19 UTC by rak-phillip

### Summary
Fixes #10171

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2024-01-02 23:58 UTC, rak-phillip commented on shell/edit/workload/mixins/workload.js
> -    }
I don't believe that this is required anymore as it appears to have existed so that we can translate a valid pod spec into an invalid one.

2024-01-02 23:59 UTC, rak-phillip commented on shell/edit/workload/mixins/workload.js
> +    let podTemplateSpec = type === WORKLOAD_TYPES.CRON_JOB ? spec.jobTemplate.spec.template.spec : this.value.type === POD ? spec : spec?.template?.spec;
I might consider rewriting this so that it's much more clear that we have multiple conditionals to deal Pods, Cron job, and the rest.

2024-01-03 00:02 UTC, rak-phillip commented on shell/edit/workload/mixins/workload.js
>          (this.mode === _CREATE || this.realMode === _CLONE)
This might be another case where we want to add

```
this.type !== POD
```

2024-01-03 09:30 UTC, richard-cox commented
Just a note, i don't think there'll be conflicts or changes, but there's some work in a pending [pr](https://github.com/rancher/dashboard/pull/10037) around the area of saving workloads. I think this PR might make a line or two of that redundant

2024-01-11 00:36 UTC, mantis-toboggan-md requested changes

2025-04-09 19:53 UTC, closed without merging