Fix highlight main nav menu items
rancher/dashboard pull request #10212
Opened 2024-01-03 12:32 UTC by aalves08

### Summary
Fixes #10010 

### Occurred changes and/or fixed issues

- Add method `checkActiveRoute` to check and apply a class `active-menu-link` to main nav menu items
- Update Fleet product route to enforce the use of `blank` cluster
- Update e2e tests in key places to check if main nav menu items are highlighted correctly when navigating to sub-routes
- Update e2e tests for Fleet to navigate to it's routes using `blank` cluster

### Technical notes summary

### Areas or cases that should be tested

- Generally test navigation to all the different products Rancher Dashboard has to offer

### Areas which could experience regressions

### Screenshot/Video

<img width="1719" alt="Screenshot 2024-01-03 at 12 30 45" src="https://github.com/rancher/dashboard/assets/97888974/634ffd3e-4478-4f82-9968-9658d4a8802f">

2024-01-08 18:11 UTC, richard-cox requested changes

2024-01-09 08:51 UTC, aalves08 commented on cypress/e2e/tests/pages/charts/istio.spec.ts
> +        BurgerMenuPo.burgerMenuGetNavClusterbyLabel('local').parent().should('have.class', 'active-menu-link');
updated

2024-01-09 08:53 UTC, aalves08 commented on shell/components/nav/TopLevelMenu.vue
> +        return this.$route?.name?.startsWith('c-cluster') && this.$route?.params?.cluster === obj?.id && getProductFromRoute(this.$route) === this.currentProduct?.name;
🤦 fixed

2024-01-10 09:43 UTC, aalves08 commented on shell/components/nav/TopLevelMenu.vue
> +      if (isClusterRoute && this.$route?.name?.startsWith('c-cluster') && this.currentCluster?.id === obj?.id) {
updated with comments and simplified logic

2024-01-15 13:32 UTC, richard-cox approved these changes

2024-01-15 14:10 UTC, merged

2024-01-23 21:01 UTC, izaac commented on cypress/e2e/tests/pages/charts/istio.spec.ts
> +        BurgerMenuPo.checkIfClusterMenuLinkIsHighlighted('local');
There is an existging `clusterName` variable on the top describe