Fix registry host not being synced with its secret
rancher/dashboard pull request #10397
Opened 2024-02-02 20:52 UTC by momesgin

### Summary
Fixes #10314 

There are more issues related to the Registries section(#10371 & #10093) that might affect this, but for now this change should only fix #10314 without breaking other functionalities there.

`registrySecret`(shown as Authentication field under Container Host field) was being extracted from the first host name in list of host names in registries.configs, but this field should look for the container host name(`registryHost`) in that list.

### Screenshot/Video

https://github.com/rancher/dashboard/assets/135728925/143f785d-d174-4a4e-bae9-76524499d177

2024-02-08 12:17 UTC, richard-cox requested changes
#10314 is resolved, but #10093 is still reproducible.

the fix for #10314 is good, i gave a go with a system registry config as well... and that works fine

2024-02-08 20:05 UTC, momesgin commented on cypress/e2e/tests/pages/manager/registries-rke2.spec.ts
> +const clusterName = `test-cluster-${ Math.random().toString(36).substr(2, 6) }`;
Thanks for letting me know about this, done.

2024-02-08 20:05 UTC, momesgin commented on shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue
> +              data-testid="registry-auth-host-input"
thanks, done.

2024-02-08 20:33 UTC, momesgin commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +      const config = regs.configs[this.registryHost];
@richard-cox thanks for spending the time on this and sharing your findings 🙏, I was confused too about the distinction between the root url and the rest of the registry urls.

Regarding #10093 maybe I'm missing something, I saw your comment pointing to the condition in `rke2.vue`:
``` 
    if ( hostname && this.registrySecret ) {
        ...
```
are you suggesting that the root url should be added to `registries.configs` no matter if it has a secret or not? my thinking was having it set as `system-default-registry` is sufficient. I've recorded a video trying different cases for the root url as well as the other registry url without selecting a secret. 

Notes about the video:
- I've added a console log right before the condition^
- ignore the `create-yaml.js` errors on console, it's not affecting these scenarios. There's an [open PR](https://github.com/rancher/dashboard/pull/10422) for it too.
- if you try adding CA Cert Bundle you get an error(at the end of the video) that I think it's unrelated too


https://github.com/rancher/dashboard/assets/135728925/8da0146e-a2d0-4bf0-8ec8-2ba06d89c125

2024-02-08 20:33 UTC, momesgin commented on cypress/e2e/po/components/registries-rke2.po.ts
> +    new TabbedPo().clickTabWithSelector(selector);
done

2024-02-08 20:44 UTC, momesgin commented on cypress/e2e/po/components/registries-rke2.po.ts
> +export default class RegistriesRke2 extends ComponentPo {
Sorry I'm not quiet sure what you suggest here, do we have an example in our codebase?

2024-02-12 15:00 UTC, richard-cox commented on cypress/e2e/po/components/registries-rke2.po.ts
> +export default class RegistriesRke2 extends ComponentPo {
If you check out the PO that will map to Components
cypress/e2e/po/components/unit-input.po.ts --> shell/components/form/UnitInput.vue 
cypress/e2e/po/detail/management.cattle.io.user.po.ts --> shell/detail/management.cattle.io.user.vue
cypress/e2e/po/pages/about.po.ts --> shell/pages/about.vue

For this case 
shell/edit/provisioning.cattle.io.cluster/tabs/registries/index.vue --> PO for the registry tab aka  RegistriesTabPo
shell/edit/provisioning.cattle.io.cluster/tabs/registries/RegistryConfigs.vue --> PO for the registry config aka RegistyConfigsPo

as tabs/registries/index.vue contains the registryconfig component the PO hierarchy would be similar. so something like
```
RegistriesTabPo {
  registryConfigs(): RegistyConfigsPo {
   new RegistyConfigsPo()
 }
}```

2024-02-12 15:38 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +      const config = regs.configs[this.registryHost];
Not sure what happened, but i could reproduce https://github.com/rancher/dashboard/issues/10093 in this PR. I've also checked head and can no longer reproduce it there either. 

Looked through the code again and updated my comment. The root registry should go in the machineSelectorConfig config object, the first without a selector. I've confirmed that's happening in this PR

2024-02-12 15:39 UTC, richard-cox requested changes
just 1 e2e change to go

2024-02-12 23:31 UTC, momesgin commented on cypress/e2e/po/components/registries-rke2.po.ts
> +export default class RegistriesRke2 extends ComponentPo {
thanks for the details 🙏, done

2024-02-13 09:13 UTC, richard-cox approved these changes
Ship it!

2024-02-13 16:44 UTC, merged

2024-02-26 21:45 UTC, rak-phillip commented
/backport v2.8.next1 release-2.8