Add root product concept to improve performance of nav change within inExplorer products
rancher/dashboard pull request #10447
Opened 2024-02-13 15:32 UTC by nwmac

TODO - draft for review

Note: TODO: There is a bug here - provision a down stream cluster. When you switch between the local and downstream clusters, the cluster explorer nav does not update and the total count boxes do not update either. 

This PR improves the performance when switching between child products of explorer - to test, install Longhorn and NeuVector - these are two simple products.

With this PR, switching between them is much faster as the 'rootProduct' (explorer) does not change, even though the current (child) product does - this means less gets re-evaluated.

2024-02-29 14:36 UTC, richard-cox requested changes
I get the following error when switching from the cluster dashboard page to CIS Benchmark

```
SideNav.vue:381 [Vue warn]: You may have an infinite update loop in watcher with expression "namespaceFilter"

found in

---> <ResourceList> at shell/components/ResourceList/index.vue
       <ClusterResourcedList> at shell/pages/c/_cluster/_product/_resource/index.vue
         <Shell/components/templates/default.vue> at shell/components/templates/default.vue
           <Root>
```

It's in an odd place, but i couldn't reproduce on v2.8.0 or v2.9-head (with new ui, old non-schema diet backend)

2024-03-05 08:58 UTC, nwmac commented on shell/store/type-map.js
> +      existing.rootProduct = existing.rootProduct || EXPLORER;
Yes, good spot!

2024-03-05 08:58 UTC, nwmac commented on shell/store/index.js
> +    return !product ? false : product.name === EXPLORER;
Yup. Thanks

2024-03-05 12:09 UTC, nwmac commented on shell/store/type-map.js
> +      existing.rootProduct = existing.rootProduct || EXPLORER;
Yeah, I've changed it

2024-03-05 15:48 UTC, nwmac commented on shell/components/SideNav.vue
> +    ...mapGetters(['productId', 'clusterId', 'currentProduct', 'rootProduct', 'isSingleProduct', 'namespaceMode', 'isExplorer', 'isVirtualCluster']),
Yeah - I was striking a balance to not go too far.

2024-03-08 15:15 UTC, richard-cox approved these changes

2024-03-28 09:28 UTC, merged