remove v1 monitoring code
rancher/dashboard pull request #10539
Opened 2024-02-29 19:57 UTC by aalves08

### Summary
Fixes #10490 

### Occurred changes and/or fixed issues

- remove v1 monitoring code

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-02-29 19:59 UTC, aalves08 commented
@nwmac @richard-cox added you both as reviewers since this need a keen eye. I went to each of those views and all looked good. 
Not fully sure if the `uninstall` can all go away, but I believe I captured the correct code removal. Didn't test this... Is it testable even?

2024-03-01 11:18 UTC, richard-cox requested changes
There's a couple of items in the checklist that still need doing

```
The PR template has been filled out
The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
```

Automated test side, we probably need some to cover below. Hopefully all have existing tests though
- Node list --> click on one --> confirm something trivial on page
- Workload list --> click on one --> confirm something trivial on page
- Cluster Dashboard --> confirm something trivial on page

Monitoring is a bit more of a pain, would need some manual tests for that (it's a honker to install on the small image used by gh ci)

2024-03-11 11:51 UTC, aalves08 commented
@richard-cox the issue has `QA/None` label... Should I change it to `QA/manual-test`?

2024-03-20 16:31 UTC, richard-cox requested changes

2024-03-22 10:19 UTC, aalves08 commented on cypress/e2e/po/components/sortable-table.po.ts
> +    // return this.self().contains(`tbody tr:nth-child(${ index })`);
Removed. Thanks

2024-03-22 16:41 UTC, richard-cox approved these changes

2024-03-22 17:39 UTC, merged