[2.8 Backport] Registry auth fix
rancher/dashboard pull request #10530
Opened 2024-02-28 23:17 UTC by momesgin

Fixes #10514  and #10337 

Backport of PR to 2.8 => https://github.com/rancher/dashboard/pull/10397

Note: The folder re-structuring around `rke2.vue` doesn't exist in 2.8 so the changes ported to 2.8 a bit differently. Also some minor changes needed to make the e2e tests work.

2024-02-29 15:27 UTC, richard-cox requested changes
The changes look good, but there's an error... and in both this PR and master a regression

- In this PR i get an error 
  ```
  Error: Unable to parse map data for yaml of type: map[provisioning.cattle.io.v1.cluster.spec.rkeConfig.registries.configs] TypeError: data[k].includes is not a function
    at create-yaml.js:463:1
    at Array.filter (<anonymous>)
    at dumpBlock (create-yaml.js:463:1)
    at stringifyField (create-yaml.js:242:1)
    at create-yaml.js:177:1
    at Array.map (<anonymous>)
    at createYaml (create-yaml.js:177:1)
    at stringifyField (create-yaml.js:340:1)
    at create-yaml.js:177:1
    at Array.map (<anonymous>)
  ```
- https://github.com/rancher/dashboard/issues/10514 is back again. Interestingly it's kind of doing the right thing. a secret is created and it shows that as selected... however it appears in both the root Authentication drop down as well as the `Registry Authentication` section. The original PR showed a video of this working (not shown in root, just `Registry Authentication`)
a.resgistry.com

2024-02-29 16:58 UTC, momesgin commented
> The changes look good, but there's an error... and in both this PR and master a regression
> 
> * In this PR i get an error
>   ```
>   Error: Unable to parse map data for yaml of type: map[provisioning.cattle.io.v1.cluster.spec.rkeConfig.registries.configs] TypeError: data[k].includes is not a function
>     at create-yaml.js:463:1
>     at Array.filter (<anonymous>)
>     at dumpBlock (create-yaml.js:463:1)
>     at stringifyField (create-yaml.js:242:1)
>     at create-yaml.js:177:1
>     at Array.map (<anonymous>)
>     at createYaml (create-yaml.js:177:1)
>     at stringifyField (create-yaml.js:340:1)
>     at create-yaml.js:177:1
>     at Array.map (<anonymous>)
>   ```
> * [[backport v2.8.next1] Registry authentication method is modified unexpectedly #10514](https://github.com/rancher/dashboard/issues/10514) is back again. Interestingly it's kind of doing the right thing. a secret is created and it shows that as selected... however it appears in both the root Authentication drop down as well as the `Registry Authentication` section. The original PR showed a video of this working (not shown in root, just `Registry Authentication`)
>   a.resgistry.com

The console error has another backport issue that I will take care of. I'm not getting the regression part though, do you mean that if you have bla.com as the root url and a secret for it from the dropdown(top section on the UI), then if you have the same url again in Registry Authentication but with different secret(the bottom section) we should NOT overwrite the secret for the root?

2024-02-29 17:27 UTC, richard-cox commented
> The console error has another [backport issue](https://github.com/rancher/dashboard/issues/10532) that I will take care of. 

Let's get that one in then rebase this one.

> I'm not getting the regression part though, do you mean that if you have bla.com as the root url and a secret for it from the dropdown(top section on the UI), then if you have the same url again in Registry Authentication but with different secret(the bottom section) we should NOT overwrite the secret for the root?

It's basically the issue from https://github.com/rancher/dashboard/issues/10514.  A secret supplied via the Registry Authentication section should not then be shown in the root secret, even if the urls match. That was fixed in the video you had in the `master` PR

2024-02-29 17:52 UTC, momesgin commented
> > The console error has another [backport issue](https://github.com/rancher/dashboard/issues/10532) that I will take care of.
> 
> Let's get that one in then rebase this one.
> 
> > I'm not getting the regression part though, do you mean that if you have bla.com as the root url and a secret for it from the dropdown(top section on the UI), then if you have the same url again in Registry Authentication but with different secret(the bottom section) we should NOT overwrite the secret for the root?
> 
> It's basically the issue from #10514. A secret supplied via the Registry Authentication section should not then be shown in the root secret, even if the urls match. That was fixed in the video you had in the `master` PR

Here's [the PR](https://github.com/rancher/dashboard/pull/10397) with the video, at the end of the video the dropdown for the root's secrets gets opened and it has the secrets from Registry Auth too. Actually overwriting the root's secret when its url matches the one from Registry Auth was intended! but based on your comment seems that the fix should be very different.

2024-02-29 18:25 UTC, momesgin commented
@richard-cox for example if I create a secret for the root with `bla.io` url this yaml get's generated:

```
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
          system-default-registry: bla.io
    registries:
      configs:
        bla.io:
          authConfigSecretName: registryconfig-auth-6k999
```

the secret gets saved in registries.configs with the url as its key, now if you add a registry auth it will also be added to registries.configs meaning if the key(url) is the same it gets overwritten

2024-03-01 10:08 UTC, richard-cox approved these changes
Ok, missed a key detail, the linked issue had a different root url to the entry in the registry auth. i was testing with the same url in both and thought it was a bug that the root auth was updated.... when as you stated that's working as expected

2024-03-01 17:30 UTC, momesgin commented
> Ok, missed a key detail, the linked issue had a different root url to the entry in the registry auth. i was testing with the same url in both and thought it was a bug that the root auth was updated.... when as you stated that's working as expected

oh I see, thanks for reviewing it, I'm glad the fix was correct 😮‍💨

2024-03-01 18:55 UTC, merged