Fetch `statefulset` resources to check fleet agent status
rancher/dashboard pull request #10755
Opened 2024-04-04 20:26 UTC by torchiaf

### Summary
Fixes https://github.com/rancher/dashboard/issues/10738

### Occurred changes and/or fixed issues

We are adding the fleet's StatefulSet in agent status calculation, for downstream clusters.

### Technical notes summary

- local clusters:
  - using both StatefulSet and Deployment
- rke2 downstream clusters:
  - using StatefulSet since the deployment does not exist.

### Areas or cases that should be tested

- cluster's dashboard -> healthboxes.

### Areas which could experience regressions

### To test

See https://github.com/rancher/dashboard/pull/10614 description.

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-04-08 16:00 UTC, richard-cox requested changes
- `shell/pages/c/_cluster/explorer/index.vue` `fetch`  `loadAgents` should not be blocking.

2024-04-08 16:00 UTC, richard-cox commented on shell/pages/c/_cluster/explorer/index.vue
> +        if (!resource) {
this can just be combined with the below loop

2024-04-08 16:00 UTC, richard-cox commented on shell/pages/c/_cluster/explorer/index.vue
> +          await this.setAgentResource('fleetDeployment', WORKLOAD_TYPES.DEPLOYMENT, 'cattle-fleet-system/fleet-controller');
can both these two be called at the same time, or can we not `await` them at all? same goes for the two requests below

2024-04-09 08:13 UTC, torchiaf commented on shell/pages/c/_cluster/explorer/index.vue
> +        this[agent] = await this.$store.dispatch('cluster/find', { type, id });
There is a `canViewAgents` variable, but it isn't checking the `statefulset` visibility.

2024-04-09 13:39 UTC, richard-cox approved these changes

2024-04-09 16:28 UTC, merged