update developer docs
rancher/dashboard pull request #10901
Opened 2024-04-29 19:40 UTC by yonasberhe23

### Summary

Fixes #https://github.com/rancher/qa-tasks/issues/1293

### Occurred changes and/or fixed issues
Update docs to include best practices discussed with the UI team regarding how to utilize POs and cleaning up resources at the end of tests.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [ ] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-04-30 09:57 UTC, richard-cox requested changes
One tiny request, otherwise looks like a good addition

2024-04-30 09:57 UTC, richard-cox commented on docusaurus/docs/testing/e2e-test.md
> +- When selecting an element be sure to use the attribute `data-testid`, even in case of lists where elements are distinguished by an index suffix.
Could we change this to request if the data-testid exist it should be used?

2024-04-30 13:13 UTC, izaac reviewed
Looks good, let's address other reviews and I'll do a final pass.

2024-05-07 08:00 UTC, richard-cox approved these changes

2024-05-08 18:00 UTC, merged