Add hooks to support virtual clusters
rancher/dashboard pull request #11064
Opened 2024-05-21 10:52 UTC by nwmac

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-06-14 19:15 UTC, nwmac commented
@mantis-toboggan-md finally got this to pass gates - refactored as we discussed.

2025-01-24 17:27 UTC, aalves08 reviewed
Reviewing this, changes seem pretty self self-contained as it's targeting the `provisioning.cattle.io.cluster`. I assume that since this is experimental, we don't want to document it right now, but in the future, if we open it, we need to add it to the documentation.

One last remark would be around using `modelExtensions` instead of extending/reusing `uiConfig` 🤔 

nevertheless, I would say that it LGTM

2025-01-24 17:54 UTC, richard-cox requested changes
Haven't given this a functional test, just looked at code.

Only minor comments. We are limiting model extensions to be singular though. Not sure we'll ever be in a scenario where different extensions might want to update things like deployment actions?

2025-01-24 17:54 UTC, richard-cox commented on shell/core/types-provisioning.ts
> +  useForModel(cluster: any): boolean;
this isn't wired in anywhere

2025-01-24 17:54 UTC, richard-cox commented on shell/core/types.ts
> +  addModelExtension(type: string, clz: Function): void;
given `clz` is a known function here (and shell/core/plugin.ts) should be typed

2025-01-24 17:54 UTC, richard-cox commented on shell/list/provisioning.cattle.io.cluster.vue
> +    groupable() {
this is going to break with Cody's SSP PR. We won't have access to all provisioning clusters (filteredRows) just a single pages worth.

2025-01-24 17:54 UTC, richard-cox commented on shell/models/provisioning.cattle.io.cluster.js
> +    return this.modelExtensions.find((modelExt) => modelExt.useFor ? modelExt.useFor(this) : false);
should there be a type / interface for modelExtension instances? missing this fn will trip up developers

2025-01-24 17:54 UTC, richard-cox commented on shell/models/provisioning.cattle.io.cluster.js
> +  get groupByLabel() {
Think this is fine now, so just a comment, but in the future the plan is to group clusters by cluster class as well

2025-01-24 17:54 UTC, richard-cox commented on shell/models/provisioning.cattle.io.cluster.js
> +    // Customer helper can report if the cluster has a parent cluster
typo `Customer`

2025-01-27 14:57 UTC, nwmac commented on shell/core/types-provisioning.ts
> +  useForModel(cluster: any): boolean;
This should be `useFor` - will fix

2025-01-27 15:23 UTC, nwmac commented on shell/models/provisioning.cattle.io.cluster.js
> +    return this.modelExtensions.find((modelExt) => modelExt.useFor ? modelExt.useFor(this) : false);
This code is javascript. The useFor is on the interface for the cluster provisioning extension - this was incorrectly `useForModel` - that has been fixed.

2025-01-27 16:41 UTC, nwmac commented on shell/models/provisioning.cattle.io.cluster.js
> +    // Customer helper can report if the cluster has a parent cluster
Removed this way of grouping

2025-01-27 16:41 UTC, nwmac commented on shell/models/provisioning.cattle.io.cluster.js
> +  get groupByLabel() {
Removing this - an extension can change the grouping for a type via the type configuration

2025-01-29 15:37 UTC, mantis-toboggan-md approved these changes
LGTM - I tested this by running code against the virtual clusters ui poc

2025-01-30 08:57 UTC, richard-cox approved these changes

2025-01-31 08:51 UTC, merged