Added "Show deprecated apps" filter to charts page plus warnings
rancher/dashboard pull request #11279
Opened 2024-06-21 01:07 UTC by momesgin

### Summary
Fixes #11042 

### Occurred changes and/or fixed issues

- Previously the only way to see the deprecated apps in the Charts page was by adding `deprecated` query param to the url.
- A new checkbox added to the Charts page labeled as "Show deprecated apps" which is disabled by default.
- If the checkbox is enabled you'll be able to see the deprecated charts.
- A "Deprecated" badge is shown on each card, and if a chart is both deprecated and experimental only the deprecated badge will be shown.
- Previously a deprecated chart's page was kinda broken since we would not make an api call to get the chart's info.
- If "Show deprecated apps" filter is enabled when you click on a card a `deprecated` query param is added to that chart's url
- Warning banners will be displayed for deprecated, experimental and both in the chart's page.

### Areas or cases that should be tested

Using different filters on the charts page, and make sure the above items are working as expected.

### Areas which could experience regressions

Make sure the charts page is working as expected.

### Screenshot/Video

https://github.com/rancher/dashboard/assets/135728925/7f5949bb-784b-4015-bae2-023b10fc4d15

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-06-24 16:19 UTC, jordojordo requested changes
One small change, otherwise LGTM.

2024-06-24 16:19 UTC, jordojordo commented on cypress/e2e/tests/pages/explorer/apps/charts.spec.ts
Is it possible to add one step to the 'Show deprecated apps filter' to test the `deprecated` query param being passed into the route?

2024-06-27 15:53 UTC, momesgin commented on cypress/e2e/tests/pages/explorer/apps/charts.spec.ts
done

2024-06-27 17:11 UTC, codyrancher approved these changes

2024-06-27 17:54 UTC, merged