Add agent tls mode to global settings
rancher/dashboard pull request #11287
Opened 2024-06-21 17:34 UTC by jordojordo

### Summary
Fixes #11138 

### Occurred changes and/or fixed issues

This will add the `agent-tls-mode` setting to the Global Settings page, as well as a new optional property `warning` on the `GlobalSettings` interface that will display a warning banner when editing the setting.

### Technical notes summary

The setting is an `enum` with two values: `strict` and `system-store`

To add a warning to the setting, the `advancedSettings.warnings` translation will require a property named after the setting, in this case `agent-tls-mode`.

### Areas or cases that should be tested

Testing the setting works with both values, ensure the warning banner shows.

### Areas which could experience regressions

N/A

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-06-25 09:25 UTC, richard-cox requested changes
One suggested change for description, otherwise everything else looks good

2024-06-25 09:25 UTC, richard-cox commented on shell/assets/translations/en-us.yaml
> +    'agent-tls-mode': 'TLS mode for agent communication.'
```suggestion
    'agent-tls-mode': "Rancher Certificate Verification. In `strict` mode the agents (system, cluster, fleet, etc) will only trust Rancher installations which are using a certificate signed by the CABundle in the `cacerts` setting. When the mode is system-store, the agents will trust any certificate signed by a CABundle in the operating system’s trust store."
```

2024-06-25 15:15 UTC, richard-cox approved these changes

2024-06-27 16:58 UTC, nwmac commented
@jordojordo This looks like it was approved but then commits pushed - don't know if that was to get a fix for e2e tests?

It looks like the automated test that was added is failing.

2024-06-28 09:32 UTC, nwmac approved these changes

2024-06-28 10:55 UTC, nwmac commented
@jordojordo I fixed the e2e tests and rebased and bumped this PR - I think this is ready to be merged.

2024-06-28 11:21 UTC, merged