EKS: edit imported clusters, and clusters with exclusively self-managed nodes
rancher/dashboard pull request #11294
Opened 2024-06-25 18:57 UTC by mantis-toboggan-md

### Summary
Fixes #11100 
Fixes #11104 
Fixes #10335 

### Occurred changes and/or fixed issues
This PR updates EKS provisioning to incorporate the same upstream syncing behavior as AKS - see https://github.com/rancher/dashboard/pull/11120 for some background on why this is needed. This PR adds some fixes to the syncing utility as well as unit tests around the problems I found while working on the PR. There are also some minor fixes around the EKS components to correct console errors shown when editing an imported cluster.

Special notes about EKS:
- imported clusters with no nodeGroups are valid (they may have self-managed nodes)
- After following aws instructions to create an EKS cluster with default values and importing it into Rancher, the subnet/virtual network configuration is indistinguishable from an EKS cluster provisioned in Rancher with the 'Create a new VPC and subnet automatically' option selected. The old UI just shows that option selected for imported clusters. 
- In this PR I updated the networking tab to use the subnets from the upstream status instead, so the user can see which VPC/subnets are in use by the current cluster.

### Areas or cases that should be tested
1. Edit an imported cluster with exclusively self-managed nodes (no node groups)
     - no console errors shown
     - user should be able to save the cluster without having added node groups
     - user should be able to add and remove node groups
2. Edit an imported cluster with node groups
    - user should be able to make all the same changes as they can with a Rancher-provisioned EKS cluster
    - the networking tab should show a list of selected subnets

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-06-27 09:38 UTC, torchiaf commented on pkg/eks/components/CruEKS.vue
> +        delete this.normanCluster.eksConfig.nodeGroups;
`this.normanCluster.eksConfig` is possibly undefined. We can include it in the if condition before delete.

2024-06-27 09:55 UTC, torchiaf commented
I tired to add and remove some node groups. While the cluster is `updating` and I click on edit button, some fields are still enabled. Is it a wanted behavior ?

![image](https://github.com/rancher/dashboard/assets/26394656/072fb434-b92d-4af8-bfae-b81d5fd85a99)

2024-06-27 10:03 UTC, torchiaf approved these changes
LGTM, just a comment about null checks.

2024-06-27 10:06 UTC, torchiaf requested changes
Just a comment to add the null check.

2024-07-02 17:42 UTC, mantis-toboggan-md commented
Updated to include https://github.com/rancher/dashboard/issues/11291 - the same syncUpstreamConfig functionality needs to be added to GKE provisioning. No extra logic around node groups needed for GKE though.

2024-07-02 17:45 UTC, mantis-toboggan-md commented
I hit an additional issue with this: due to pre-existing norman api validation it's not possible to add node groups then delete all node groups through the UI. I've separated that out into a different issue, as it needs backend work as well and the other fixes in this PR are required to reproduce the bug.

2024-07-03 07:53 UTC, torchiaf approved these changes
LGTM

2024-07-03 13:53 UTC, merged