[FIX] Fixed some issues with driver pages
rancher/dashboard pull request #11316
Opened 2024-07-01 06:19 UTC by eva-vashkevich

### Summary
Fixes #11046 #10718 

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-07-02 13:37 UTC, nwmac commented
@aalves08 @richard-cox Adding you as reviewers, in case you have time to help review this and get this in.

2024-07-02 15:31 UTC, richard-cox requested changes
only one small comment, otherwise looking good

2024-07-02 15:31 UTC, richard-cox commented on shell/dialog/DeactivateDriverDialog.vue
> +          this.$store.dispatch('rancher/request', {
this promise should be returned

2024-07-02 16:51 UTC, richard-cox approved these changes

2024-07-02 16:51 UTC, richard-cox commented
If there are no overnight objections to my tweak, will merge tomorrow AM UK time

2024-07-03 09:26 UTC, richard-cox approved these changes

2024-07-03 14:11 UTC, aalves08 commented
@richard-cox I think Eva is out, right? If it's approved can it be merged?

2024-07-03 14:20 UTC, richard-cox commented
Yep, just been tickling gates after rebase.

2024-07-03 14:20 UTC, merged