Fixing harvester cluster page reload routing
rancher/dashboard pull request #11359
Opened 2024-07-04 17:20 UTC by torchiaf

### Summary
Fixes #11350

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-07-04 18:51 UTC, codyrancher approved these changes

2024-07-05 09:00 UTC, richard-cox requested changes
This doesn't solve the issue of navigating to a harvester cluster when logged out. The management store is needed, which is why the original extension route loading flow was in authenticated after loadManagement.

I'm not sure placing loadManagement in the entry-help is the right process, will investigate

Edit: loadManagement cannot be called as the schemas cannot be fetched as the user is not logged in

2024-07-05 15:16 UTC, codyrancher commented
> This doesn't solve the issue of navigating to a harvester cluster when logged out. The management store is needed, which is why the original extension route loading flow was in authenticated after loadManagement.
> 
> I'm not sure placing loadManagement in the entry-help is the right process, will investigate
> 
> Edit: loadManagement cannot be called as the schemas cannot be fetched as the user is not logged in

I'll take a look, I think we can move this out of the render and into a navigation guard to resolve the login issue.

2024-07-08 06:31 UTC, codyrancher commented
@richard-cox I think that this change should still be merged. I've created a new PR to address the authenticated issue https://github.com/rancher/dashboard/pull/11373

2024-07-08 09:16 UTC, richard-cox approved these changes

2024-07-08 09:24 UTC, merged