update extensions documentation for Rancher 2.9 updates
rancher/dashboard pull request #11362
Opened 2024-07-05 08:54 UTC by aalves08

### Summary
Fixes #11361 

### Occurred changes and/or fixed issues

- Create page to cover the Rancher 2.9 updates
- Create support matrixes page to aggregate all of the support matrixes available in the documentation in one easy-to-access page
- added shell version support matrix
- Other small updates

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

![screencapture-localhost-3000-extensions-support-matrix-2024-07-05-09_47_15](https://github.com/rancher/dashboard/assets/97888974/9ae16acf-e764-498c-8eb2-42724fa12511)
![screencapture-localhost-3000-extensions-rancher-2-9-support-2024-07-05-09_46_55](https://github.com/rancher/dashboard/assets/97888974/c09acd0a-2f39-4cc8-b51a-c9b0fc7915fa)
<img width="1697" alt="Screenshot 2024-07-05 at 09 47 30" src="https://github.com/rancher/dashboard/assets/97888974/22109162-0887-49c7-bd65-6e0fb6ba4408">

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-07-08 08:48 UTC, richard-cox requested changes
- `2.9` vs `2.9.0`
  - Given rancher's release process with patch builds i'd vote we're clear that this is a 2.9.0 change 
- diagram 
  - `our latest stable version` will get stale quickly. maybe something like `Released Pre Rancher 2.9.0`

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +With the release of Rancher 2.9 some breaking changes were introduced to improve performance on how Rancher Dashboard deals with k8s resources in order to present it's views to the users (create, edi
```suggestion
Rancher 2.9.0 contains many improvements, unfortunately some make necessary changes that invalidate certain versions of Rancher Extensions working with certain versions of Rancher.
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +With that in mind, we have made some important changes to the Shell package (our core JS package) which needed to be updated so that extensions would work with this release of Rancher.
```suggestion
To support these changes we have made some importance changes to Rancher Shell (our core JS package) which helps and protects version compatibility.
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +At the time of writing this documentation, the latest stable Shell version was `0.5.3`. We've now updated the Shell versioning system in the following way:
```suggestion
Before Rancher 2.9.0 was released, the latest stable Shell version was `0.5.3`. From 2.9.0 we have updated the Shell versioning system in the following way:
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +In a nutshell, for future releases of your extension to **work on Rancher 2.9** you will need to do another version of your extension using Shell `2.0.0`.
```suggestion
For future releases of your extension to **work on Rancher 2.9.0** you will need to build and release a new version of your extension using Shell `2.0.0`.
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +The decision to update the versions this way was to ensure that from this point forward we will have the most accurate versioning to present to developers.
Suggestion for these two paragraphs
```
These changes bring Shell versions in line with standard versioning patterns. Only major version updates are expected to container breaking changes, minor and patch versions should not.
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +- Test locally your extension with the new Shell version `2.0.0`. Also do a local build and Developer Load on the desired Rancher system to make sure everything works as expected. Check documentation
```suggestion
- In the root of your extension repository update `package.json` `@rancher/shell` to the new `2.9.0` version and `yarn install` to fetch it. Then do a local build of your extensions and `Developer Load` them on the desired Rancher version to confirm everything works as expected. Check documentation about a Developer Load [here](./extensions-getting-started#test-built-extension-by-doing-a-developer-load).
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +> With these annotations your extension will be "locked" to Rancher version greater than `2.9.0` and will also be "locked" to a UI Extensions version (Shell version) greater than or equal to `2.0.0`.
```suggestion
> With these annotations your extension will be restricted to Rancher version greater or equal to `2.9.0` and will also be restricted to a UI Extensions version (Shell version) greater than or equal to `2.0.0`.  
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +These are not mandatory but rather a good practice so that your future extension versions are correctly bound to the different systems/versions.
```suggestion
These are not mandatory but highly recommended to ensure your extension versions reference Rancher / Shell versions they're compatible with.  
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +- After the above steps, just publish a new version of the extension with Shell `2.0.0`. That published version should now be compliant with Rancher 2.9.
```suggestion
- After the above steps, just publish a new version of the extension. That published version should now be compliant with Rancher 2.9.0.
```

2024-07-08 08:48 UTC, richard-cox commented on docusaurus/docs/extensions/support-matrix.md
> +The Shell package is the core package that allows for an Extension to incorporate with a Rancher Dashboard.
```suggestion
The Shell package enables Extensions to integrate with Rancher.
```

2024-07-08 10:36 UTC, aalves08 commented
@richard-cox Thanks for the review 🙏 I've updated the PR with your recommendations

2024-07-09 11:17 UTC, aalves08 commented
@richard-cox updated with `known issues` page

2024-07-09 14:11 UTC, richard-cox requested changes
There's some suggested tweaks, some i noticed were typos in my previous review

2024-07-09 14:11 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +> With these annotations your extension will be restricted to Rancher version greater or equal to `2.9.0` and will also be restricted to a UI Extensions version (Shell version) greater than or equal
```suggestion
> With these annotations your extension will be restricted to Rancher version greater or equal to `2.9.0` and will also be restricted to a UI Extensions version (Shell version) greater or equal to `2.0.1`.  
```

2024-07-09 14:47 UTC, richard-cox commented on docusaurus/docs/extensions/rancher-2.9-support.md
> +> With these annotations your extension will be restricted to Rancher version greater or equal to `2.9.0` and will also be restricted to a UI Extensions version (Shell version) greater than or equal
Not sure if it's gh fail, but i don't see this change and the one below

2024-07-09 14:57 UTC, aalves08 commented
@richard-cox maybe I've reverted some changes done with a force-push. I think now everything is all good

2024-07-09 15:06 UTC, richard-cox approved these changes

2024-07-10 08:02 UTC, merged