Bugfix/11333 minimum value inactive user
rancher/dashboard pull request #11490
Opened 2024-07-18 20:56 UTC by rak-phillip

### Summary
Fixes #11333 

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-07-18 21:41 UTC, rak-phillip commented on shell/composables/useLabeledFormElement.ts
> +  }
This is a clear sign that there's some drift between the mixin and the composable. I created #11491 so that we can address.

2024-07-19 02:09 UTC, rak-phillip commented on shell/composables/useUserRetentionValidation.ts
> +};
I'm considering if there's a better place for our Setting type to live? I'm not a fan of keeping it colocated with code related to user retention.

2024-07-19 15:20 UTC, rak-phillip commented on shell/composables/useUserRetentionValidation.ts
> +};
I opted for `shell/types/resources/settings.d.ts`

2024-07-19 15:38 UTC, rak-phillip commented on shell/composables/useLabeledFormElement.ts
> +        emit('update:validation', false);
We might want to consider also updating `shell/mixins/labeled-form-element.ts` to avoid further drift between the two methods code sharing.

2024-07-26 18:58 UTC, mantis-toboggan-md requested changes
I see duplicate error messages for the duration format validation on the deleteAfterPeriod input:
![Screenshot 2024-07-26 at 11 40 12 AM](https://github.com/user-attachments/assets/a2e305eb-ed71-4ab2-841a-51646ac43c97)

It looks like this is due to the format of duration strings being validated within other validators. One potential solution would be to give duration formatting its own validator function, and return error messages in `validateDeleteInactiveUserAfter` and `validateDurationAgainstAuthUserSession` only when a valid duration string is passed in.



Otherwise, the PR looks good to me. I think the addition to `useLabeledFormElement` is a solid way of making the composable function without the form validation mixin. I've attempted to use input-level error reporting without the form validation mixin in another repo myself, and this change would have made that considerably tidier. I would also be in favor of adding it to the `labeled-form-element` mixin.

2024-07-29 17:31 UTC, rak-phillip commented
@mantis-toboggan-md that's a good catch, thanks for the review! I made the following changes

- Create a new validator `validateDuratio()`
- Print warning instead of returning validation strings in `validateDeleteInactiveUserAfter()` & `validateDurationAgainstAuthUserSession()` 

I also updated the `labeled-form-element` mixin so that it emits validation errors in the same way as the composable. I think it's a good idea to keep these two in sync until we are able to remove the mixin usage in #11491

2024-07-31 17:38 UTC, mantis-toboggan-md approved these changes

2024-07-31 22:27 UTC, merged