Removing prop mutation in v-model usage
rancher/dashboard pull request #11625
Opened 2024-08-09 14:34 UTC by codyrancher

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-08-09 22:16 UTC, rak-phillip reviewed
My review is still in progress, but I left a few comments based on my observations. This change is looking really good overall, it's just a big one to review 🙂

2024-08-09 22:16 UTC, rak-phillip commented on shell/components/form/Taints.vue
> +      :value="value"
Funny to see that the `localValue` pattern was implemented 4 years ago..

https://github.com/rak-phillip/dashboard/commit/7a3c09dcc419b4709b41069e0e03df6e78cc9c30#diff-5b8f84a7e9a14b05f4460a3ac34988e86bde13325badca0b7eb4eaf6bb72e2d2R30-R37

I think that the computed prop becomes dead with this change, we might want to consider removing it.

2024-08-09 22:16 UTC, rak-phillip commented
> The vue3 compiler will now complain about this so we're taking steps to stop doing it here.

Just for posterity - we are still mutating the value prop via `set()` and assignment in most of these components, but the Vue3 compiler will mostly complain about `v-model=value` usage, which is the problem being addressed by this PR.

2024-08-12 17:01 UTC, rak-phillip requested changes
There's really only two areas that I think need to be addressed before merging:

1. pkg/aks/components/Taint.vue
2. shell/pages/c/_cluster/apps/charts/install.vue

Anything else that I mentioned in my review doesn't really have the ability to affect functionality.

In all, I think this looks great; a majority of the `value` props are defined in the `CreateEditView` mixin. I also tried to review each component for any unusual values that might be emitted in my review. Functionally, all is looking good at this point.

2024-08-12 20:37 UTC, codyrancher commented on shell/chart/monitoring/index.vue
Yeah, I decided to omit them for now. 

The nested props come up in the linter rule right now but can also be omitted (in a future version) and honestly I don't know if it's something we'll ever fully remove with how tightly coupled resource editing/saving is with the model architecture.

2024-08-12 20:38 UTC, codyrancher commented on pkg/aks/components/Taint.vue
It shouldn't regress because v-model really is just an alias for what got replaced but ultimately I only wanted to remove prop-mutation so I've gone ahead and removed it.

Good catch.

2024-08-12 20:39 UTC, codyrancher commented on shell/pages/c/_cluster/apps/charts/install.vue
> +            :value="value"
Reverted

2024-08-12 20:47 UTC, rak-phillip submitted a review, later dismissed
LGTM

2024-08-13 19:35 UTC, rak-phillip approved these changes

2024-08-13 19:38 UTC, merged