Add server-side pagination to cluster explorer lists
rancher/dashboard pull request #11672
Opened 2024-08-20 13:39 UTC by richard-cox

Blocked on 
- https://github.com/rancher/rancher/issues/48473
  - new index fields 
  - issue also fixes another blocking issue https://github.com/rancher/rancher/issues/48479 (HPA filtering fails)

No Longer Blocked on 
- https://github.com/rancher/dashboard/pull/11663
- https://github.com/rancher/rancher/issues/48384
  - Service cache fails to be created, blocking othe requests
  - Fixed by https://github.com/rancher/rancher/issues/48256 (fixed in rancher main)
- https://github.com/rancher/rancher/issues/48256 (fixed in rancher main)
- https://github.com/rancher/dashboard/issues/12856

Impacted by 
- https://github.com/rancher/rancher/issues/48092
  - Sorting side nav cluster list by state
- https://github.com/rancher/rancher/issues/48453
  - storage class filtering fails 
- https://github.com/rancher/dashboard/issues/12982
  - sorting service on type doesn't change type cells... but does change others

Outstanding (separate PR)
- https://github.com/rancher/dashboard/issues/11674
- https://github.com/rancher/dashboard/issues/12815

Working around https://github.com/rancher/rancher/issues/40773

### Summary
Fixes #9546
Fixes #12555

### Occurred changes and/or fixed issues
- Functional Changes
  - service list service type now shows Cluster IP (Headless) instead of just Headless (makes sort possible in SSP world, and is a better general value)
  - not quite functional but console warnings made when a request to filter/sort on an unsupported field are now only made in dev mode
  - not quite functional but the automated tests that construct an extension and run it against a shell made from the current branch now use `list/namespace.vue` instead of the now TS file `list/catalog.cattle.io.clusterrepo.vue`. The later has TS build errors
- New Pagination Tools
  - Pagination settings page now had a 'reset to default' option. This helps in short term whilst settings are in flux
- Regressions
  - NOTE - This contains items that were not tracked from previous PRs (mainly secret, configmap,  node)
  - workload health (sum of pod states) and pod restart count columns have been removed for all workload types
    - We should be able to bring these back when we get label selectors (and making a request per row to fetch specific pods given label selector)
  - job
    - duration is now not sortable (https://github.com/rancher/dashboard/issues/12815)
  - pod restarts has been removed for all workloads
    - this is the sum of restarts for pods
  - persistentvolume
    - pv source is now not sortable/filterable (uses local smarts)
  - configmap
    - keys is now not sortable/filterable (uses local smarts)
  - secret
    - secret data is now not sortable/filterable (uses local smarts)
  - networking.k8s.io.ingress
    - default backend is now not sortable/filterable (uses local smarts)
  - pod
    - images is now not sortable (sorting on an array)
  - node
    - role - is now not sortable/filterable (uses local smarts)
    - internal ip - is now not sortable/filterable (uses local smarts)
    - cpu - is now not sortable/filterable (uses local calculation)
    - ram - is now not sortable/filterable (uses local calculation)
  - catalog.cattle.io.app
    - chart is now only sorted/filtered on name (and not version as well) TODO split into two columns?
    - chart upgrade is not now sortable/filterable (uses smarts locally to determine if one is available)
  - catalog.cattle.io.clusterrepo
    - type - is now not sortable/filterable (uses local smarts git vs oci vs http)
    - url - is now not sortable/filterable (uses local smarts)
- Converted Lists
  - Cluster dashboard / events list
  - Cluster / Events
  - Cluster / Node (now uses PaginatedResourceTable)
  - Workloads
    - All (minus previously done pods)
  - Apps / Installed Apps
  - Apps / Repositories
  - Apps / Recent Operations
  - Service Discovery / HPA
  - Service Discovery / Ingresses
  - Service Discovery / Services
  - Storage / PersistentVolumes
  - Storage / StorageClasses
  - Storage / PersistentVolumeClaims
- Fixes
  - Fix issue where list components containing PaginatedResourceTables would incorrectly fetch all resources anyway
  - Fix async button icon alignment when in manual refresh mode
  - Ensure PaginatedTableResources pass through correct props
    - use-query-params-for-simple-filtering prop comes from resource list (so needs to pass through from generic resource list component --> actual resource list component --> paginated resource table component)
    - force-update-live-and-delayed prop comes from mixins (so only needs to pass through in scenarios where the component as a mixin with it in)
  - sortable table had a bug from vue3 migration ( showHeaderRow just needs to know slots exist, rather than creating components)

### Technical notes summary
- Resources will still not update (given backend blocked https://github.com/rancher/dashboard/issues/12734)

### Areas or cases that should be tested
- As per converted lists

### Areas which could experience regressions
- As per converted lists

### Screenshot/Video

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-10-25 08:40 UTC, nwmac commented
@richard-cox Is this for 2.10?

2025-01-03 20:41 UTC, codyrancher commented on cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts
> -    cy.get('@consoleWarn').should('not.be.called'); // See warning log (there will be some....)
Can this go back in? Are we avoiding warnings and errors or is it just not necessary anymore?

2025-01-03 20:49 UTC, codyrancher commented on shell/components/ResourceList/index.vue
> +      }
What is this resolving? This looks like a gotcha waiting to happen, I also don't like how we're adding more implicit logic which will cause more effort when we try to de-tangle and make things more composable.

2025-01-03 22:29 UTC, codyrancher requested changes
Overall simple changes. I think once the todos and the tests pass we'll be fine to merge.

2025-01-06 15:11 UTC, richard-cox commented on cypress/e2e/tests/pages/explorer/dashboard/cluster-dashboard.spec.ts
> -    cy.get('@consoleWarn').should('not.be.called'); // See warning log (there will be some....)
This was erroneously added in the previous PR https://github.com/rancher/dashboard/pull/11663/files#diff-2e0d69f6ba95f5b63f312a8b8d2001db4b2a63ad3499de89103564b933df32bd

2025-01-06 15:37 UTC, richard-cox commented on shell/config/settings.ts
> +            ],
This and the resource updates were the two mahoosive discussion points when they designed the solution.

Unfortunately anything that is sorted/filtered does so on a db indexed field and matching go code... so needs to be known up front. Think the code part was why just a sql alter table can't be used.

It was agreed they would (promptly) manually add them at dev time for us.

For extensions we agreed that extension owners that work with CRDs should ensure they contain [additional printer columns](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns). Those will be returned in the rancher schema as attributes.columns (which the dashboard will show as columns in lists) which reference the resources metadata.fields array. The metadata.fields array is indexed, so lists will automatically enable sort/filter on them. 

deployments atttributes.columns
```
{
"name": "Containers",
"type": "string",
"format": "",
"description": "Names of each container in the template.",
"priority": 1,
"field": "$.metadata.fields[5]"
},
```

deployment metadata.fields
```
[ 
...,
...,
...,
...,
...,
"fleet-controller,fleet-cleanup,fleet-agentmanagement",
...,
...,
],
```

Extension developers though that wish to sort/filter on resources where they don't own the CRD ... are blocked. We would need to come back with real use cases for that one

2025-01-06 15:47 UTC, richard-cox commented on shell/config/table-headers.js
> -export const ENDPOINTS = {
Not used (though other columns will use the Endpoints formatter)

2025-01-06 22:30 UTC, codyrancher approved these changes

2025-01-07 22:13 UTC, codyrancher approved these changes

2025-01-07 22:13 UTC, merged