…
rancher/dashboard pull request #11697
Opened 2024-08-23 17:23 UTC by aalves08

### Summary
Fixes #11694 

### Occurred changes and/or fixed issues

- add step for checking tag version matching on publish shell workflow
- remove unused `TMP_DIR` var in `publish-shell` script
- update creators package version to match what was published on NPM

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-08-26 13:12 UTC, aalves08 commented
FYI @richard-cox @nwmac

2024-08-26 15:38 UTC, aalves08 commented on shell/scripts/publish-shell.sh
> +fi
I think you've got a point here... 🤔 

I don't think it's called anywhere else and we can simplify it and adjust the `test-plugins-build` script. I've done that, let's see if it passes the gates

2024-08-26 16:10 UTC, jordojordo requested changes

2024-08-26 16:10 UTC, jordojordo commented on .github/workflows/scripts/check-package-tag-version.sh
> +  creators)
`shell` and `creators` should be quoted.

```bash
"shell")
...
"creators")
...
```

2024-08-26 16:10 UTC, jordojordo commented on shell/scripts/publish-shell.sh
> +  creators)
Same here with the quotes for shell and creators

2024-08-29 15:58 UTC, jordojordo approved these changes

2024-08-30 13:27 UTC, nwmac approved these changes

2024-08-30 13:28 UTC, nwmac commented
This needs to get in - some e2e tests are not passing, but after review, the failures there do not appear to be related to the changes here - getting this in as its needed to unblock other PRs.

2024-08-30 13:28 UTC, merged