Show Cloud Credential Expiration information for Harvester Creds, add actions to renew
rancher/dashboard pull request #12038
Opened 2024-09-26 14:56 UTC by richard-cox

### Summary
Fixes #11270

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-10-04 08:38 UTC, richard-cox commented on shell/config/labels-annotations.js
> +  'cattle.io/expiryTime'
now `cattle.io/expiration-date`

2024-10-09 09:47 UTC, torchiaf requested changes

2024-10-09 09:47 UTC, torchiaf commented on shell/config/labels-annotations.js
> +  'cattle.io/expiration-date'
This is `cattle.io/expiration-timestamp` in rancher 2-9-head

2024-10-09 11:23 UTC, torchiaf approved these changes
UI changes look good.
However, the Renew actions fail because the `cattle.io/expiration-timestamp` label in cloud credentials object is not updated by the backend.

2024-10-09 16:35 UTC, richard-cox commented
The `Renew` issue was investigated today and to progress it @MbolotSuse is taking a look. Given timing we'll merge this PR WITH the feature, and then hide / change messaging tomorrow if there's no solution

2024-10-09 16:35 UTC, merged