Fix 2.8 e2e tests
rancher/dashboard pull request #12053
Opened 2024-09-27 16:04 UTC by jordojordo

fix / update fleet git repo e2e test

Remove unused vars

Remove home page get within before method

Add wait to burger menu po

Restore home.spec.ts

Lint

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-09-30 07:54 UTC, richard-cox requested changes

2024-09-30 07:54 UTC, richard-cox commented on cypress/e2e/po/side-bars/burger-side-menu.po.ts
> +    return cy.getId('top-level-menu').should('be.visible').click({ force: true }).wait(500); // eslint-disable-line cypress/no-unnecessary-waiting
Not clear why there's a wait here....

2024-09-30 18:26 UTC, richard-cox commented
@jordojordo Description just needs tidying up then i think this is good to merge

2024-09-30 18:55 UTC, jordojordo commented
@richard-cox Thanks for looking into this, updated the description - good to review now.

2024-10-01 07:01 UTC, richard-cox approved these changes

2024-10-01 07:01 UTC, merged