Reduce flakiness in explorer/apps/repositories.spec.ts
rancher/dashboard pull request #12445
Opened 2024-10-31 14:37 UTC by mantis-toboggan-md

### Summary
Partially addresses https://github.com/rancher/dashboard/issues/12099

This PR corrects some retry logic in one of the e2e tests I'm seeing fail often.

You an see an example of this failure on our sorry cypress instance `.../instance/7a973f49-6fff-40d3-8054-9c5aa95a653b/test/r7
`

Each time this test runs it adds a repo name to `reposToDelete`. After each attempt, the afterEach hook tries to delete all repos in `reposToDelete`. If the test fails and retries, the afterEach hook will be retrying a repo deletion, get a 404 not found, and error out. 

The simplest fix here seems to be to ignore these errors in afterEach. We could also refactor the test so it only attempts to delete one repo each run.

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2024-10-31 20:11 UTC, yonasberhe23 submitted a review, later dismissed

2024-11-14 10:16 UTC, richard-cox requested changes

2024-11-14 10:16 UTC, richard-cox commented on cypress/e2e/tests/pages/explorer/apps/repositories.spec.ts
> +          reposToDelete.forEach((r) => cy.deleteRancherResource('v1', 'catalog.cattle.io.clusterrepos', r, false));
we could convert this to a for loop and remove the entry on successful deletion

2024-12-19 10:32 UTC, richard-cox approved these changes

2024-12-19 17:09 UTC, merged