Improve Fleet performance
rancher/dashboard pull request #12896
Opened 2024-12-17 11:25 UTC by aruiz14

### Summary
Issue #12895

Performance improvements while keeping the same behavior.

### Occurred changes and/or fixed issues
(Changes are logically split into different commits)

- Standardize on `clusterID` vs. "clusterLabel" (which normally refers to the *management* Cluster resource name, while the Fleet Cluster name is usually the same as the "display" name).
  - The `clusterId` is compound by `${namespace}/${name}` of the `Cluster` resource, making it easier to work with.
  - The `management` "Cluster" object (`clusterLabel`) is only really needed for calculating the `detailLocation` of deployed resouces, as they will link to the Explorer, which uses the management clusters' names.
- Refactor usages of `clusterResourceStatus`, which is always combined with a `find` by `clusterLabel` (now `clusterId`).
  - Used to obtain the resource statuses count per cluster.
  - Used to get the cluster state (based in the resource statuses aggregation).
  - This was being performed for every cluster individually, so it impacts performance exponentially to the number downstream clusters.
  - Reworking this allows to finally get rid of this function completely 🎉 .
- The Continuous Delivery dashboard iterates over all gitrepos/bundles/clusters in order obtain the badges and tooltip for every single entry in the table.
  - I've computed the necessary information in a single place and passed it to the relevant functions so they can easily pick what they need, hence greatly reducing the number of iterations (see screenshot below)
- Small optimizations (e.g. use a variable to avoid calling the same getters multiple times within the same function).
 

### Technical notes summary

Above changes were driven by capturing Performance traces with the Chrome Dev Tools, on a local Rancher installation where many sample workloads were installed.
See a summary of CPU usage over 30s of loading the CD dashboard:
 - Before:
![Screenshot 2024-12-10 at 12 42 50](https://github.com/user-attachments/assets/1a246d22-1b0a-4a0f-a042-cbf62cca9f72)
 - After:
![Screenshot 2024-12-10 at 12 42 59](https://github.com/user-attachments/assets/4f144fb3-9415-4b70-ba5a-cbc03603e299)

### Areas or cases that should be tested
 - Continuous Delivery:
   - Dashboard
   - Cluster list
   - Cluster details
   - GitRepo list
   - GitRepo details

### Areas which could experience regressions

These changes aim for improving performance while not introducing any changes to the information being displayed.
I've performed several tests using a local UI build and couldn't find any difference, but I may have missed something.

### Checklist
- [X] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [X] The PR has a Milestone 
- [X] The PR template has been filled out
- [X] The PR has been self reviewed 
- [X] The PR has a reviewer assigned
- [X] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [X] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2025-01-07 17:43 UTC, richard-cox commented
@aruiz14 i had to re-run all jobs given the build job output had expired, this has brought in an issue in check-i18n-links that should be fixed with a rebase

2025-01-16 17:15 UTC, torchiaf commented
@aruiz14 I found a difference in status color between main and your branch, I'm not sure if it is a wanted change or implicit bug fix:

![image](https://github.com/user-attachments/assets/348b70dd-4b89-4dd8-90da-e7cdefd4f759)

2025-01-16 18:15 UTC, torchiaf requested changes
Left some comments about Dashboard -> Status columns.

2025-01-16 18:15 UTC, torchiaf commented on shell/models/fleet.cattle.io.gitrepo.js
> +    const { nonReadyResources, ...bundlesSummary } = this.status?.summary || {};
Is it correct to use GitRepo `status` to calculate Bundles `statuses` ?
I have an active bundle associated to my `test` GitRepo in my test environment but the UI shows `0/0`, I think this could be one of the root causes.

GitRepo `test`

![image](https://github.com/user-attachments/assets/ca894264-87e0-4915-8b69-39647982d603)

Dashboard page - 'Ready Bundles' column is `0/0`:

![image](https://github.com/user-attachments/assets/b2b002b3-47ad-491d-8fa3-e8438b974786)

2025-01-17 11:33 UTC, aruiz14 commented on shell/models/fleet.cattle.io.gitrepo.js
> +    const { nonReadyResources, ...bundlesSummary } = this.status?.summary || {};
Yes, GitRepo's `[status.summary](https://github.com/rancher/fleet/blob/main/pkg/apis/fleet.cattle.io/v1alpha1/status.go#L5)` is indeed a `[BundleSummary](https://github.com/rancher/fleet/blob/main/pkg/apis/fleet.cattle.io/v1alpha1/bundle_types.go#L247)` type, which aggregates the status of all the Bundles that were deployed.

From the screenshots, I can see that you are using just a Local cluster with no downstreams configured, while creating a GitRepo within the `fleet-default` workspace, which excludes the local cluster. In that situation, it makes sense that the number of matching clusters and bundles is zero.

2025-01-21 12:31 UTC, aruiz14 commented on shell/pages/c/_cluster/fleet/index.vue
> +        badgeClass: STATES[state].color ? STATES[state].color : `${ STATES[STATES_ENUM.UNKNOWN].color } bg-unmapped-state`,
Good catch, thanks. Addressed in 1d7a0e230f0c2194728646a0778bb1368d04cebc

2025-01-21 12:35 UTC, aruiz14 commented on shell/models/fleet.cattle.io.gitrepo.js
> +    const { nonReadyResources, ...bundlesSummary } = this.status?.summary || {};
I was wrong, despite its name, `BundleSummary` contains `BundleDeployment` counts, so this won't work.
I reworked it to obtain the Bundles statuses from BundleDeployments directly (still avoiding to use `Bundles` directly just for this, since they are expensive to download/process).

2025-01-23 17:35 UTC, torchiaf approved these changes
LGTM, I added a commit suggestion just to fix a parameter type.

2025-01-23 17:35 UTC, torchiaf commented on shell/utils/fleet.ts
> +function conditionIsTrue(conditions: Condition[], type: string): boolean {
```suggestion
function conditionIsTrue(conditions: Condition[] | undefined, type: string): boolean {
```

2025-01-24 16:32 UTC, torchiaf approved these changes

2025-01-24 16:48 UTC, merged