proposal: Refactor build-extension-charts workflow in master to use scripts from upstream (dashboard)
rancher/dashboard pull request #12946
Opened 2024-12-24 15:22 UTC by aalves08

### Summary
Fixes #12824 

### Occurred changes and/or fixed issues

- Refactor `build-extension-charts` workflow in `master` to use scripts from upstream (dashboard) instead of shell package

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2025-02-21 13:29 UTC, nwmac commented
@aalves08 How urgent is this one? 2.11?

2025-02-24 09:47 UTC, aalves08 commented
Definitely not needed for 2.11.

I don't totally remember but I think we wanted to put this on hold... We can discuss it, but there's no hurry whatsoever.

2025-08-13 13:50 UTC, nwmac requested changes
Minor comments

2025-08-13 13:50 UTC, nwmac commented on .github/workflows/build-extension-charts.yml
> +          git clone -b master https://github.com/rancher/dashboard.git dashboard-repo
I'd suggest we pull this out to a separate step - both steps rely on the repo being cloned, but its cloned in this one and assumed in the next - I'd suggest adding a step above with a comment. I also think we should do a shallow clone/add the appropriate args so we clone as little as possible.

2025-08-13 13:50 UTC, nwmac commented on .github/workflows/build-extension-charts.yml
> +          BASE_DIR="$(
This could just go on one line

2025-08-13 13:50 UTC, nwmac commented on .github/workflows/build-extension-charts.yml
> +          BASE_DIR="$(
This could just go on one line

2026-05-22 13:43 UTC, aalves08 commented
Closing as not needed

2026-05-22 13:43 UTC, closed without merging