fix keyboard nav on login screen
rancher/dashboard pull request #12956
Opened 2024-12-27 15:43 UTC by aalves08

### Summary
Fixes #12775

### Occurred changes and/or fixed issues

- Fix keyboard navigation on `login` screen
- checkbox is now visibly focusable
- add `role="button"` to `AsyncButton`
- `Password` component is no tabbable
- refactor `LocaleSelector` component to work with keyboard navigation (`login` node only)

### Technical notes summary

### Areas or cases that should be tested

- Go to the login screen and browse the page with the tab key
- use `enter` or `space` key to trigger UI elements on the page

### Areas which could experience regressions

### Screenshot/Video

https://github.com/user-attachments/assets/86a838b0-ba86-404c-b330-c725b95a793e

### Checklist
- [ ] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [ ] The PR has a Milestone 
- [ ] The PR template has been filled out
- [ ] The PR has been self reviewed 
- [ ] The PR has a reviewer assigned
- [ ] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [ ] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2025-01-02 21:03 UTC, rak-phillip reviewed
Keyboard navigation is definitely improved, but I'm noting a lot of missing behavior that would satisfy keyboard interactions for the menubar pattern[^1]. Some notable elements that don't align with the APG:

- When a menu opens, or when a menubar receives focus, keyboard focus is placed on the first item
- Tab and Shift + Tab do not move focus among the items in the menu
- Arrow Navigation and Escape behavior are missing

We can discuss more on how we would like to approach these instances, but I suspect that we will replace one-off implementations like these with a standardized component once we address #12771. 

[^1]: https://www.w3.org/WAI/ARIA/apg/patterns/menubar/

2025-01-03 14:02 UTC, aalves08 commented on shell/components/LocaleSelector.vue
>              data-testid="locale-selector"
The outermost `div` inside the `mode="login"` `div` has the role `menu` and all it's menu items inside have the role `menuitem`.

2025-01-03 14:09 UTC, nwmac commented on pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
>          role="checkbox"
The animation is dreadful and should be removed

2025-01-03 14:33 UTC, nwmac commented on pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
> +    tabbingIndex: {
.. and we aren't setting this anyway in our use of `Checkbox` on the login page, which it feels like we should, so that it is explicit.

2025-01-03 15:43 UTC, aalves08 commented
@nwmac going to resolve all of the PR comments that you had around `tabbingIndex` and `tabindex`. They will all be cleaned on the next PR commit.

2025-01-03 15:44 UTC, aalves08 commented on pkg/rancher-components/src/components/Form/Checkbox/Checkbox.vue
> +        :tabindex="-1"
Fixed the the next commit

2025-01-03 20:53 UTC, rak-phillip commented on shell/components/LocaleSelector.vue
>              data-testid="locale-selector"
We had an OOB discussion and decided that a lot of these patterns should be fixed with #12771. It's not worth the effort to duplicate these efforts at this time.

2025-01-03 21:12 UTC, rak-phillip reviewed
This is looking good. We want to clean up the unused props and I think this will be good to merge.

2025-01-03 21:20 UTC, aalves08 commented
@rak-phillip removed the `tabbingIndex `. Good spot. Thanks

2025-01-03 22:08 UTC, rak-phillip commented on shell/components/LocaleSelector.vue
> +    },
One more unused instance of `tabbingIndex` that can be removed.

2025-01-06 09:55 UTC, aalves08 commented on shell/components/LocaleSelector.vue
> +    },
Don't know how I missed that. It's the last one lingering, I've made sure of that 😛 Fixed. Thanks

2025-01-06 10:11 UTC, aalves08 commented
@rak-phillip fixed and ready for final review 🤞

2025-01-06 14:52 UTC, nwmac requested changes

2025-01-06 14:52 UTC, nwmac commented on shell/components/AsyncButton.vue
> +    role="button"
This seems unrelated to this PR.

2025-01-06 14:52 UTC, nwmac commented on shell/components/form/Password.vue
> +            tabindex="0"
I think this should have `role=button` as this is a link being used as a button.

2025-01-06 14:52 UTC, nwmac commented on shell/components/LocaleSelector.vue
>          <v-dropdown
I guess the keyboard behaviour for the menu will be fixed when we wire in a standard menu component, as Phil notes. Tab should not move focus between menu items - the up/down arrow keys should do that - but we can tackle that =in the standard menu component. We will need to make sure we wire it in here.

2025-01-06 16:12 UTC, aalves08 commented on shell/components/LocaleSelector.vue
>          <v-dropdown
Me and @rak-phillip agreed that he would work on his new menu component and will replace all instances on the code afterwards.

The menu is now browsable with the `tab` key despite not being optimal. It's a definite improvement but not the final solution.

2025-01-06 16:18 UTC, nwmac approved these changes

2025-01-06 18:23 UTC, rak-phillip approved these changes

2025-01-06 19:03 UTC, merged