fix keyboard nav for about page
rancher/dashboard pull request #12959
Opened 2024-12-30 16:28 UTC by aalves08

### Summary
Fixes #12786 

### Occurred changes and/or fixed issues

- Fix keyboard nav for `about` page

### Technical notes summary

### Areas or cases that should be tested

- Go to the about page, click on the page and browse the UI elements with the tab key
- use enter or space key to trigger UI elements on the page

### Areas which could experience regressions

### Screenshot/Video

https://github.com/user-attachments/assets/41321ad6-2b98-4d83-922b-d27d0672b48f

### Checklist
- [x] The PR is linked to an issue and the linked issue has a Milestone, or no issue is needed
- [x] The PR has a Milestone 
- [x] The PR template has been filled out
- [x] The PR has been self reviewed 
- [x] The PR has a reviewer assigned
- [x] The PR has automated tests or clear instructions for manual tests and the linked issue has appropriate QA labels, or tests are not needed
- [x] The PR has reviewed with UX and tested in light and dark mode, or there are no UX changes

2025-01-02 14:00 UTC, nwmac requested changes

2025-01-02 18:07 UTC, aalves08 commented on shell/components/BackLink.vue
> +    <span><i class="icon icon-chevron-left" /> {{ t('generic.back') }}</span>
It's a smaller format for the outline. I am showing the outline on the `span`. The router-link has some padding that i figured not to mess with it because of possible alignment problems elsewhere.

Let me know if you want me to remove it and show the focus on the outermost element.

2025-01-02 18:11 UTC, aalves08 commented on shell/pages/about.vue
> +              role="link"
I don't know how to trigger a `space` key handler to navigate to an `href`. Probably is very simple but I haven't been able to find a solution for this one yet

2025-01-02 21:54 UTC, rak-phillip commented on shell/pages/about.vue
> +              role="link"
`space` (in addition to `enter`) is typically a pattern for activating buttons[^1] and links are activated using `enter`[^2]. In addition to this, native anchor elements also don't trigger on space. 

I suggest that we stick to a consistent pattern for links, ensure `enter` behaves as expected, and remove the expectation that `space` will activate a link. 

[^1]: https://www.w3.org/WAI/ARIA/apg/patterns/button/
[^2]: https://www.w3.org/WAI/ARIA/apg/patterns/link/

2025-01-02 21:59 UTC, rak-phillip commented on shell/components/BackLink.vue
> +    <span><i class="icon icon-chevron-left" /> {{ t('generic.back') }}</span>
Adding the span also appears to have altered the alignment of elements in Firefox

## Before

![image](https://github.com/user-attachments/assets/56c7cd91-c6b2-41d0-80b9-3f38e37653c6)

## After

![image](https://github.com/user-attachments/assets/dc0a52e3-22b6-45e8-8177-e26cbdfc465e)

2025-01-03 09:58 UTC, nwmac commented on shell/pages/about.vue
> +              role="link"
Agreed - I thought we'd used it elsewhere, but you're right, we should not use space on pure links.

We should capture this in some guidance notes for others

2025-01-03 10:06 UTC, aalves08 commented on shell/pages/about.vue
> +              role="link"
So, should I revert this change in all of the four open PRs that I have for accessibility or can we just leave those, but not adopt the `space` key from now on?

2025-01-03 10:08 UTC, aalves08 commented on shell/pages/about.vue
> +              role="link"
Added the information to `Accessibility: Developer Guidance & Automation` internal docs page

2025-01-03 10:50 UTC, aalves08 commented on shell/components/BackLink.vue
> +    <span><i class="icon icon-chevron-left" /> {{ t('generic.back') }}</span>
fixed

2025-01-03 10:52 UTC, aalves08 commented on shell/pages/about.vue
> +              role="link"
removed from all places

2025-01-03 10:52 UTC, aalves08 commented
@rak-phillip @nwmac PR updated based on last comments

2025-01-03 11:22 UTC, nwmac commented on shell/pages/about.vue
> +              role="link"
We should remove space key for pure links - where we are using a link as a button, however, we should support space.

2025-01-03 11:23 UTC, nwmac approved these changes

2025-01-03 11:25 UTC, nwmac requested changes

2025-01-03 11:25 UTC, nwmac commented on shell/pages/about.vue
> +        role="link"
I think this should support space as it is a button

2025-01-03 11:47 UTC, aalves08 commented on shell/pages/about.vue
> +        role="link"
changed the role to `button`, as it's a button on it's essence and added the `space` handler

2025-01-03 11:47 UTC, aalves08 commented
Final update @nwmac

2025-01-03 12:10 UTC, nwmac approved these changes

2025-01-03 12:27 UTC, merged