monitoring v2 tweaks
rancher/dashboard pull request #1697
Opened 2020-10-23 18:45 UTC by mantis-toboggan-md

#1689 - set Grafana `persistence.enabled` to `true` when pvc or statefulset storage is configured

#1667 - add Advanced nav group to monitoring
![Screen Shot 2020-10-22 at 4 36 03 PM](https://user-images.githubusercontent.com/42977925/97041209-06adee00-1524-11eb-9662-e614995d9184.png)

#1668 - add tooltips to `aggregateToDefaultRoles` and `createDefaultRoles` checkboxes
![Screen Shot 2020-10-23 at 11 33 22 AM](https://user-images.githubusercontent.com/42977925/97041279-2a713400-1524-11eb-810b-98a110a8bc34.png)
Along with adding tooltips, I tweaked some of the `text-label` class usage to be more consistent with other inputs:
<img width="1643" alt="Screen Shot 2020-10-23 at 11 44 24 AM" src="https://user-images.githubusercontent.com/42977925/97041934-2691e180-1525-11eb-8c7a-2c91dd874f9b.png">
<img width="1463" alt="Screen Shot 2020-10-23 at 11 44 33 AM" src="https://user-images.githubusercontent.com/42977925/97041945-28f43b80-1525-11eb-9df9-cee49699d6b7.png">

#1660 - enable `k3sServer` when `k3sControllerManager`, `k3sScheduler`, `k3sProxy` are enabled
The basic configuration aspect of this ticket is completed; the dashboard will enable k3sServer when it enables `k3sControllerManager`, `k3sScheduler`, and `k3sProxy` 
The advanced configuration portion of this ticket is dependent on #909

2020-10-23 19:00 UTC, westlywright approved these changes

2020-10-23 21:26 UTC, lvuch reviewed
Review submitted via commit

2020-10-26 22:39 UTC, vincent99 commented on assets/styles/base/_typography.scss
> +}
You really want this on every LI everywhere by default?  i.e. the left nav spacing seems to be getting out of hand..

![image](https://user-images.githubusercontent.com/753917/97228580-5e529080-1794-11eb-8540-f0902aeced5f.png)

2020-10-26 22:39 UTC, vincent99 commented on assets/styles/base/_typography.scss
>    line-height: 1.75em;
I don't know why `<p>` had a huge font to begin with, but shouldn't the line-height be removed too?

2020-10-26 22:39 UTC, vincent99 commented on assets/translations/en-us.yaml
> +    tip: Adds labels to the ClusterRoles deployed by the Monitoring chart to <a target="_blank" rel="noopener nofollow" href="https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-
`noreferrer`.  Always all 3 for external links.

2020-10-28 09:50 UTC, vincent99 requested changes
@lvuch see spacing comments, @mantis-toboggan-md just the rel=...noreferrer

2020-10-28 22:36 UTC, merged