Service Create Selectors - Show Target Pods Real Time
rancher/dashboard pull request #2194
Opened 2021-01-11 22:53 UTC by westlywright

Adds a banner message similar to Fleet Cluster Groups that shows the live pod count for the selectors section of service create.
Adds required to External Name input.

rancher/dashboard#717
rancher/dashboard#2179

![Screen Shot 2021-01-11 at 3 36 58 PM](https://user-images.githubusercontent.com/858614/104247330-d3914180-5424-11eb-8cdc-0ff0b11143fc.png)
![Screen Shot 2021-01-11 at 3 36 46 PM](https://user-images.githubusercontent.com/858614/104247338-d5f39b80-5424-11eb-93f6-989706ea0309.png)

2021-01-15 19:25 UTC, vincent99 requested changes

2021-01-15 19:25 UTC, vincent99 commented on edit/service.vue
> +    udpateMatchingPods: throttle(function() {
Typo in method name

2021-01-15 19:25 UTC, vincent99 commented on edit/service.vue
> +    },
I don't see why this needs to be periodically polled?  The find doesn't have force so it's getting back the same array every time, and allPods.length should be "live".

2021-01-19 17:28 UTC, westlywright commented
@vincent99 updated per your comments, thanks!

2021-01-20 18:28 UTC, merged