Add GitHub Actions to support using GitHub linked issues with Zube
rancher/dashboard pull request #2556
Opened 2021-03-17 08:49 UTC by nwmac

This PR adds a GitHub action that triggers when PRs are opened, re-opened, edited or closed.

This allows us to use GitHub linked issues with out workflow, where merging a PR should move the issues it fixes to the Test, rather than closing them.

Details for GitHub linked issues are here: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

For the open case, for all linked issues, it will:
- Set the assignee to the person creating the PR (if no assignees were added)
- Add the Zube 'In Review' label and remove any other Zube labels

For the edited/re-opened case, for all linked issues, it will:
- Add the Zube 'In Review' label and remove any other Zube labels

For the closed case, for all linked issues where there are no other open PRs that reference them, it will:
- Re-open the linked issue
- Add the 'To Test' label to the linked issue and remove any other Zube labels

Note: There should be no issues with the Zube Integration Bot, since it is triggered via a WebHook and thus should have run well before the GitHub action gets a chance to. Even so, this action will wait for the label added by the bot to ensure the Zube Bot has run first.

2021-03-30 08:01 UTC, nwmac commented
@richard-cox Vince has enabled GitHub actions, so this should now work when merged.

2021-03-30 10:30 UTC, richard-cox requested changes
I haven't run it, but walked through code and looks good. There were a couple of minor tweaks required though (one subjective, one functional).
Once merged we should tentatively test it once non-linked issues seem unaffected (a good fallback position)

2021-03-30 10:30 UTC, richard-cox commented on .github/workflows/scripts/pr.js
> +    const found = issue.labels.find(l =>l.name.toLowerCase() === label.toLowerCase());
Minor, could just return directly

2021-03-30 10:30 UTC, richard-cox commented on .github/workflows/scripts/pr.js
> +    request.put(labelsAPI, {labels: cleanLabels});
This should have `await`. Alternatively I _think_ you could remove `async` and `return request.put...`

2021-04-06 13:23 UTC, richard-cox approved these changes

2021-04-06 13:32 UTC, merged