Add home page doc support for readme and getting started
rancher/dashboard pull request #2801
Opened 2021-04-22 13:00 UTC by nwmac

The home page has a couple of small docs that need to be included - this PR adds support for those using nuxt content.

The PR ensures that i18n is supported for these docs, with a fallback to en-us.

2021-04-27 10:01 UTC, richard-cox requested changes

2021-04-28 07:20 UTC, nwmac commented on content/docs/en-us/getting-started.md
> +Welcome to Rancher Dashboard.
I'm going to ask someone to help us build that out

2021-04-28 07:21 UTC, nwmac commented on pages/home/index.vue
> +      // Update the value, so that the message goes away
I'll make version number a link - I am going to tweak the behaviour slightly in another PR

2021-04-28 07:37 UTC, nwmac commented on pages/home/index.vue
> +            <nuxt-link :to="{name: 'docs-doc', params: {doc: 'getting-started'}}" class="pull-right">
Fixed

2021-04-28 07:46 UTC, nwmac commented
@richard-cox Updated following your review

2021-04-28 10:06 UTC, richard-cox approved these changes
Given `getting-started.md` gets updated before release, LGTM

2021-04-28 14:38 UTC, merged