WIP: Ember page embedding
rancher/dashboard pull request #3031
Opened 2021-05-19 14:08 UTC by nwmac

This PR embed more Ember pages into the dashboard user - the goal being that net-new users do not need to switch back to the old Cluster Manager UI.

2021-05-26 09:42 UTC, nwmac commented on assets/translations/en-us.yaml
> +v1ProjectTools:
Remove

2021-05-26 09:46 UTC, nwmac commented on components/EmberPage.vue
> +      return 'content';
Remove loader mode

2021-05-26 09:54 UTC, nwmac commented on components/EmberPage.vue
> +      }, 1500);
make 1s

2021-05-26 09:56 UTC, nwmac commented on components/EmberPage.vue
> +          this.heightSync = h;
heightSync is the timer not the cached height

2021-05-26 10:07 UTC, nwmac commented on components/EmberPage.vue
> +  <div ref="emberPage" class="ember-page" :class="fixed">
Combine ember-page and fixed classes

2021-05-26 10:08 UTC, nwmac commented on components/EmberPage.vue
> +    <Loading v-if="!inline" :loading="!loaded" :mode="loaderMode" :no-delay="true" />
loaderMode is fixed as content

2021-05-26 10:11 UTC, nwmac commented on components/EmberPageView.vue
>      <h1>Page Not Found</h1>
Localize

2021-05-26 10:14 UTC, nwmac commented on components/nav/TopLevelMenu.vue
> +          <template v-if="legacyApps.length">
This should be on the if have the legacy feature flag enabled

2021-05-26 10:16 UTC, nwmac commented on config/product/legacy.js
> +    label:          'Alerts',
localize

2021-05-26 10:21 UTC, nwmac commented on detail/node.vue
> +    const v3Nodes = await this.$store.dispatch('rancher/request', {
Could be gated on if v1 monitoring installed

2021-05-26 10:24 UTC, nwmac commented on detail/pod.vue
> +    slectionChanged(c) {
typo

2021-05-26 10:29 UTC, nwmac commented on list/management.cattle.io.feature.vue
> +        this.update.save();
Add comment - await can go back in when backend returns after restart

2021-05-26 10:34 UTC, nwmac commented on mixins/v1-workload-metrics.js
> +      let prefix = 'workloads/';
Remove

2021-05-26 10:39 UTC, nwmac commented on pages/c/_cluster/explorer/index.vue
> +    hasV1Monitoring() {
Use helper

2021-05-26 10:56 UTC, nwmac commented on pages/c/_cluster/explorer/tools/index.vue
> +          upgradeAvailable: app?.upgradeAvailable,
Change to legacy flag

2021-05-26 11:01 UTC, nwmac commented on pages/c/_cluster/explorer/tools/index.vue
> +            <template v-else-if=" opt.chart.versions.length">
remove space

2021-05-26 11:04 UTC, nwmac commented on pages/c/_cluster/legacy/project/index.vue
> +  <IconMessage icon="icon-monitoring" message="Use the Project/Namespace filter at the top of the page to select a Project in order to see legacy Project features." />
Localize

2021-05-26 11:12 UTC, nwmac commented on utils/monitoring.js
> +// Can be used inside a compoennts' computed property
Typo

2021-05-26 15:43 UTC, richard-cox requested changes
- Dark mode - Dark navy background of dashboard jars with faded black background of cluster manager. As discussed I'll create a separate issue for this
- In Deployment (rancher-webhook) - Detail View - Metrics tab - the embedded window contains the warning `This is the system project which has all Kubernetes and Rancher system namespaces. Changes made to resources in the system project may harm the cluster.`. This shouldn't be there for embedded mode and we should probably show something similar in Edit View.
  - Also applies to Pod/Container metrics
  - Interestingly in edit mode we show another warning which doesn't overlap `This Deployment is managed by a Helm app; changes made here will likely be overwritten the next time the app is changed.`
- After playing around
  - i think the 1 second height ping does feel too long in places, 0.5s would be better  
  - the `Waiting for Restart` modal does need a spinner / windows progress bar 
- On a system which had v1 and v2 monitoring installed at some point (probably v1 in the same session) I disabled the `legacy` feature
  - The side nav 'LEGACY APPS / Cluster Manager' link was still shown
  - After going to the local cluster dashboard I got a white page error with the following exception 
    ```
    client.js?06a0:97 TypeError: Cannot read property 'summary' of undefined
        at _resourceCounts (ResourceSummary.vue?ef88:22) ... (`const summary = clusterCounts[resource].summary;`)
        at eval (index.vue?d30a:203)
        at Array.forEach (<anonymous>)
        at VueComponent.totalCountGaugeInput (index.vue?d30a:202)
        at Watcher.get (vue.runtime.esm.js?2b0e:4479)
        at Watcher.evaluate (vue.runtime.esm.js?2b0e:4584)
        at VueComponent.computedGetter [as totalCountGaugeInput] (vue.runtime.esm.js?2b0e:4836)
    ```
  - On refresh these two were resolved / didn't happen

2021-05-27 08:33 UTC, nwmac commented
@richard-cox All done, apart from the dark mode change - removing the system project warning requires a change to Ember - PR for this is here: https://github.com/rancher/ui/pull/4639

2021-05-27 14:55 UTC, richard-cox approved these changes

2021-05-27 15:31 UTC, merged