Update icon for local cluster to blue cow
rancher/dashboard pull request #3039
Opened 2021-05-19 22:32 UTC by neillsom

#2942 
Existing logo was generic k3s image. This pr detects if the current cluster is `local` and updates the logo accordingly. 
Takes advantage of new `BrandImage` component and suse green theming.

2021-05-20 00:52 UTC, vincent99 commented on models/management.cattle.io.cluster.js
> +
You want `this.spec?.internal === true` here.  I don't remember exactly the situation but that's what internal means and it's possible for the id to not be `local`.  (You can then update other references to `internal` that look at `this.isLocal` instead to make them more readable)

2021-05-21 07:40 UTC, nwmac requested changes
See comment from Vince

2021-05-21 12:48 UTC, nwmac commented
@neillsom I wanted to get this in, so I went ahead and made some changed - I made Vince's fix but also changed to use an inline svg, so we can change the color.

It looked a little odd in the slide-in menu having the primary hover color with the logo, so with this approach we can override the color on hover to be the correct color for the light/dark theme.

The logo was two-tone before - now's it just primary, but I think that is more consistent with the other icons in the slide-in menu.

Take a look at the change I made and see what you think.

2021-05-24 16:23 UTC, richard-cox approved these changes

2021-05-24 16:24 UTC, merged