Form field changes in Cluster Private Registry CSS changes
rancher/dashboard pull request #3369
Opened 2021-07-01 09:36 UTC by neillsom

**Form fields in Cluster Private Registry & Agent Environment Vars tabs tweaks**
#3184 
Added css styling to make forms consistent height

2021-07-06 14:50 UTC, richard-cox requested changes
Two v minor tweaks required, others LGTM

2021-07-06 14:50 UTC, richard-cox commented on components/form/SecretSelector.vue
> +    min-height: 61px;
There's a scss variable for form field height (`$input-height`) that should be used here

2021-07-06 14:50 UTC, richard-cox commented on components/form/SelectOrCreateAuthSecret.vue
> +  min-height: 61px;
Should also be  `$input-height`

2021-07-09 16:21 UTC, merged

2021-07-09 16:23 UTC, vincent99 commented
@neillsom Please use `git rebase` to update instead of putting merge commits in PRs.