Bugfix/3421 error page url
rancher/dashboard pull request #3926
Opened 2021-08-18 23:37 UTC by rak-phillip

This adds a button to the fail whale page to allow the user to "refresh" the page on error by attempting to navigate back one step in the router history. 

I attempted another approach to display the fail whale page without modifying the url by introducing a named catch-all route, similar to instructions detailed in [NUXT](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes) and [Vue Router](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#extendroutes), but I think the functionality that I was looking for is only available in Vue Router 4.x. I'm open to other potential solutions to resolve this issue.

This change also has the added risk of changing the way we route to fail whale by changing our method from `replace` to `push`. Since we've now added fail whale to our route history, users might be able to inadvertently navigate back to a fail whale page, adding to further confusion...

#3421

2021-08-18 23:38 UTC, rak-phillip commented
### New Fail Whale 
![image](https://user-images.githubusercontent.com/835961/129985593-b83dbef5-b6f4-4243-b95c-02ec88449355.png)

2021-08-19 09:18 UTC, nwmac requested changes
One thing needs localizing, other than that, looks good to go in.

2021-08-19 09:18 UTC, nwmac commented on pages/fail-whale.vue
> +    content: 'or';
'or' should be localized - you'll need to switch that from being rendered in the :after to do that

2021-08-20 15:02 UTC, nwmac approved these changes
LGTM

2021-08-20 15:08 UTC, merged