Adding and renaming cluster repos to the cluster management section of the app
rancher/dashboard pull request #4158
Opened 2021-09-14 18:23 UTC by codyrancher

This allows restricted admins to manage the repos even if they don't have access to the local cluster.

https://github.com/rancher/dashboard/issues/3995]

![Screenshot from 2021-09-14 11-21-03](https://user-images.githubusercontent.com/55104481/133312449-0805eff5-a0a0-44e8-b2ca-acca0d20ea99.png)
![Screenshot from 2021-09-14 11-21-22](https://user-images.githubusercontent.com/55104481/133312453-61fa4b02-fff6-4c4b-a48a-ac2719d5eb96.png)
![Screenshot from 2021-09-14 11-21-28](https://user-images.githubusercontent.com/55104481/133312454-d836166f-1a51-4e27-9cca-47630af12f26.png)

I verified:

1. A restricted admin has access to cluster repos under cluster management
2. That the breadcrumbs at the top of the page as well as the cancel buttons still work for both local and cluster management variants.

2021-09-16 10:24 UTC, nwmac requested changes

2021-09-16 10:24 UTC, nwmac commented on assets/translations/en-us.yaml
> +  catalog.cattle.io.clusterrepo: 'A cluster repository is a Helm repository, {vendor} git based application catalog or a rke template repository. It provides the list of available charts and template
Can we have two messages - only repositories in the local cluster can contain cluster templates.

For the local cluster, user the new message, for non-local clusters, use the old message.

2021-09-17 14:40 UTC, richard-cox requested changes

2021-09-17 14:40 UTC, richard-cox commented on assets/translations/en-us.yaml
> +  catalog.cattle.io.clusterrepo.local: 'A repository is a Helm repository, {vendor} git based application catalog or a rke template repository. It provides a list of available charts and templates.'
should rke be capitalised?

2021-09-17 14:40 UTC, richard-cox commented on assets/translations/en-us.yaml
> +  catalog.cattle.io.clusterrepo.local: 'A repository is a Helm repository, {vendor} git based application catalog or a rke template repository. It provides a list of available charts and templates.'
Strictly speaking the rke template repository is one of the two previous ones, which is offered to the user in a radio button in the create flow.
Maybe something like...

`A repository is either a Helm or {vendor} git based catalog. It provides a list of available Helm charts and templates, and RKE templates.`

for non-local...
`A repository is either a Helm or {vendor} git based catalog. It provides a list of available charts and templates.`

2021-09-17 14:40 UTC, richard-cox commented on list/catalog.cattle.io.clusterrepo.vue
> +      return this.currentCluster.isLocal ? 'typeDescription."catalog.cattle.io.clusterrepo.local"' : 'typeDescription."catalog.cattle.io.clusterrepo"';
When signing in as a standard user and going to the management repo list i get a `Cannot read property 'isLocal' of undefined` error. In this context, it's safe to assume if there's no currentCluster then we're seeing catalog resources from that local cluster

2021-09-17 15:00 UTC, nwmac commented
@codyrancher I've made some tweaks to this. Just going to tweak the banner label.

2021-09-17 16:43 UTC, richard-cox approved these changes

2021-09-17 16:50 UTC, merged