4270 kubeconfig clipboard
rancher/dashboard pull request #4322
Opened 2021-09-30 17:50 UTC by jordojordo

This PR is in reference to #4270 to bring back the ability to copy the kubeconfig for clusters.

Converted the button in the navigation header for downloading the kubeconfig yaml of the current cluster into a dropdown which consists of two options: `Download KubeConfig` and `Copy KubeConfig to Clipboard`

https://user-images.githubusercontent.com/40806497/135504487-4a71ee75-b92d-4bcf-8c4c-734c870ca754.mp4

@vincent99 Is there a way to format the the config for projects/namespaces into yaml, similar to how the cluster has an action `generateKubeconfig`?

2021-11-04 12:13 UTC, nwmac requested changes
A few comments - also, this adds a copy config for the namespace resource - not sure why this was added? Doesn't seem to relate to the issue which is to copy the kubeconfig - did I miss something?

2021-11-04 12:13 UTC, nwmac commented on assets/translations/en-us.yaml
> +  copy: Copy Config to Clipboard
Can we name this copyConfig rather than just copy

2021-11-04 12:13 UTC, nwmac commented on assets/translations/en-us.yaml
> +  kubeconfigDownload: Download KubeConfig
Since we have may related here, I'd suggest a kubeconfig key with child keys download, copy and options

2021-11-04 12:13 UTC, nwmac commented on components/nav/Header.vue
> +          v-tooltip="t('nav.kubeconfigOptions')"
The dropdown arrow in the header bar is not obvious as to what it does or the fact its a drop down - I'd suggest we remove the drop down and just put two buttons in the header bar - there's plenty of room and they both have icons.

2021-11-04 19:52 UTC, jordojordo commented
Cleaned up the nav header by splitting the dropdown into two separate buttons. Also, removed the copy config action from namespace resources as it didn't relate to the issue.

2021-11-22 12:27 UTC, nwmac commented on components/nav/Header.vue
> +        </button>
The v-tooltip key need updating - it should be `nav.kubeConfig.download1`

2021-11-22 12:32 UTC, nwmac commented on components/nav/Header.vue
> +        </button>
@jordojordo I've updated the PR with this fix.

2021-11-22 12:33 UTC, nwmac approved these changes

2021-11-22 13:26 UTC, merged