Add action for pool force-machine-remove
rancher/dashboard pull request #4592
Opened 2021-11-18 20:15 UTC by jordojordo

Reference #4538 

This adds support for force removing a RKE2 pool in a cluster that is stuck in deleting state.

**Note: **
_Currently a WIP as the backend will not allow the deletion of a pool. At the moment the resource is stuck on a loop where it will update the Yaml a countless number of times, which in turn will not allow the annotation `provisioning.cattle.io/force-machine-remove` to be added to the config. (see video)_

https://user-images.githubusercontent.com/40806497/142489889-aae1fd59-94e9-4c41-9136-14360eeaba2f.mp4

**To Test**

2021-11-22 17:50 UTC, richard-cox requested changes
Two very minor comments, otherwise LGTM

2021-11-22 17:50 UTC, richard-cox commented on models/cluster.x-k8s.io.machine.js
> +      label:      'Force Delete',
Needs i10n

2021-11-22 17:50 UTC, richard-cox commented on models/cluster.x-k8s.io.machine.js
> +    machine.setAnnotation('provisioning.cattle.io/force-machine-remove', 'true');
There's a file that contains a list of annotations, this should probably be listed there (`./config/labels-annotations.js` `CAPI` obj)

2021-11-22 19:23 UTC, jordojordo commented
@richard-cox I updated this with the suggestions you made, moved the label to translations and added an annotation for `FORCE_MACHINE_REMOVE`

2021-11-23 09:41 UTC, richard-cox approved these changes

2021-11-23 12:53 UTC, merged