[WIP] "Restore snapshot" action is not available in Cluster management page
rancher/dashboard pull request #4677
Opened 2021-12-01 22:29 UTC by neillsom

2021-12-03 01:15 UTC, catherineluse commented
While talking about this issue, Neill and I found out that the cluster model's preexisting method to get the snapshots of a cluster (`etcdSnapshots`) seems to always return an empty array. It might be a separate backend issue to make `etcdSnapshots` included in the cluster's `status` property, as the `etcdSnapshots` getter is expecting it to be. https://github.com/rancher/dashboard/blob/master/models/provisioning.cattle.io.cluster.js#L470

2021-12-20 21:16 UTC, jordojordo requested changes
One minor comment - Otherwise LGTM
Tested with multiple snapshots with no issues noticed.

2021-12-20 21:16 UTC, jordojordo commented on models/provisioning.cattle.io.cluster.js
> +
Since we're in here, could we change the labels for the actions to be localized?

2022-01-04 15:44 UTC, jordojordo approved these changes

2022-01-04 15:45 UTC, merged