added 2.6.3 content to top
rancher/dashboard pull request #4755
Opened 2021-12-10 22:32 UTC by gaktive

https://github.com/rancher/dashboard/issues/4678 has the details. I'm open to different formatting.

As for 2.6.1 and 2.6.2 content, I don't think we officially got any wording. We can look at adding that later once we get or decide on content.

Signed-off-by: Gary A Korhonen <gkorhonen@suse.com>

2021-12-10 22:34 UTC, gaktive commented
I will note that the release note link doesn't work since the 2.6.3 tag isn't live (yet).

2021-12-14 11:22 UTC, nwmac requested changes

2021-12-14 11:22 UTC, nwmac commented on content/docs/en-us/whats-new.md
> +## New in 2.6.3
The heading levels are the same for the version as well as the children - we should use a different heading style.

2021-12-15 13:25 UTC, nwmac approved these changes
LGTM

2021-12-15 16:57 UTC, merged