Show the same id twice
rancher/dashboard pull request #4783
Opened 2021-12-16 17:18 UTC by WuJun2016

# links
- https://github.com/harvester/harvester/issues/1111

2021-12-16 17:38 UTC, WuJun2016 commented
Hi, @richard-cox   can you help review this pr?  I don't know if this is the right change or if it will introduce other problems。  thanks

2021-12-16 18:08 UTC, vincent99 commented
I haven't run this but that doesn't look at all like a safe change to make.  The point of it is that if you're on a create screen and have a reference to the model, after save()ing that same instance needs to be the one that is put into the store so that it continues to be 'live' instead of becoming orphaned outdated data.  By ignoring the existing object that was passed in you're going to break that.

Are you trying to `load()` an `existing` model that has an `id` already somewhere?  That's the only way I see a duplicate entry getting in here, because the entry is unconditionally added.  But you're not supposed to cause that situation in the first place, if it has an ID then it should have been in and come from the store already and doesn't need loading.

2021-12-16 19:07 UTC, richard-cox commented
It looks like with dev tool throttling on it's artificially recreating something similar... though i think it isn't what's causing the bug. With throttling on the socket updates the resource before the response to the resource save is 'unthrottled' by the browser and processed in `mutations.js`.  The original bug states the double resource is still shown on resource, whilst in this scenario it's a local caching issue and is resolved by a refresh

2021-12-16 21:43 UTC, vincent99 commented
Alright I can see that happening in theory that a websocket message for a change gets received and handled before the save response.. But a fix needs to preserve the behavior that `model.save()` operates on that model and the result is that same model object gets into the store and receives future updates.

What the PR currently does is update the copy in the store but orphan the original model.  You'd have to instead "fix up" the store by removing the unexpected entry and adding the expected one.

But yes this doesn't seem relevant to the original issue since it wouldn't persist across reloads.  Two resources of the same type+namespace+name is "impossible" in k8s; that's the one meager constraint that they guarantee as a database is that's the only unique key..  So if that's what's really being seen after a reload, I'd suspect a bug in Steve and look at its list response vs `kubectl get` and/or the websocket events coming in.

2022-01-04 16:13 UTC, richard-cox requested changes
As per comments, we don't think this is the correct solution

2022-01-06 08:22 UTC, WuJun2016 commented
> Alright I can see that happening in theory that a websocket message for a change gets received and handled before the save response.. This should be pretty unlikely because the save happens upon response but change events get queued and processed in batches.

If I set the network speed very slow, , a websocket message for a change gets received and handled before the save response.

![image](https://user-images.githubusercontent.com/24985926/148349393-9501b608-6fea-46b9-a86f-075be1588ea8.png)

2022-01-06 08:43 UTC, richard-cox commented
@WuJun2016 I don't think dev tool throttling affects web sockets, so it's a bit of an artificial test case

2022-01-07 05:38 UTC, WuJun2016 commented
I started a rancher via docker （`sudo docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 --privileged rancher/rancher:v2.6.0`）,   It is easy to reproduce this problem, too.   

![image](https://user-images.githubusercontent.com/24985926/148495747-85b7aeb2-adf2-4fad-90b4-4dd5a8e2be3c.png)


Dev tool throttling does not affect the websocket, when the network is slow, the websocket gets the resources earlier than in model.save()

2022-01-07 05:40 UTC, WuJun2016 commented
I started a rancher via docker （`sudo docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 --privileged rancher/rancher:v2.6.0`）,   It is easy to reproduce this problem, too.   

![image](https://user-images.githubusercontent.com/24985926/148497433-dc4ee334-8a5d-4fa9-a7d5-9a5781ae3d6f.png)

Dev tool throttling does not affect the websocket, when the network is slow, the websocket gets the resources earlier than in model.save()

2022-03-01 18:21 UTC, gaktive commented
@MbolotSuse if you're looking at https://github.com/rancher/rancher/issues/36071 and https://github.com/rancher/rancher/issues/36072, we found this old PR tied to one investigation angle with a way to repro.

2022-03-08 15:51 UTC, richard-cox commented
Bumping out to 2.6.5

2022-07-29 09:46 UTC, nwmac commented
We're not keen on this fix - can you re-open with more detail if this is still an issue that you think needs addressing.

2022-07-29 09:46 UTC, closed without merging

2023-05-16 10:21 UTC, w13915984028 commented
met it, in a VPN network from local to rancher fremont DC;  

a force-refresh of web page solved the issue.

<img width="934" alt="image" src="https://github.com/rancher/dashboard/assets/31133476/46f1325b-1b43-4c4a-978e-bea68ed8aaa0">