Improve styling of Input and Select controls
rancher/dashboard pull request #4914
Opened 2022-01-13 14:24 UTC by nwmac

This PR updates the styling of the Input and Select controls and fixes a number of rendering issues with them (and a couple of related controls that use them).

- Remove the background colour from these controls when active - we uses a greyish background which is easily confused with the control presentation when disabled.
- Consistently use the border colour for :focus and :hover states - we use a mix of box shadow and outline (which both paint outside of the bounding box)
- Usea border colour change on control :hover
- Use a border colour change on control :focus and highlight the label (when labelled) with the outline color
- Introduce a compact mode - labelled controls will now correctly size themselves depending on whether a label is provided (this can be overridden using the compact property) - this should make it easier to ensure controls have the height when arranged in columnar layouts
- Improve the presentation of the LabelWithSelect control so that the select part no longer looks disabled and so that it has the same :hover and :focus behaviour as a normal Select control
- Fix minor positioning issues with tooltip icons and dropdown arrows
- Change the style of select boxes to have a border in the outline colour that outlines the complete control, including the select, i.e.
<img width="514" alt="Screenshot 2022-01-13 at 14 13 35" src="https://user-images.githubusercontent.com/1955897/149346008-9a45be42-e6a8-4613-93f3-0e5511856e9d.png">
Note: This requires various css to ensure the corner borders are shown correctly when the dropdown drops up/down and when used as part of a LabelWithSelect control 
- Improve the presentation of the select control when displaying tags:
<img width="506" alt="Screenshot 2022-01-13 at 14 14 27" src="https://user-images.githubusercontent.com/1955897/149346138-9679b9ff-6eae-4a71-ba79-58b0418fc797.png">
- Tweaks to the KeyValue, Taints and Tolerations controls to improve the presentation
- Added example pages to the Storybook
-

2022-01-14 15:14 UTC, richard-cox requested changes
We might want to slightly tone down (darken) the input field hover border in dark mode. Just to make it more subtle.

I spotted the following issues (not sure all are related to this PR)
- Deployment / Resources Tab --> `Add Toleration` button text isn't right
![image](https://user-images.githubusercontent.com/18697775/149533417-edfcac95-ff57-43d1-b9dc-9d86bcf0766e.png)
![image](https://user-images.githubusercontent.com/18697775/149533466-71b536ed-8332-4c92-b2e6-5548dd1e2c1d.png)
- Deployment / Scaling and Upgrade Policy --> Select unit height is incorrect
  ![image](https://user-images.githubusercontent.com/18697775/149533759-d13bda8f-b2f9-47b9-8df8-c2f0e4783e4f.png)
- User Avatar Menu --> On click of menu item the left/right margin/padding is removed 
  ![image](https://user-images.githubusercontent.com/18697775/149536753-63ede243-df49-41c9-8a2c-4a1bd9ee091a.png)
- Deployment / General Tab --> deployment's with long name aren't elipsed in the NameNSDescription component
  ![image](https://user-images.githubusercontent.com/18697775/149537609-83c06c86-b1f3-40dd-b831-980b14709bb2.png)

2022-01-14 15:14 UTC, richard-cox commented on utils/select.js
> +// This is a simpler positiionner for the dropdown for a select control
typo

2022-02-03 16:39 UTC, nwmac commented
@richard-cox Updated with fixes - button colour will be done in another PR. I couldn't see the issue with the user dropdown - looked the same to me as before.

2022-02-04 15:58 UTC, richard-cox requested changes
Not sure if I originally missed this, but the content of the namespace filter in the header wiggles on hover. Other hover border effects like the list filter work fine.

Otherwise LGTM

Update: The commits need to be squashed too, that last merge brought in a lot of history

2022-03-23 09:23 UTC, nwmac commented
@richard-cox I believe this is all updated and good to go - NamespaceFilter was fixed separately. I've rebased this PR with master.

2022-03-23 12:14 UTC, richard-cox approved these changes

2022-03-23 12:15 UTC, merged