Add support for displaying cluster badges next to cluster name
rancher/dashboard pull request #4933
Opened 2022-01-18 14:34 UTC by nwmac

This PR adds the ability to show.a badge next to the cluster name and, optionally, to reflect this in the icon shown for the cluster in the header as well as the slide-in navigation.

This allows users to tag their clusters with badges such as 'Production', 'Staging' etc and to give these an appropriate colour such that users are aware of the cluster that they are interacting with.

This feature is controlled by annotations on the cluster - this PR does not add any UI to manage these labels - this will be done in another PR.

3 annotations are supported on the cluster management resource:

1. `ui.cattle.io/badge-text` - Badge text - badge is only shown if badge text is not empty
1. `ui.cattle.io/badge-color` - Badge color - as a hex color - e.g. #ff00ff
1. `ui.cattle.io/badge-use-as-icon` - Use as icon - if set to "true" the cluster icon will also reflect the badge

Examples of how this looks:

Badge only:

![Screenshot 2022-01-18 at 14 34 31](https://user-images.githubusercontent.com/1955897/149957520-50a6b2bd-ead3-4d77-943c-75eca4627d93.png)

Badge and icon:

![Screenshot 2022-01-18 at 14 30 20](https://user-images.githubusercontent.com/1955897/149956775-19c7dac2-b3df-458b-a6d4-0cddd297c186.png)

![Screenshot 2022-01-18 at 14 30 46](https://user-images.githubusercontent.com/1955897/149956760-91166ebc-4f5a-454c-9e76-e6841920b995.png)

2022-01-19 17:32 UTC, richard-cox requested changes
- For long titles the text will shunt the header right context out of view. This also extends the width of the main body. Would it be possible to ellipse the overflow? The same applies to the new cluster text (it can push right content out of sight)
  - ![image](https://user-images.githubusercontent.com/18697775/150177809-6918350f-a267-4537-bde9-4d9da23f1703.png)
- Subjective - It feels like the filter should be to the right of the icons but left of the action menu. A the moment it looks like it's dangling after the icons.
  - ![image](https://user-images.githubusercontent.com/18697775/150178110-862ae863-ffef-4aea-bf3a-70c9f4e0b5ef.png)
- Icons for clusters that aren't connected don't appear
  - (left is PR, right is a slightly old 2.6-head... let me know if you'd like access to the system)
  - ![image](https://user-images.githubusercontent.com/18697775/150179967-b331f1ef-efaf-4ff3-a8c6-c9a904bf6c3b.png)

2022-01-19 17:32 UTC, richard-cox commented on models/management.cattle.io.cluster.js
> +      textColor:  textColor(parseColor(color)),
This throws an exception if it fails, could catch this and track log it WRT to metadata?.annotations[CLUSTER_BADGE.COLOR]

2022-01-19 17:32 UTC, richard-cox commented on config/labels-annotations.js
> +  USE_AS_ICON: 'ui.cattle.io/badge-use-as-icon',
We could eek out some more functionality by making this the letter to show?

2022-02-03 18:58 UTC, nwmac commented
@richard-cox Updated with your feedback.

2022-02-04 14:16 UTC, richard-cox approved these changes

2022-02-04 14:17 UTC, merged