Fix: issue with displaying Errors messages
rancher/dashboard pull request #5136
Opened 2022-02-16 13:39 UTC by scures

While editing an YAML file, if there's any HTTP error sent to the Footer>Banner component it will display it as `[Object Object]` 

![image](https://user-images.githubusercontent.com/88777903/154276150-1a647bb8-6ecd-4acc-94a7-4fd0734cc153.png)

This PR will fixes it by looking if the `label` objects includes a `message` propriety, if so it will stringify and display the Error message.

![image](https://user-images.githubusercontent.com/88777903/154276348-d6b5ace5-5597-48e2-9b60-d24935afe912.png)

2022-02-16 13:54 UTC, cnotv requested changes
Could you define a case to reproduce an error containing a message?

2022-02-16 14:05 UTC, scures commented
> Could you define a case to reproduce an error containing a message and reference the issue if exists?

I noticed that any response will an error (validation, network status etc..) will be affected. One way to reproduce would be: 
- Edit any Pod configuration vía YAML and change any boolean value to something invalid like `falsea` , this will return a 400 Error and you'll be able to preview it.

2022-02-16 14:52 UTC, cnotv commented on components/Banner.vue
> +      <span v-else-if="label.message" v-html="JSON.stringify(label.message)" />
Correcting my suggestion after discussing and realizing it's not possible to use the optional operator within the template:

In the template
```html
  <span v-else v-html="parsedLabel" />
  ```

As computed variable
```ts
parsedLabel(): string {
  return this.label?.message 
    ? JSON.stringify(this.label.message)
    :  nlToBr(this.label))
}
```

2022-02-17 16:40 UTC, scures commented on components/Banner.vue
> +      <span v-else-if="label.message" v-html="JSON.stringify(label.message)" />
@cnotv I pushed the changes with the  ` return !(typeof this.label === 'string') ? stringify(this.label) : undefined;` seems the more reasonable solution at this point.

What do you think?

2022-02-17 16:47 UTC, cnotv commented on components/Banner.vue
> +      <span v-else-if="label.message" v-html="JSON.stringify(label.message)" />
For me it's ok, as I would have to investigate way too much to make it work with the type and we don't want to get stuck now with this.

2022-03-09 19:31 UTC, cnotv approved these changes

2022-03-11 09:48 UTC, nwmac commented
@richard-cox Could you give this the once-over - is this something we want to get in for 2.6.4?

2022-03-15 10:55 UTC, richard-cox approved these changes

2022-03-15 13:28 UTC, merged