HARVESTER:  feture & bug fix
rancher/dashboard pull request #5189
Opened 2022-02-23 04:29 UTC by WuJun2016

## harvester feature & bug fix
1. harvester upgrade
2. code refactoring

2022-02-24 13:12 UTC, richard-cox requested changes
As per other reviews i haven't tested the functionality but gone through the code.

There's a couple of inline comments but also...

The namespace filter has moved to the left, it looks this has broken the way it's hidden for the custom harvester namespace filter. The cluster name now doesn't need truncating
  ![image](https://user-images.githubusercontent.com/18697775/155518086-7817b798-a7e2-4f31-907d-4d54443b41b9.png)

2022-02-25 03:52 UTC, WuJun2016 commented on components/HarvesterUpgradeProgressBarList.vue
> +  .fload-r {
Done.

2022-02-25 03:53 UTC, WuJun2016 commented on components/nav/Header.vue
> +    <div
Done.

2022-02-25 03:55 UTC, WuJun2016 commented
Hi @richard-cox. PTAL，  thanks.

2022-02-25 14:44 UTC, richard-cox approved these changes

2022-02-25 14:45 UTC, merged