Gir Repo intro page is not showing - #4952
rancher/dashboard pull request #5207
Opened 2022-02-24 18:38 UTC by Shavindra

## Summary

Issue #4830  - Update no git repo landing page.

#5063 - This is the original PR. When rebasing with the master somehow this was broken. This PR apply the fix again.

## Steps to test
1. Navigate to Continuous delivery > Git repos.
2. Ensure there are no repos. 
2. It should display the following view of the content.
3. Note: The header and side menu is out of scope for this PR.

![image](https://user-images.githubusercontent.com/1955897/152501379-c0ea6584-fcaf-4055-be2f-8c8414d736bf.png)

2022-02-24 22:19 UTC, catherineluse commented
when you linked https://github.com/rancher/dashboard/issues/4830, did you mean to link https://github.com/rancher/dashboard/issues/4952?

2022-02-24 23:23 UTC, catherineluse requested changes
When I built it locally, the icon looked a little bit too low and to the right. can it be more centered?
<img width="1676" alt="Screen Shot 2022-02-24 at 4 03 04 PM" src="https://user-images.githubusercontent.com/20599230/155624169-8fa7bf25-2c1b-48ff-8c05-2294727d6e3f.png">

2022-02-24 23:23 UTC, catherineluse commented on components/fleet/FleetRepos.vue
> +      // Shouldn't happen, but does for resources like management.cattle.io.preference
This comment seems out of place because this table contains only gitRepos, not preferences

2022-02-24 23:23 UTC, catherineluse commented on components/fleet/FleetRepos.vue
> +      const includedNamespaces = this.$store.getters['namespaces']();
Git repos can't be created in a namespace, so why are we filtering by namespace?

2022-03-02 14:40 UTC, nwmac approved these changes
LGTM

2022-03-02 16:56 UTC, catherineluse approved these changes
LGTM

2022-03-03 09:43 UTC, merged