Improve namespace filter
rancher/dashboard pull request #5226
Opened 2022-02-26 18:33 UTC by nwmac

Fixes #5364 

This PR fixes a number of issues with the namespace filter control - some made more obvious by its move to the right hand side.

2022-03-07 11:40 UTC, richard-cox requested changes
- The top level control lacks focus on tab, with the old one a user could tab to it which would open the drop down. This gets a bit frustrating given that a lot inside the tab can still be done via the keyboard.
- `cattle-impersonation-system` is cropped when it's the first one selected before others
  ![image](https://user-images.githubusercontent.com/18697775/157022018-dcf2dec7-2bc3-4667-9f68-c2dd641f0ae9.png)


Minor
- It was quite nice mouseing over and seeing the selection, an improvement would be to add a tooltip to the `+<x>` pill to show one
- Now that the pills don't all have the close button it's handy to remove all selected pills via the `All Namespaces` option (or other similar global ones). In harvester land they don't have these so would be forced to manually find the entries in the list and deselect. Not bad on small systems but may not scale well on system with a lot of namespaces. For their use case they should bring in the `All Namespace` option as it's there by default. I've got a public system that you can access with harvester if you'd like to fix this one
   ![image](https://user-images.githubusercontent.com/18697775/157024297-a8271f63-6479-41d8-bde9-a822e95720f4.png)

2022-03-09 21:02 UTC, nwmac commented
@richard-cox Updated to address your comments apart form the ability to hover and see the selection.

2022-03-10 09:11 UTC, nwmac commented
@richard-cox I went ahead and added a tooltip as well - should be good to re-review

2022-03-10 11:06 UTC, richard-cox approved these changes

2022-03-11 09:40 UTC, merged