add notification
rancher/dashboard pull request #5284
Opened 2022-03-03 05:54 UTC by WuJun2016

Add a global message for the click action。

2022-03-03 08:49 UTC, richard-cox requested changes
`resourceAction` is primarily used by `doAction` where a lot of the time it handles the exception and displays the error in a specific way.

What's the root bug that this fixes, is it to do with actions in tables?

2022-03-03 14:00 UTC, richard-cox commented
@WuJun2016 Unfortunately if we catch the error within `doAction` we would need to change a lot of other places that won't handle failures currently without a thrown exception. 

Could there be a new method in `/plugins/steve/resource-class.js`, next to `doAction` that catches the failure?  Something like...
```
  doActionGrowl(actionName, body, opt = {}) {
    try {
      return this.$dispatch('resourceAction', {
        resource: this,
        actionName,
        body,
        opt,
      });
    } catch (err) {
       this.$dispatch('growl/fromError', {
        title: rootGetters['i18n/t']('generic.notification.title.error'),
        err:   err.data || err,
      }, { root: true });
    }
  }
```
Anywhere then that doesn't need the exception can be explicitly changed

2022-03-03 15:35 UTC, WuJun2016 commented
Hi， @richard-cox   Done, PTAL,  thanks a lot.

2022-03-04 10:22 UTC, richard-cox approved these changes

2022-03-04 10:22 UTC, merged