HARVESTER:   single cluster feature & bug fix
rancher/dashboard pull request #5342
Opened 2022-03-10 10:13 UTC by WuJun2016

2022-03-10 17:11 UTC, richard-cox requested changes
Two super minor comments, otherwise LGTM

2022-03-11 07:00 UTC, n313893254 commented on mixins/harvester-vm/impl.js
> +      if (smmEnabled && efiEnabled) {
smmEnabled and efiEnabled might be `undefined`. Seems `return !!(smmEnabled && efiEnabled)` will be better.

2022-03-11 07:28 UTC, WuJun2016 commented
Added a few new commits,  PTAL,  thanks.

2022-03-11 07:28 UTC, WuJun2016 commented on models/harvester/kubevirt.io.virtualmachine.js
> +    if (this.isOff || /pod has unbound immediate PersistentVolumeClaims/.test(super.stateDescription)) {
Done

2022-03-11 07:28 UTC, WuJun2016 commented on mixins/harvester-vm/impl.js
> +      if (smmEnabled && efiEnabled) {
Done

2022-03-11 07:28 UTC, WuJun2016 commented on assets/translations/zh-hans.yaml
>        tips: 凭证生效需要安装qemu-guest-agent，更新凭证内容后无需重启，添加凭证后需要重启生效，删除凭证后，需要进入虚拟机手动修改密码/删除ssh key
Done

2022-03-11 10:31 UTC, richard-cox approved these changes

2022-03-11 10:31 UTC, merged