Fix slow performance when creating a SortableTable
rancher/dashboard pull request #5382
Opened 2022-03-13 17:02 UTC by nwmac

This PR fixes a performance issue in the SortableTable component and improves the loading indicator display for ResourceList.

Currently SortableTable uses a VueX store module to maintain the table selection. When a SortableTable is created, we create a new store module and when it is destroyed we remove the steer module.

Unfortunately, creating modules in the VueX store is expensive and results in a noticeable delete when you switch to a page with a list (even when the data for it has already been fetched) - see https://github.com/vuejs/vuex/issues/1792.

For our use case there is no need to use a VueX store. This PR removes the store and stores the selection within the component.

In addition, this PS adds a loading indicator to SortableTable and wires that in through ResourceTable and ResourceList. This gives a better loading experience - rather than the whole view being blocked with a loading indicator, only the table is when waiting for data.

When we already have data, we don't show the loading indicator at all. There is a small issue that we can not distinguish data not being loaded from no rows. This causes the loading indicator to briefly show in cases where the table is empty. To work around this, we add a small delay - so the loading indicator only appears after that delay. This also helps with the case where data loads quickly and would cause the loading indicator to appear very briefly.

2022-03-24 12:13 UTC, richard-cox requested changes
- Bug # 1 - On the Helm Repo list select a single row and click on the `Refresh` action. The `x selected` count doubles up a few times on every press. Looking at the network tab it makes duplicate requests to the same resource (which results in 409 errors)
- Bug # 2 - On Pods list filter list by text, select a couple of rows and then change the sort order of the list. Same outcome as Bug # 1. Also saw the count creep up on it's own without interaction (i'm guessing the resource list was being updating by the backend)

2022-03-24 21:09 UTC, nwmac commented on components/SortableTable/index.vue
> +  // Loading indicatorr ow
Fixed - the issue was the selection is not cleared and the code was added back in the same items into the selection - we only need to remove items from the selection that were selected but are no longer in the list.

2022-03-24 21:09 UTC, nwmac commented
@richard-cox Fixed I think!

2022-03-25 11:26 UTC, richard-cox approved these changes

2022-03-25 11:26 UTC, merged