Fix harvester cluster create UI visibility when error.
rancher/dashboard pull request #5397
Opened 2022-03-15 09:33 UTC by Shavindra

## Summary

Issue #5373 - Harvester cluster create form error breaks UI

## Steps to test
1. Cluster management > Create Cluster 
2. Ensure RKE2 switch is turned on
3. Click on Harvester
4. Try to error the form in Machine pool (e.g. if there is no harvester instance/Images set up you can click on images dropdown)

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/1387263/158347977-d2b72769-2e0f-4c44-8db6-bafa1225bc56.png">

2022-03-15 11:14 UTC, richard-cox requested changes

2022-03-15 17:15 UTC, Shavindra commented on machine-config/harvester.vue
> -  <div v-else-if="errors.length">
How can the user rectify an error if the UI is completely hidden? 

Ref: #5373

2022-03-17 09:33 UTC, richard-cox approved these changes
I added a minor change to ensure that errors created during `fetch` are presented (they have no 'message')

2022-03-17 09:33 UTC, richard-cox commented on machine-config/harvester.vue
> -  <div v-else-if="errors.length">
Ok, i see the issue now, there are additional non-fetch errors that were being hidden

2022-03-17 09:40 UTC, merged