Inconsistencies with Cluster metrics across the UI
rancher/dashboard pull request #5542
Opened 2022-03-29 11:14 UTC by aalves08

Addresses Github issue: [#5430](https://github.com/rancher/dashboard/issues/5430)
Addresses Zube issue: [#5456](https://zube.io/rancher/dashboard-ui/c/5456)

- Fix number of PODS on homepage cluster table by displaying the proper PODs usage (`PodsUsage` component)
- Fix units for MEM on homepage cluster table to always be GiB (consistent with the rest of the UI)
- Show **total** number of nodes rather that **useful** nodes in cluster dashboard view 
- Remove reserved info for CPU and MEM in cluster table in homepage 
- Fix PODs usage in nodes list view (matches cluster dashboard and cluster table in homepage)

2022-04-01 13:28 UTC, nwmac requested changes
One minor comment.

We should also make the pod usage formatter a delayed component once the table performance changes are in

2022-04-01 13:28 UTC, nwmac commented on components/formatter/PercentageBar.vue
> +    N/A
Should probably use a localised string for this

2022-04-04 08:48 UTC, aalves08 commented
> One minor comment.
> 
> We should also make the pod usage formatter a delayed component once the table performance changes are in

Once you merge your end @nwmac I will test everything on my side. The idea then is to add `delayLoading: true` to the headers col definition and also add the method `startDelayedLoading()` to the formatter.

One question though:
I need to "move" what's inside of the async fetch in `components/formatter/PodsUsage.vue` to be called from `startDelayedLoading()` method? Those are the only two changes to do once your part gets merged, right?

Let's coordinate so that we can use this for 2.6.5 🙏

2022-04-13 11:09 UTC, nwmac approved these changes
LGTM - You'll need this PR merged - https://github.com/rancher/dashboard/pull/5635 - to fix an issue with the sortable table delay loading

2022-04-13 12:45 UTC, merged