State of Machine in Cluster Management page is seen as Active when the node is in Provisioning state
rancher/dashboard pull request #5570
Opened 2022-04-04 14:17 UTC by aalves08

Addresses Github issue: [#5443](https://github.com/rancher/dashboard/issues/5443)
Addresses Zube issue: [#5469](https://zube.io/rancher/dashboard-ui/c/5469)

- Fix pending and ready counts for MgmtNodePool model

2022-04-04 14:21 UTC, aalves08 commented
@richard-cox I spent quite some time looking into the code and for the `MachineSummaryGraph` component we need not only the count of each occurence of a state but also the `pending` and `ready` counts for each element.
We chatted about changing the stateParts in the models, but not only they are present in multiple components/formatters they won't fix the "view" of provisioning nodes in the cluster management list.
With that in mind, imo, I don't think it's worth changing a ton of stuff and risk "breaking" the view of multiple components.

I only fixed the "countS" for the RKE1's

2022-04-06 08:27 UTC, richard-cox requested changes
@aalves08 I'm confused why changing `./models/provisioning.cattle.io.cluster.js` `stateParts` to return the actual state of nodes/machines rather than the approximation won't fix the issue of the disparity between the cluster nodes states? and the management pool's node states?

2022-04-06 08:27 UTC, richard-cox commented on models/management.cattle.io.nodepool.js
> +    return this.desired - this.pending;
Changing this to desired (think of this as the configured amount) instead of actual nodes means ready won't represent actual nodes that are ready

2022-04-06 08:27 UTC, richard-cox commented on models/management.cattle.io.nodepool.js
> +    return this.nodes?.length ? this.nodes.filter(node => node.state !== 'active').length : 0;
If no nodes exist... but we do want some... then pending shouldn't be zero

2022-04-11 09:45 UTC, richard-cox reviewed
After our call I've compared nodepools (np) and machinedeployments (md).

Md's make use of the generic replica set states, mostly `status.replicas` and `status.unavailableReplicas`. In the aim of making the two behave the same I tried to apply those concepts to 'nodes count` and `nodes that are "active"`. We get something like

```
   get desired() {
    return this.spec?.quantity || 0;
  }

  get pending() {
    return Math.max(0, this.desired - this.nodeActiveCount);
  }

  get ready() {
    return Math.max(0, this.nodeCount - this.unavailable);
  }

  get unavailable() {
    return this.nodeCount - this.nodeActiveCount
  }

  get nodeActiveCount() {
    return this.nodes?.filter(node => node.state !== 'active') || 0
  }
  get nodeCount() {
    return this.nodes?.length || 0;
  }
```

However, that might dupe up some of the counts.

Also looking at md and it's states, i'm not sure the `pending state` is valid, as spec.replicates will probably always match status.replicas.

Although it's more of an investment, I think displaying counts associated with actual node/deployment states would be much more helpful here.

@nwmac Do we have any other options?

2022-04-22 09:13 UTC, closed without merging