Config map view inconsistent for binary data
rancher/dashboard pull request #5602
Opened 2022-04-08 15:27 UTC by aalves08

Addresses Github issue: [#5311](https://github.com/rancher/dashboard/issues/5311)
Addresses Zube issue: [#5336](https://zube.io/rancher/dashboard-ui/c/5336)

2022-04-12 09:57 UTC, nwmac requested changes
Looks good to me.

On the edit config page for a config map, can we add a message to the binary data tab when there is no binary data - at the moment you just get:
![image](https://user-images.githubusercontent.com/1955897/162934074-24bfd569-2187-42e0-958e-cd170d68fff0.png)

Something like: "No binary data'.

Also - when there is binary data, can we add an info banner underneath the 'Binary Data' heading that says 'Binary data can not be edited in the UI'

Lastly, although binary data can not be edited, it would nice to be able to remove binary data keys.

2022-04-13 08:58 UTC, nwmac requested changes
Two small things:

- Can we change the message to "Binary Data values can not be edited in the UI" = since you can change the key name and delete - you can't change the value
- Can we only show the above message when the mode is edit - currently you see the message about not being able to edit when you are viewing the config

2022-04-14 19:50 UTC, richard-cox requested changes
I've lost track of what we were aiming for on a few things
- If there is no initial binary data the user cannot add new entries (just get the 'no binary data' message instead of `Read from Filer` button). Not sure if this was a stretch goal?
- In the config tab the user could always see binary data (in view and edit modes) instead of the summary size string (due to the configmap not setting `:display-values-as-binary="true"`). Should they see it in view but not in edit? Neil mentioned in edit mode there should be a message saying they can't edit binary data, this is missing

![image](https://user-images.githubusercontent.com/18697775/163465161-376e5dcb-c845-482e-9099-06482a8050d9.png)
![image](https://user-images.githubusercontent.com/18697775/163465276-066ba37c-b619-4bac-bc19-74e186c1efb3.png)
![image](https://user-images.githubusercontent.com/18697775/163465324-2f2abeb3-39f4-495a-a6ff-fd15918c5a9b.png)

2022-04-14 19:50 UTC, richard-cox commented on components/form/KeyValue.vue
> -
I think you might have an odd linting rule that puts these in. Generally I think we have lines where they have been removed in the file

2022-04-14 19:50 UTC, richard-cox commented on assets/translations/en-us.yaml
> +      noData: No Binary Data available for this ConfigMap...
There should be a matching message in place for when there's no (non-binary) data. At the moment it shows the keyvalue form but with a placeholder for a row

2022-04-14 19:50 UTC, richard-cox commented on assets/translations/en-us.yaml
> +      noData: No Binary Data available for this ConfigMap...
This shouldn't have the `...`

2022-04-19 13:38 UTC, richard-cox approved these changes

2022-04-19 13:39 UTC, merged