Fleet add repository form update - #5197
rancher/dashboard pull request #5625
Opened 2022-04-12 10:20 UTC by Shavindra

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-04-19 08:46 UTC, richard-cox requested changes
`CruResourceWizard` component contains large blocks of copy & paste from both `CruResource` and `Wizard` 

If we go with the idea of a `CruResourceWizard` we need to ensure it's a lightweight wrapper around the existing Wizard without the duplicated code of either. Button integration can be added to either inject buttons into the wizard or `CruResource`.

2022-04-19 09:03 UTC, Shavindra commented
@richard-cox yes, I didn't want to refactor existing code. I wasn't sure if its going to break anything. I was going to wait after the merge to go in and refactor to inject buttons. Let me know if you still like to do this as part of this PR? or after?

2022-04-19 10:03 UTC, richard-cox commented
@Shavindra There's a balance between potentially dangerous changes and technical debt, I think in this case the scales are in favour of the changes.

If the practise of `slots` are stuck to then it should minimise the danger, so the CruResourceWizard would override `slots` in the Wizard for the header and buttons. The slot for the buttons could provide a lot of the plumbing (not sure of names but things like canNext, Next(), canPrevious(), etc)

2022-04-23 09:05 UTC, richard-cox commented
Update on status, briefly went through this with Shavin on Friday and there's some tweaks still to do

2022-04-25 14:11 UTC, richard-cox requested changes
There's still a lot of copy and paste from the Wizard throughout here. 

Anything containing internal wizard logic like activeStepIndex, showPrevious, stepsLoaded, goToStep etc should be accessed via the wizard itself. 

Any properties left that are absolutely vital should be defined in a mixin to keep them nicely separate (this isn't a pattern that's been well applied, but is done well in the `SortableTable`).

2022-04-26 17:18 UTC, richard-cox requested changes

2022-04-26 17:18 UTC, richard-cox commented on components/CruResource.vue
> +    initStepIndex: {
not used, can be removed

2022-04-26 17:18 UTC, richard-cox commented on components/CruResource.vue
> +    showBanner: {
not used, can be removed

2022-04-26 17:18 UTC, richard-cox commented on components/CruResource.vue
> +    initialTitle: {
not used, can be removed

2022-04-26 17:18 UTC, richard-cox commented on components/CruResource.vue
> +    handleStepChange(e) {
given the changes to the wizard slot/templates  i don't think this is needed anymore (along with the local copy of `activeStep` - when used in a template that should come from a slot)

2022-04-26 17:18 UTC, richard-cox commented on components/Wizard.vue
> +      this.$emit('stepChange', { step: selected });
given comment above hopefully this can be removed

2022-04-28 16:59 UTC, richard-cox requested changes
App Charts install wizard
  - there's no space now between header and content
  ![image](https://user-images.githubusercontent.com/18697775/165794499-e3165653-7343-4881-80c6-377fd6e8d6bd.png)


Git Repo Wizard
- You'll need to rebase with master. There was a bug which resulted in the cru resource error section to always show (including it's margin). Manually removing the section in this branch (as if it were master) makes the header look odd
  ![image](https://user-images.githubusercontent.com/18697775/165801814-6c2da99a-170f-443d-8406-d21aa14f2c64.png)
  ![image](https://user-images.githubusercontent.com/18697775/165801929-e552ccf4-be3b-42f2-b983-d0d4bfee5979.png)
- For this usage of the wizard header, where there are no icons, it consumes a lot of space. The `Wizard` should provide a way to override the .header > .title min-height . The cru resource should set this to something around 60px (the steps on the right will still need to look ok)
- The first step is titled `Finish: Step 1`. The verb should be linked to the change of resource like in the header above. Though given it's there I don't think it needs repeating here so can be removed
  ![image](https://user-images.githubusercontent.com/18697775/165803568-df78e7e5-00f1-4341-86c8-24bae929aff1.png)
- There's a lot of content in step 1, user would need to scroll in most windows which isn't very step-ish. So would suggest creating an additional step. Maybe move git and helm auth fields into a `Repo Auth` step? To confirm with Neil.
- There's 2 fields marked as required on step one and the `Next` button is enabled when either are empty. To fix this you can add `ready: false` to the `step` 1 object.

2022-05-31 08:56 UTC, richard-cox requested changes
App Charts install wizard
- "there's no space now between header and content". Header & Content being the vertical contexts. So...
  ![image](https://user-images.githubusercontent.com/18697775/171131987-cbabc110-50cc-41c4-b5a2-b04ccbc9b2c2.png)
  vs 
  ![image](https://user-images.githubusercontent.com/18697775/171132062-eb2be004-e907-49d0-864e-037a5fbba651.png)
- The footer is now broken
  ![image](https://user-images.githubusercontent.com/18697775/171132347-f55b876e-b76b-44ff-a386-ba9e6fbe60b4.png)

Git Repo Wizard
- The vertical alignment for the step details part (to high) and the step breadcrumbs (too low) are now out 
  ![image](https://user-images.githubusercontent.com/18697775/171132622-014c6f75-8271-4fa4-840a-872b9fd120b3.png)
- "The first step is titled Finish: Step 1. The verb should be linked to the change of resource like in the header above. Though given it's there I don't think it needs repeating here so can be removed"
  - The actual line is `<h2>{{ t(`asyncButton.${headerMode || finishMode}.action`) }}: {{ t('wizard.step', {number:activeStepIndex+1}) }}</h2>` so passing in a `headerMode` matching the create/edit context should work

2022-05-31 09:08 UTC, richard-cox requested changes
App Charts install wizard
- "there's no space now between header and content". Header & Content being the vertical contexts. So...
  ![image](https://user-images.githubusercontent.com/18697775/171131987-cbabc110-50cc-41c4-b5a2-b04ccbc9b2c2.png)
  vs 
  ![image](https://user-images.githubusercontent.com/18697775/171132062-eb2be004-e907-49d0-864e-037a5fbba651.png)
- The footer is now broken
  ![image](https://user-images.githubusercontent.com/18697775/171132347-f55b876e-b76b-44ff-a386-ba9e6fbe60b4.png)

Git Repo Wizard
- The vertical alignment for the step details part (to high) and the step breadcrumbs (too low) are now out 
  ![image](https://user-images.githubusercontent.com/18697775/171132622-014c6f75-8271-4fa4-840a-872b9fd120b3.png)
- "The first step is titled Finish: Step 1. The verb should be linked to the change of resource like in the header above. Though given it's there I don't think it needs repeating here so can be removed"
  - The actual line is 
  - ```<h2>{{ t(`asyncButton.${headerMode || finishMode}.action`) }}: {{ t('wizard.step', {number:activeStepIndex+1}) }}</h2>``` so passing in a `headerMode` matching the create/edit context should work
- I entered a git and helm auth on step 1, hit next for step2, hit previous back to step1 and the controls for both had been reset. looks like the same issue when editing an existing repo with both settings
- When editing an existing repo the next button on step one didn't become enabled until there was a change of any value

2022-06-10 10:59 UTC, richard-cox requested changes
Git Repo Wizard
- The alignment in the header is still out
  ![image](https://user-images.githubusercontent.com/18697775/173049987-dd9b9294-eb99-4803-9308-69c82b0daac9.png)
  - The vertical alignment for the step details part is now too low, it needs to be centered
  - the step breadcrumbs are unchanged and too low. They should be centered as well with the line leading between the dots.
- The first step is still titled "Finish: Step 1". See comment in https://github.com/rancher/dashboard/pull/5625#pullrequestreview-990102151
- git and helm auth on step 1, is still lost on return. See comment in https://github.com/rancher/dashboard/pull/5625#pullrequestreview-990102151

2022-07-14 15:55 UTC, richard-cox requested changes
- Loading the create repo page throws a full page dev error due to `AUTH_TYPE` missing in data in `SelectOrCreateAuthSecret`
- There's an issue when viewing the github repo `Config` tab (see below). That tab shows the resource's `edit` component but in `VIEW` mode (all components disabled, no cancel/save buttons). As a low-bar solution the wizard within CruResouce should also take this in to account (no content left of the breadcrumbs, no edit as YAML, form controls disabled by passing on `mode`), 
   ![image](https://user-images.githubusercontent.com/18697775/179018197-915965bb-12fa-42f5-8f47-47754cccce7d.png)

2022-07-18 00:57 UTC, Shavindra commented on shell/edit/fleet.cattle.io.gitrepo.vue
> +    addRepositorySteps() {
The steps are dynamic

2022-07-18 10:08 UTC, richard-cox requested changes

2022-07-18 13:23 UTC, richard-cox commented on shell/components/CruResourceFooter.vue
> +        v-if="isView || showCancel"
That's fine. This is on the config tab and the other edit pages in this context don't have the cancel buttons either.

Going forward this should hopefully change anyway. The wizard should be used for create flows and the traditional tab way for edit flows (the edit flow would then replace this wizard in the config tab). For this round though we're falling back on the wizard.

2022-07-18 16:03 UTC, richard-cox approved these changes
LGTM! Remember to squash merge

2022-07-18 16:55 UTC, merged