prevent scale down of only machine in a pool
rancher/dashboard pull request #5673
Opened 2022-04-20 20:47 UTC by mantis-toboggan-md

### Summary
Fixes #5454 
The machine pool scale down button is disabled when the pool spec has only one replica defined; the individual pool scale down action menu option was disabled when the machine was the only instance of a controlplane or etcd role. This meant that if a cluster had one pool of workers with one worker machine, the pool couldn't be scaled down but the machine could. 

### Occurred changes and/or fixed issues
This PR updates the machine's `canScaleDown` function to prevent scaling down when it's the only machine in a pool. The role-checking logic is removed, since a machine can't be the only instance of a role without also being the only machine in its pool.

2022-04-20 21:23 UTC, richard-cox reviewed
I've requested some design clarifications from Gary over at https://github.com/rancher/dashboard/issues/5454#issuecomment-1104464507. If we go down this path some of the other locations will need to change to avoid other discrepancies between the three ways to scale

2022-04-21 10:26 UTC, richard-cox commented
Additional comment, https://github.com/rancher/dashboard/issues/5454#issuecomment-1105025068. Waiting on clarification on slack regarding how scaling to zero should (or shouldn't) work

2022-04-22 16:48 UTC, richard-cox requested changes
Ok, think it's sorted now, see https://github.com/rancher/dashboard/issues/5454#issuecomment-1106688959

2022-04-22 20:54 UTC, mantis-toboggan-md commented
Updated the +/- buttons to use (essentially) the same logic as the individual machine action menu item: the - button should now be disabled when scaling down the pool would result in the loss of the only etcd or controlplane machine in the cluster.

2022-04-23 03:49 UTC, rak-phillip reviewed
I might have some reservations in that I can scale down `etcd` nodes rapidly enough that I can put my cluster in a failure state.

![image](https://user-images.githubusercontent.com/835961/164873996-23e67030-4ed4-464c-9120-5c8f9883c00f.png)

![image](https://user-images.githubusercontent.com/835961/164874071-dd3fd1f0-f6c7-4f0d-8fe2-bf8961796c0c.png)

I'm able to get into this state by selecting the overflow menu => scale down all of the machines in a pool, one after the other. Perhaps, another set of eyes might not be a bad idea.

2022-04-23 03:49 UTC, rak-phillip commented on models/cluster.x-k8s.io.machine.js
> +// This is a little overly optimised but avoids iterating over the whole machine set every time
Personally, I would prefer JSDoc style comments to provide a little more context about our parameters and what we're returning. I find the function name of `noOnlyOfRole` to be a bit unclear, especially when `type` is used so much throughout the function body.

2022-04-23 10:31 UTC, richard-cox approved these changes
@mantis-toboggan-md I've made some small tweaks and tested (see commit message). Unless there's any objections I'll merge tomorrow.

I'd agree with Phil's comment regarding scaling down to bad states, I think you/he encountered issues as per Brandon's comment. Under the hood we set an annotation on each effected machine and then scale down the pool the machines are in by that amount. Smarts for doing this correctly might need to come from the backend. In terms of scaling by the pool buttons, it's possible to hit the same bad state, but requires more effort.

Given that this PR addresses bottom line machine vs type availability I'd say we should still get this in. Further improvements (both frontend and backend) came come in a later one.

2022-04-24 19:41 UTC, merged