Enable restricted admin settings.
rancher/dashboard pull request #5697
Opened 2022-04-25 12:33 UTC by Shavindra

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-04-25 13:11 UTC, richard-cox commented on store/type-map.js
> +        if (p.overrideIfHaveVerbFor) {
When this is generic it can be bumped up out of the `ifHaveType` condition

2022-04-25 13:11 UTC, richard-cox commented on store/index.js
> +    if ( getters['management/canList'](MANAGEMENT.GLOBAL_ROLE_BINDING) ) {
Ok, I see the gotcha here, I failed to realise we'd need to fetch all global role bindings up front.

Need to decide which is preferable to resolve https://github.com/rancher/dashboard/issues/4954

1. Load global role bindings on every visit 
- could impact systems with lots of people/project 
- could be a nice feature for other use cases
2. Show Global Settings to everyone
- reveal admin only things to non-admins 
- they can do this already, but not in the UI

2022-04-25 13:39 UTC, richard-cox requested changes
Ok, this approach won't work, sorry for suggesting it. See https://github.com/rancher/dashboard/issues/4954#issuecomment-1108573899

2022-04-25 18:12 UTC, richard-cox commented
As per https://github.com/rancher/dashboard/pull/5697#pullrequestreview-951880854, this approach unfortunately won't work

2022-04-25 18:12 UTC, richard-cox requested changes
As per https://github.com/rancher/dashboard/pull/5697#pullrequestreview-951880854, this approach unfortunately won't work.

2022-04-25 19:21 UTC, Shavindra commented
@richard-cox yes... I am disabling `rowsActions`. I am leveraging existing functionality

https://github.com/rancher/dashboard/blob/master/components/SortableTable/index.vue#L931-L937

2022-04-26 12:57 UTC, richard-cox requested changes
Banners & Branding pages `Apply` buttons are still shown when the user doesn't have permissions to edit

2022-04-26 17:34 UTC, richard-cox approved these changes

2022-04-27 07:49 UTC, merged