Allow configuring ingress tls secrets that does not exist
rancher/dashboard pull request #5856
Opened 2022-05-06 12:42 UTC by bashofmann

### Summary
Allow configuring ingress tls secrets that does not exist

This is useful when you use cert-manager together with the ingress-shim functionality. For that you need to specify a tls secret name that does not exist. The secret will then be automatically created and populated by cert-manager.

See https://cert-manager.io/docs/usage/ingress/

Fixes https://github.com/rancher/dashboard/issues/5714

### Areas or cases that should be tested
Creating/Updating an Ingress.

### Areas which could experience regressions
There should be no regression possible. The default value for `push-tags` in a `v-select` is `false` and it's only set to `true` in the `Certificate` component.

### Screenshot/Video
Screenshot of creating an ingress and referencing a non existent secret
![Bildschirmfoto 2022-05-06 um 14 37 42](https://user-images.githubusercontent.com/243056/167132804-f9e0df96-1687-48ab-8b81-061aa5bcefa6.png)

2022-05-27 08:27 UTC, richard-cox commented
There were some major changes in folder structure recently that have resulted in conflicts in this PR (basically a lot of code is now in `./shell` rather than just `./`. A standard rebase with master should resolve them. If you hit any build issues try

1) `yarn clean`
2) removing your local `node_modules` folder and then `yarn install`

Feel free to ping me in slack if there's any questions

2022-05-28 11:46 UTC, bashofmann commented
The PR is rebased. Worked without a problem.

2022-05-31 12:24 UTC, richard-cox requested changes
This is an odd one, as it was always possible to use the component to create entries (enter text, select from drop down). This is enabled by the `taggable` property (https://vue-select.org/api/props.html#taggable) and used in many places in the dashboard. The addition of `pushTabs` (https://vue-select.org/api/props.html#pushtags) just means the entry will be visible in the drop down after it was selected. 

I don't think we should tweak `taggable` / `pushTabs` behaviour for just the case, if we go ahead we should probably automatically set `pushTabs` when `taggable` is set. Alternatively we don't change anything, when the resource is edited we don't then push that selected value into the drop down again so even with the change it looks the same way as before.

I'll have quick check with @nwmac but think maybe we should align the two values. I'll update this comment with the recommendation.

2022-06-01 10:33 UTC, richard-cox commented
After chatting with Neil we feel that this is a general usability issue and will be resolved via https://github.com/rancher/dashboard/issues/6077

2022-06-01 10:33 UTC, closed without merging