translations: Replace vendor tag with name tag
rancher/dashboard pull request #5939
Opened 2022-05-12 12:40 UTC by mkutlak

### Summary

With custom branding [0]  telemetry sentence mentions custom company name instead of Rancher.

[0] https://rancher.com/docs/rancher/v2.6/en/admin-settings/branding/

### Screenshot/Video
![rancher_telemetry](https://user-images.githubusercontent.com/24898105/168076475-9bbc20e2-ec5c-4cce-8bf7-4fa4a6466b35.png)

2022-05-12 12:57 UTC, richard-cox commented
General comment - In the setup flow there's a number of different uses of {name} and {vendor}. We (dashboard) side need to confirm if these need to be consistent and if not what should be used where

2022-06-10 13:55 UTC, richard-cox requested changes
I'm just double checking if telemetry data always comes to Rancher. That aside the PR is broken, name isn't parsed through when `setup.telemetry` is used (for other usages on the page see https://github.com/rancher/dashboard/blob/master/shell/pages/auth/setup.vue#L367). So something like below would work
```
:label="t('setup.telemetry', { name: productName })"
```

2022-06-13 16:55 UTC, mkutlak commented
Good catch!


I tried to apply your suggestion, but it didn't do what I expected. 
![telemetry_label_not_great](https://user-images.githubusercontent.com/24898105/173405114-52254f6f-eebb-45b2-a686-d92897dc6b25.png)

So I just reused that code for eula and it seems to work.
![telemetry_label](https://user-images.githubusercontent.com/24898105/173405288-d77d42a9-0af6-439f-939a-d9b4f702f4a0.png)

2022-06-20 10:47 UTC, richard-cox approved these changes

2022-06-20 10:48 UTC, merged