Services card, instances title, configurations break
rancher/dashboard pull request #6001
Opened 2022-05-20 08:29 UTC by scures

Recreation of https://github.com/rancher/dashboard/pull/5678

2022-05-23 07:59 UTC, scures commented
## Old
![image](https://user-images.githubusercontent.com/88777903/169771923-b2efeb3e-022b-4103-9ed6-11cd8318b799.png)

## New
![image](https://user-images.githubusercontent.com/88777903/169771824-9f60cfeb-e01c-4181-99e6-8c244e8a0709.png)

2022-05-27 10:30 UTC, richard-cox requested changes
After rebasing you'll need to use the latest epinio, i need to update the public instance with this and will let you know when it's done.

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +                <td>{{ resourcesUssage.memoryBytes.toFixed(2) }} MiB</td>
The memory and cpu stats were already calculated in the application model. Can't remember if that was an older change or not, but we should probably use that version

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +        Age: 2d ago -->
The creation time has now been added(in meta.createdAt). Unfortunately I don't think we're getting uptime anytime soon

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +          {{ value.configCount }} {{ t('epinio.applications.detail.counts.services') }}
There's `Configurations` and there's also `Services` (which are instances of `Catalog Services`). The app can be bound to both, however the `configurations` property currently contains resources that apply to both types (as part of binding a service to an application a configuration is counted). Until https://github.com/epinio/epinio/issues/1471 is created we should keep this labelled as `Configurations`

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +    choseIcon() {
This isn't used?

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +      switch (this.value.sourceInfo?.label) {
Switching on human text generally isn't advisable. The sourceInfo under the hood uses ` switch (this.origin.Kind) { 
    case APPLICATION_MANIFEST_SOURCE_TYPE.PATH:`
...

However, would advise adding an `icon` property to that `sourceInfo` object. To catch the blank case you can just use something like `value.sourceInfo.icon` || `icon-epinio`

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +            <h4>Deployment Details</h4>
The switch to ul/li leaves the spacing unable to consume the correct amounts

![image](https://user-images.githubusercontent.com/18697775/170682619-ce5a51aa-7d00-4a38-9582-a5d996a43691.png)

2022-05-27 10:30 UTC, richard-cox commented on pkg/epinio/detail/applications.vue
> +import ApplicationCard from '~/shell/components/cards/ApplicationCard.vue';
There's a frustrating issue that VSCode will default to imports with `~` when we don't want them to. For instance this should be `@shell`

2022-06-07 14:28 UTC, merged