WIP: Elemental advanced filtering
rancher/dashboard pull request #6224
Opened 2022-06-23 15:38 UTC by aalves08

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-07-12 14:24 UTC, aalves08 commented
@richard-cox this need a rebase from https://github.com/rancher/dashboard/pull/6225 and fixing possible merge conflicts, but bulk of work is done.
I'll ping you once this PR is "truly" ready for review. Thanks

2022-08-09 16:57 UTC, cnotv requested changes
There's some hints for coding, but some parts should really worked out (table, filtering). I'll take a round in the UI later on.

2022-08-09 16:57 UTC, cnotv commented on shell/components/SortableTable/filtering.js
> +  for ( let j = 0 ; j < searchTokens.length ; j++ ) {
I think you want to use [`.every()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every).

```ts
return searchTokens.every(token => {
  const expect =!token.substr(0, 1) === '!'; // could you please add comments to this, why is it needed?
  const cleanToken = expect ? token.substr(1) : token;

  return cleanToken && !(matches(searchFields, cleanToken, row) !== expect)
})
```

2022-08-09 19:36 UTC, cnotv commented on shell/components/SortableTable/filtering.js
> +  for ( let j = 0 ; j < searchTokens.length ; j++ ) {
Also it would be great to extend it for a more generic scope, instead of just `'!'`

2022-08-10 11:52 UTC, cnotv commented
During creation of a new Machine Registrations I get the error:
 
![Screenshot 2022-08-10 at 13 51 04](https://user-images.githubusercontent.com/5009481/183894424-e6bc5518-01e9-4733-aa0e-42b6ec3bf9d6.png)

Not sure why I cannot see the source code as this is supposed to have a source map for debugging and error tracing.

2022-08-10 12:09 UTC, cnotv commented
I was not able to find `Group by` or added filters/key as in the screenshot
The count of the machine in the sidebar does not update on creation till page refresh.

Edge cases for excessive number for filters seems covered.

It would be great if filter search field was automatically focused and confirm by pressing enter. This last one can be achieved by wrapping the filter in a form and assign the submit event, then switch the button to submit.

![Screenshot 2022-08-10 at 14 06 52](https://user-images.githubusercontent.com/5009481/183897425-e98c3c83-9db6-432e-a65e-eb9213a4a21e.png)

2022-10-05 09:57 UTC, nwmac commented
@aalves08 Can you separate out the changes just for advanced filtering?

2022-11-07 14:04 UTC, aalves08 commented
@nwmac @richard-cox going to close this PR.

Work has been merged to dashboard with the following PRs:
https://github.com/rancher/dashboard/pull/7168
https://github.com/rancher/dashboard/pull/7134

2022-11-07 14:04 UTC, closed without merging