Project delete namespaces
rancher/dashboard pull request #6279
Opened 2022-07-06 14:09 UTC by nwmac

This is a rework of https://github.com/rancher/dashboard/pull/5762

Fixes https://github.com/rancher/dashboard/issues/5624

Adds new custom promptRemove component to handle deleting project as well as associated namespaces

2022-07-07 10:12 UTC, richard-cox requested changes
I made two cheeky tweaks
- Deleting namespaces requires confirmation, but not projects. added and tested
  -  ![image](https://user-images.githubusercontent.com/18697775/177749350-05d1c84e-2e4e-421d-acc1-450c429e26a6.png)
- Added an alignment fix (before/after screenshots)
  - ![image](https://user-images.githubusercontent.com/18697775/177747862-92b29049-1e9c-46ca-85b9-5d966fc338fc.png)
  - ![image](https://user-images.githubusercontent.com/18697775/177747977-15d6c5f4-3ff4-49ea-b7d6-ea7938290065.png)

2022-07-13 11:03 UTC, nwmac commented on shell/promptRemove/management.cattle.io.project.vue
> +          resource.remove();
Thanks - I'll make that change

2022-07-13 11:03 UTC, nwmac commented on shell/promptRemove/kubevirt.io.virtualmachine.vue
> +    <span v-html="resourceNames(names, plusMore, t)"></span>
Agreed

2022-07-20 15:15 UTC, richard-cox approved these changes

2022-07-20 15:16 UTC, merged