HARVESTER: Fixes v1.0.3 issues
rancher/dashboard pull request #6398
Opened 2022-07-19 07:47 UTC by n313893254

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-07-19 19:12 UTC, mantis-toboggan-md requested changes

2022-07-19 19:12 UTC, mantis-toboggan-md commented on shell/list/harvesterhci.io.dashboard/index.vue
> +    ...mapGetters(['currentCluster', 'isVirtualCluster']),
`isVirtualCluster` is not being used in this component.

2022-07-19 19:12 UTC, mantis-toboggan-md commented on shell/components/form/NodeAffinity.vue
> +        rerenderNums:              0
See @aalves08 's comment here: https://github.com/rancher/dashboard/pull/6385#issuecomment-1189329523

2022-07-20 09:36 UTC, n313893254 commented
@mantis-toboggan-md Thanks for your review. Fixed and add enhancement for external Harvester credentials. Here is related [commnet](https://github.com/harvester/harvester/issues/2316#issuecomment-1189922378).

2022-07-20 19:47 UTC, mantis-toboggan-md requested changes

2022-07-20 19:53 UTC, mantis-toboggan-md approved these changes

2022-07-20 20:19 UTC, merged