Refresh projects before updating project
rancher/dashboard pull request #6416
Opened 2022-07-20 02:28 UTC by catherineluse

This PR addresses https://github.com/rancher/dashboard/issues/6377 by changing the order of what happens when we save a new project. If we fetch projects before updating the podsecuritytemplate, we avoid a version conflict.

I also removed the `forceReplaceOnReq` variable because it was always undefined a search revealed that it was not being passed in by anything. I set it true as that seems to be the intent of the original code.

2022-07-22 11:06 UTC, richard-cox requested changes
I still hit the `error updating PSPT ID` error, usually on the second or third attempt at creating a project.

My rancher version is `v2.6-b8afb4e50bcb692fe2a0757d3c62faa6f75a0e2e-head` (20th July)

2022-07-22 19:33 UTC, catherineluse commented on shell/models/management.cattle.io.project.js
> -  async save(forceReplaceOnReq) {
Ah, that makes sense. I'll revert it.

2022-07-22 22:27 UTC, catherineluse commented
I understand the issue a bit better now.

- My initial attempt to fix the issue involved moving the fetching of all projects to before the action to create the pod security policy template. I hoped that fetching all projects would make it so that our resource versions would match the newest version, but my assumption was wrong - it doesn't work that way. The resource version doesn't make a difference as it is not referenced in the async call to update the pod security policy template. The reason my previous PR looked like it was working was that it just added some wait time in between the project creation and PSP template creation, so that it was less likely that there would be a conflict, but it was still not impossible, as Richard was still hitting the error (). https://github.com/rancher/dashboard/pull/6416#pullrequestreview-1047752853
- I tried the approach Richard suggested https://github.com/rancher/dashboard/issues/6377#issuecomment-1185369752 which involved a forced refetch of the project. But I found that force-refetching the project didn't make a difference due to the fact that we don't use the resource version in our call to Norman.

My updated solution is to just retry the PSP template update if we get the 409 error. To test the PR, I created a bunch of projects, waited until I saw the 409 error in the logs, and confirmed that the project was successfully created with no errors in the UI.

2022-07-25 15:04 UTC, aalves08 approved these changes
If it's the only option we have to cover that test scenario, then LGTM

2022-07-25 15:24 UTC, merged