Incremental loading and manual refresh features
rancher/dashboard pull request #6543
Opened 2022-07-28 18:01 UTC by aalves08

- to edit

2022-07-29 16:11 UTC, richard-cox requested changes
- From a page where we've sub'd to `PODS` (edit service page) to `PODS` list, the type isn't unwatched
  - I don't think this is important, as the one who's initially subscribed may want to continue watching. Can probably leave this one
- From PODS list where we've not sub'd to `PODS` to Edit Service page, type is not now watched
  - This is more important, as the one that wants to be subscribed never is 
- We should limit this feature to the `EXPLORER` product until we're happier with it (and can ensure it's only enabled for those that use the kube api)
- If the initial partial resource load is executing the manual refresh button should be disabled

2022-08-01 10:10 UTC, aalves08 commented on shell/list/workload.vue
> +      loadResources:     allTypes ? Object.values(WORKLOAD_TYPES) : [route.params.resource],
True. Good one. 👊

2022-08-01 10:16 UTC, aalves08 commented on shell/mixins/resource-fetch.js
> +  beforeDestroy() {
That's easy: The mixin is included on both `Workloads` and `ResourceList`, so when you switch list view, both get destroyed (therefore running that hook). I've added a condition to only run on the mixin instance that has been initialized.
On the case of `Workloads` + `ResourceList`, despite the mixin is included on both, it's only initialized on `Workloads` 🙏

2022-08-01 10:23 UTC, aalves08 commented on shell/plugins/dashboard-store/actions.js
> +    } catch (e) {
Removed the whole `try - catch` block

2022-08-01 10:49 UTC, aalves08 commented on shell/plugins/dashboard-store/actions.js
> +    } catch (e) {
going to resolve this conversation @richard-cox , let me know if you don't agree 🙏

2022-08-02 11:30 UTC, richard-cox requested changes
I still see 
- On manual refresh the live columns fail to load (workload restarts & health)

Additionally
- PR description needs updating
  - list of affected resource
  - notes for QA, areas of possible regressions (would be good for them to test permissions)
- On the honker of a cluster, i don't see all resources loading (deployments - pagination shows 2893, side bar shows 3725. pods 2727 vs 2147). This might be the NS filter bug, need to confirm that shows when running the code from `master`

2022-08-02 18:13 UTC, richard-cox approved these changes
If the last changes pass CI then this is good to squash merge.

I've caught the failure to catch failure issue in https://github.com/rancher/dashboard/issues/6574

2022-08-03 11:02 UTC, merged