Check status.conditions exists before getting bundle lastUpdateTime - #6771
rancher/dashboard pull request #6818
Opened 2022-09-07 08:46 UTC by Shavindra

### Summary
Fixes #6771 - Rancher UI Can't Get to Bundles Page if Bundle Status is does not exist #6771

### Occurred changes and/or fixed issues
I couldn't really replicate the issue. I expect the schema and everything to be in place. However, I added optional property check to `this.status.conditions` for getter `lastUpdateTime`

### Areas or cases that should be tested

1. Navigate to Continuous Delivery > Git Repos
2. Click on Add repository
3. Use your own git repo or examples from https://github.com/rancher/fleet-examples to add a repo.
4. Click through newly created repo.
5. Delete all bundles from repo. Leave the bundles in place.
6. Refresh gitrepo object and verify bundle exists with kubectl
7. There should not be anymore errors.

2022-09-07 15:11 UTC, jordojordo requested changes
This solves the problem with `status.conditions`, although I'm receiving a different error of `row.status` returning `undefined`. Seems to be stemming from the `v-if` conditional [here](https://github.com/rancher/dashboard/blob/a10327efcd52e29492f82226070e74ef75a92fa7/shell/components/fleet/FleetBundles.vue#L120-L122)

![rowstatus](https://user-images.githubusercontent.com/40806497/188913813-e7c865da-9d59-49d8-9dcb-8fce67f5f2c2.png)

2022-09-11 17:26 UTC, Shavindra commented
@jordojordo I am not sure why I still can't replicate the issue. I've update the code anyway.

2022-09-12 13:00 UTC, jordojordo requested changes
@Shavindra I was able to replicate the issue by deleting all of the bundles and force updating afterwards.

https://user-images.githubusercontent.com/40806497/189659488-c5952c36-251c-4612-badc-90a15318f07b.mp4

Still getting the `row.status is undefined` but I was able to stop it by changing the `v-else` to `v-else-if="row.status"`
```vue
<span v-else-if="row.status">{{ row.status.summary.desiredReady }}</span>
```

2022-09-22 13:21 UTC, jordojordo requested changes
One minor change, but lgtm otherwise.

2022-09-22 13:21 UTC, jordojordo commented on shell/components/fleet/FleetBundles.vue
> +ß
This should be removed

2022-09-23 11:21 UTC, jordojordo approved these changes

2022-09-23 16:37 UTC, merged