Extract non localised strings
rancher/dashboard pull request #6825
Opened 2022-09-07 13:51 UTC by bisht-richa

### Summary
Fixes #6492

Fixed issues in some section pages.

Mostly badges, workspaces, names directly from Ids, links, and descriptions are not having localized strings.
Needs someone's help to fix I have updated those page details in the Zube card.

https://zube.io/rancher/dashboard-ui/c/6527

2022-09-28 07:22 UTC, nwmac commented
@bisht-richa Can this be moved out of draft?

2022-11-18 01:15 UTC, catherineluse commented
@bisht-richa Can you please rebase this on master?

2022-11-23 09:33 UTC, richard-cox requested changes
The PR diff doesn't look correct. This probably needs a rebase and manually checking each file. At first glance
- There's new files outside of `shell` 
- Some files haven't been merged correctly (for instance Carousel.vue)
- Some files show whitespace differences (for instance ExplorerProjectsNamespaces.vue)

I think it's worth going reviewing the confluence page on PRs (Development/Pull Requests). There's a good section on there that covers this sort of thing.

2022-11-24 17:16 UTC, richard-cox requested changes
There's still a lot of files changed that aren't to do with this issue
- .github/workflows/test.yaml
- shell/assets/images/generic-plugin.svg
- shell/components/Carousel.vue (this brings back a bug)
- shell/components/ExplorerProjectsNamespaces.vue (template)
- shell/components/Tabbed/index.vue
- shell/config/product/manager.js
- shell/edit/workload/index.vue
- shell/pages/c/_cluster/_product/projectsnamespaces.vue.
- store/prefs.js

Please make sure you go through the PRs `Files changed`

2022-11-24 17:16 UTC, richard-cox commented on shell/edit/auth/azuread.vue
> +      } else if ( newEndpointKey ) {
This does exactly the same as the else case

2022-11-29 12:15 UTC, closed without merging

2022-11-29 12:31 UTC, bisht-richa commented
Re open it