HARVESTER: Harvester Cloud Provider compatibility check enhancement
rancher/dashboard pull request #6995
Opened 2022-09-26 05:25 UTC by n313893254

### Summary
Harvester Cloud Provider compatibility check enhancement

### Occurred changes and/or fixed issues

- https://github.com/harvester/harvester/issues/2753

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-09-26 15:13 UTC, n313893254 commented
Hi, @mantis-toboggan-md. Backend PR does not merge yet. But I think you can review my PR, thanks.

2022-09-27 22:45 UTC, mantis-toboggan-md requested changes
I tested this by modifying setHarvesterVersionRange with the default value from [here](https://github.com/harvester/harvester/pull/2812):
```
 // const version = (res?.data || []).find(s => s.id === 'harvester-csi-ccm-version');

const version = { default: '{"harvester-cloud-provider": ">=0.0.1 <0.1.14", "harvester-csi-provider": ">=0.0.1 <0.1.15"}' };
 ```
 
 In light of code freeze being tomorrow, I'm fine with merging this without the backend merged yet.

2022-09-27 22:45 UTC, mantis-toboggan-md commented on shell/assets/translations/en-us.yaml
> +          You cannot select Harvester cloud provider as the current Harvester Version is not compatible with RKE2 Kubernetes Version, click <a target="_blank" rel="noopener noreferrer nofollow" href=
`You cannot select the Harvester cloud provider as the current Harvester version is not compatible with the selected RKE2 Kubernetes version, click <a target="_blank" rel="noopener noreferrer nofollow" href="https://www.suse.com/suse-harvester/support-matrix/all-supported-versions">here</a> to see which Kubernetes versions are supported.`

2022-09-27 22:45 UTC, mantis-toboggan-md commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +            v-if="isHarvesterDriver && isHarvesterIncompatible"
I think there should be `&& showCloudProvider` as well so the banner about cloud providers is not shown when the user cannot select a cloud provider (k3s kubernetes version is selected)

2022-09-28 17:37 UTC, mantis-toboggan-md approved these changes

2022-09-28 17:37 UTC, merged