Adds validation for git URL
rancher/dashboard pull request #7049
Opened 2022-09-29 14:58 UTC by scures

### Summary
Fixes # https://github.com/epinio/ui/issues/107

### Technical notes summary

1. Adds validation on input based on regex, it makes sure it matches the correct format of `{user or org}/{repository}`
2. Disables the branch input unless the URL is valid.

### Areas or cases that should be tested
1. Refer to the issue https://github.com/epinio/ui/issues/107 to understand the problem.
2. Try adding an invalid URL, it should disable the branch input and throw an error
3. Try adding a valid URL, it should enable the `branch` input and allows you to continue. 

### Screenshot/Video

2022-09-30 15:08 UTC, mmartin24 commented
I checked the following scenarios in branch:

### Case 1: URL with structure different from `{user or org}/{repository}` throws an error and prevents user from entering branch:
Example: `https://github.com/epinio/example-go/wrong`
![image](https://user-images.githubusercontent.com/37271841/193296561-4b7babca-25ff-445e-be22-4d8607ac0c54.png)

### Case 2: User is allowed to enter if structure is correct:
Example: `https://github.com/epinio/example-go`
![image](https://user-images.githubusercontent.com/37271841/193296760-d39721ee-94b0-474b-99d3-8eec83535b17.png)

However I found 2 scenarios where an error may still be produced:

### Case 3: Changing to bad URL after a correct previous one with branch included

Steps to reproduce: 
- Enter valid URL (ie: `https://github.com/epinio/example-go`)
- Enter valid branch (ie: `main`)
- Change URL to invalid (ie: `https://github.com/epinio/example-go/wrong`

Result: user not prevented from going to next screen:
![image](https://user-images.githubusercontent.com/37271841/193297793-de668926-898b-402a-a3f6-96243e6f206d.png)

### Case 4: Entering a bad URL with correct structure

Steps to reproduce: 
- Enter valid URL with bad ending (ie: `- Enter valid URL (ie: `https://github.com/epinio/example-gobadending`)

Result: user not preventing from next step:
![image](https://user-images.githubusercontent.com/37271841/193298675-cd9d9e7c-8240-4dfb-a2fe-c6b9f3cb2a6e.png)

@scures, cases 1 and 2 are simple cases strictly related to the pr; cases 3 and 4 are edge cases that may be addressed here or in another issue.

2022-10-06 11:41 UTC, mmartin24 commented
thanks @scures .
Checked Case 3 and working:
![image](https://user-images.githubusercontent.com/37271841/194303490-832ecdce-e0b0-44c9-8c15-d11ffcce57c7.png)

I hear what you say about case 4. If too complicated; let's focus for the moment other place.

2022-10-17 17:28 UTC, richard-cox requested changes
The Git URL can be any URL that points to a publicly available git instance, so validation should only match that of a URL rather than something github/gitlab specific. @enrichman could you confirm?

Looking back at the issue, we'd need to do some kind of pre-fetch to determine if there was an git instance there (and not just _something_ there) and i'm not sure that's possible

2022-10-18 13:15 UTC, enrichman commented
> The Git URL can be any URL that points to a publicly available git instance, so validation should only match that of a URL rather than something github/gitlab specific. @enrichman could you confirm?
> 
> Looking back at the issue, we'd need to do some kind of pre-fetch to determine if there was an git instance there (and not just _something_ there) and i'm not sure that's possible (in a simple UX flow)

Yes, I would expect this working also with Gitlab, and maybe in the future with private Github enterprise instances.
Is it working with Gitlab?

2022-10-18 13:20 UTC, richard-cox commented
> > The Git URL can be any URL that points to a publicly available git instance, so validation should only match that of a URL rather than something github/gitlab specific. @enrichman could you confirm?
> > Looking back at the issue, we'd need to do some kind of pre-fetch to determine if there was an git instance there (and not just _something_ there) and i'm not sure that's possible (in a simple UX flow)
> 
> Yes, I would expect this working also with Gitlab, and maybe in the future with private Github enterprise instances. Is it working with Gitlab?

@enrichman Would it be expected to work with non-github/gitlab urls though, as in, anything supported by `git clone`?

2022-10-18 13:32 UTC, enrichman commented
> > > The Git URL can be any URL that points to a publicly available git instance, so validation should only match that of a URL rather than something github/gitlab specific. @enrichman could you confirm?
> > > Looking back at the issue, we'd need to do some kind of pre-fetch to determine if there was an git instance there (and not just _something_ there) and i'm not sure that's possible (in a simple UX flow)
> > 
> > 
> > Yes, I would expect this working also with Gitlab, and maybe in the future with private Github enterprise instances. Is it working with Gitlab?
> 
> @enrichman Would it be expected to work with non-github/gitlab urls though, as in, anything supported by `git clone`?

I would say yes, but I'm not sure if this is too much of work. I haven't followed much the issue, so I'm not sure if it's something feasible or not.

2022-10-19 09:09 UTC, richard-cox commented
Ok, i think for this issue then we should just validate that the URL is in the correct format. We have another issue that should address how to recover from a failed app deploy step - https://github.com/epinio/ui/issues/49

2022-10-27 12:40 UTC, richard-cox requested changes
Following on from the PR conversation the Git Url validation should only validate if the URL is valid and not if it's a valid github/gitlab url. 

This doesn't quite resolve the original issue, but validating if a git instance is at the end of a url and that it supplies a valid point to checkout would be quite involved. 

There is an existing general issue that would help resolve the original issue's problem though https://github.com/epinio/ui/issues/49 will he

2022-11-28 16:47 UTC, richard-cox approved these changes

2022-11-28 16:47 UTC, richard-cox commented on pkg/epinio/components/application/AppSource.vue
> +          v-focus
At some point this needs to be added to the first input field of the other types as well

2022-11-29 09:39 UTC, merged