Edit labels and annotations.
rancher/dashboard pull request #7105
Opened 2022-10-06 14:12 UTC by Shavindra

### Summary
- #7094 

 

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-10-07 12:26 UTC, cnotv commented
@Shavindra could you please describe what was missing and required to be done? 
I've seen that was missing the `metadata`, the `WorkloadDeployments` name changed and something else, but this one I dont get it:

```
    if ( this.type === POD ) {
      return this.spec.initContainers;
    }
```

Should we maybe add a comment about why is this logic an exception?
Sorry to bother 😬

2022-10-07 12:40 UTC, cnotv requested changes
I am not able to save the creation while I created the comparison video.


https://user-images.githubusercontent.com/5009481/194555624-ac80d293-33dd-4f24-af33-68d20b591578.mov

2022-10-07 12:54 UTC, cnotv commented
Now it seems adding some extra stuff which I dont get.

<img width="1499" alt="Screenshot 2022-10-07 at 14 53 32" src="https://user-images.githubusercontent.com/5009481/194558464-cf7aeda4-065d-4e26-bec8-afe5bd4e6959.png">

2022-10-07 13:11 UTC, Shavindra commented
> Now it seems adding some extra stuff which I dont get.
That is expected because it's a system label.

2022-10-07 14:03 UTC, cnotv submitted a review, later dismissed
If system label are not a problem LGTM.

Please mind linters.

2022-10-10 08:33 UTC, cnotv requested changes

2022-10-10 08:33 UTC, cnotv commented on shell/edit/workload/index.vue
> +                    <LabeledInput v-model="allContainers[0].name" :mode="mode" :label="t('workload.container.containerName')" />
Should it not be `tab.name`?
Also why always the first one? If there's a valid reason, maybe we could write a comment.

2022-10-10 08:33 UTC, cnotv commented on shell/edit/workload/index.vue
> +                      v-model.trim="allContainers[0].image"
Same here as above.

2022-10-10 11:58 UTC, cnotv approved these changes
LGTM

2022-10-10 12:02 UTC, merged