Fix broken links to developer docs
rancher/dashboard pull request #7116
Opened 2022-10-06 20:39 UTC by rak-phillip

This fixes some broken links to developer docs in README.md

2022-10-06 20:51 UTC, rak-phillip commented
I'm wondering if it would make more sense to link to the docs located under https://rancher.github.io/dashboard/getting-started/concepts/ 🤔

2022-10-06 22:34 UTC, catherineluse commented
Docusaurus supports a feature to add an edit link to the bottom of each page that links to the source code on GitHub. Until that feature is enabled, I think we should link to both so that it's clear where to make edits.

2022-11-15 14:48 UTC, nwmac approved these changes

2022-11-15 16:07 UTC, catherineluse requested changes

2022-11-28 18:54 UTC, rak-phillip commented on README.md
> +For information on APIs, the layout of the codebase, Vuex stores, localization and more, see the [developer docs.](./docusaurus/docs)
The team had discussed directing all links in the root-level `README.md` to our hosted docs instead of github.

2022-11-28 19:08 UTC, nwmac approved these changes

2022-11-28 20:13 UTC, catherineluse approved these changes

2022-11-28 21:20 UTC, merged