Customisable links support
rancher/dashboard pull request #7131
Opened 2022-10-09 16:15 UTC by nwmac

TBD

2022-10-10 16:50 UTC, richard-cox requested changes
Tested a lot, including special deluxe mode, harvester standalone use case (CommunityLinks in support page) and some other weird edge cases. Apart from inline comments looks good

2022-10-11 07:51 UTC, nwmac commented on shell/config/home-links.js
> +import { DOCS_BASE } from '@shell/config/private-label';
Created https://github.com/rancher/dashboard/issues/7144 for this

2022-10-11 07:54 UTC, nwmac commented on shell/components/CommunityLinks.vue
> +        all.push(...this.links.custom);
Not sure about this - created https://github.com/rancher/dashboard/issues/7145 to revist

2022-10-11 07:56 UTC, nwmac commented on shell/pages/c/_cluster/settings/links.vue
> +    // TODO: NEED TO SUPPOT MODRE FOR THE DEFAULT LINKS CONTROL
The todo was done, so removed

2022-10-11 08:50 UTC, richard-cox approved these changes

2022-10-11 13:11 UTC, merged