[backport v2.6.9] NetworkPolicy PolicyRules checkbox and buttons overlap
rancher/dashboard pull request #7137
Opened 2022-10-10 16:45 UTC by cnotv

### Summary
Fixes #7115 
As in issue.

### Occurred changes and/or fixed issues
Removed unnecessary padding and margin.

### Technical notes summary
Added prop to the `Tabbed` component and pointed class for active property.

### Areas or cases that should be tested
- `NetworkPolicy`, `/c/local/explorer/networking.k8s.io.networkpolicy
- `Workload` creation

### Areas which could experience regressions
Based on what defined in the issue, no other view has nested tabs cases.

### Screenshot/Video
<img width="731" alt="Screenshot 2022-10-10 at 17 38 53" src="https://user-images.githubusercontent.com/5009481/194904925-cc8cff7a-f7fc-48de-802b-e1b56184cc4c.png">

<img width="584" alt="Screenshot 2022-10-10 at 17 39 32" src="https://user-images.githubusercontent.com/5009481/194904931-05dc8d99-d513-4784-a3c7-984047199b37.png">

![Screenshot 2022-10-06 at 16 35 41](https://user-images.githubusercontent.com/5009481/194342573-e77734d2-fd59-40f5-97db-ab90e1869dac.png)

![Screenshot 2022-10-06 at 16 35 44](https://user-images.githubusercontent.com/5009481/194342579-4dd18aad-d815-4829-b54e-eec92fefbf82.png)

![Screenshot 2022-10-06 at 16 37 57](https://user-images.githubusercontent.com/5009481/194342588-8d2eac89-752a-487b-82a6-b7049875baa0.png)

2022-10-10 21:39 UTC, cnotv commented
@neillsom the other PR has been merged https://github.com/rancher/dashboard/pull/7136

Requirement for reviewers is missing here for the release, not so sure if RegEx is possible.

2022-10-11 13:24 UTC, richard-cox requested changes
This isn't a return to how it was before, there's now a box shadow around the tab. It looks like this is the box shadow should be on other context of the tab (outside of the workload page / tab in tab)

Original 2.6.9
![image](https://user-images.githubusercontent.com/18697775/195102437-2809ff9d-0bef-4666-927a-4816b2cb8d58.png)

From PR
![image](https://user-images.githubusercontent.com/18697775/195102547-1c0414d0-2300-4b6b-be0c-0e39f04098ac.png)

2022-10-11 15:00 UTC, cnotv commented
Corrected shadow box, screenshot with the light theme 😅 
Good catch.

2022-10-11 17:28 UTC, richard-cox approved these changes

2022-10-11 19:17 UTC, merged