Remove last item from navigation filter onMouseDown
rancher/dashboard pull request #7310
Opened 2022-10-31 17:22 UTC by Shavindra

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2022-11-15 18:03 UTC, cnotv requested changes

2022-11-22 08:31 UTC, Shavindra commented on shell/components/nav/NamespaceFilter.vue
> +      if (this.value.length === 1) {
`@click="removeOption(ns, $event)"` already does that? 

then I have `if (this.value.length === 1)` which would clear the options only when `length === 1`

2022-11-22 15:39 UTC, cnotv commented on shell/components/nav/NamespaceFilter.vue
> +      if (this.value.length === 1) {
Look, I think the steps I take to reproduce the issue are correct.

https://user-images.githubusercontent.com/5009481/203356461-f000c424-c2bc-487a-8b09-d71eff672865.mov

2022-11-27 23:12 UTC, cnotv approved these changes
LGTM

2022-11-28 10:07 UTC, merged