Removed required from ApiGroup feild
rancher/dashboard pull request #7323
Opened 2022-11-03 08:40 UTC by bisht-richa

### Summary
Fixes #7084

Removed mandatory Asterix * sign on API Groups

### To test 
Try to create a role through Rancher >> Cluster Explorer >> RBAC >> Roles >> Create
The `API Groups` field should not have a mandatory Asterix * sign

2022-11-20 20:15 UTC, nwmac requested changes

2022-11-20 20:15 UTC, nwmac commented on shell/components/CruResource.vue
> +    test
@bisht-richa I don't think this should be here. You should self-review PRs once created just to check for this kind of thing.

2022-11-21 09:38 UTC, nwmac commented
@bisht-richa I've updated this PR, removed the test text and added code to replace the double quotes in the API group field

2022-12-07 17:08 UTC, Shavindra requested changes

2022-12-07 17:08 UTC, Shavindra commented on shell/components/auth/RoleDetailEdit.vue
> +
I think this need to be handled where the rules are actually set. Not before it just save? I think this might be in the model.

2022-12-08 12:08 UTC, Shavindra approved these changes
LGTM

2022-12-19 10:28 UTC, merged