Stop cluster config from jumping up and down when navigating between tabs
rancher/dashboard pull request #7350
Opened 2022-11-08 01:31 UTC by catherineluse

This PR adds a minimum height to the RKE2/K3s cluster config form to stop it from wiggling when tabs are clicked.
<img width="1461" alt="Screenshot 2022-11-07 at 6 30 35 PM" src="https://user-images.githubusercontent.com/20599230/200451722-65edff80-30b7-4514-a9ac-06eca9f899e7.png">

2022-11-11 09:32 UTC, torchiaf requested changes
Hi Catherine, I think your branch needs a rebase with the `master` branch. Apart from that LGTM.

2022-11-18 02:23 UTC, catherineluse commented
The PR seems blocked by a linting issue with an unrelated file
<img width="1371" alt="Screenshot 2022-11-17 at 7 22 14 PM" src="https://user-images.githubusercontent.com/20599230/202602145-c3a44917-3af3-4984-879c-af6395dbe088.png">

2022-11-18 17:46 UTC, cnotv commented
Rebase is required.

2022-11-21 08:46 UTC, torchiaf approved these changes

2022-11-21 14:55 UTC, merged