Minor log styling fix
rancher/dashboard pull request #7351
Opened 2022-11-08 02:22 UTC by catherineluse

This PR addresses https://github.com/rancher/dashboard/issues/4950 by making a minor CSS fix.

To test this PR,

1. I created a Deployment named `test` of a sample application that has the same Spring Boot logs as the original issue. I used this container image that I found by googling: `springio/gs-spring-boot-docker:latest`
2. Go to the Deployment detail page for `test`
3. On the Pods tab, go to a pod and click the *⋮ > View Logs*
4. Confirm that the "Spring Boot" is formatted properly

Before:

<img width="962" alt="Screenshot 2022-11-07 at 7 16 28 PM" src="https://user-images.githubusercontent.com/20599230/200458832-03b42eea-0c06-4cc8-89b1-941fe397976b.png">

After:

<img width="936" alt="Screenshot 2022-11-07 at 7 18 48 PM" src="https://user-images.githubusercontent.com/20599230/200458946-e5e29830-524a-4b83-b78b-829ac969e465.png">

2022-11-10 07:52 UTC, votdev approved these changes
Tested & LGTM

2022-11-10 07:59 UTC, votdev requested changes

2022-11-10 07:59 UTC, votdev commented on shell/components/nav/WindowManager/ContainerLogs.vue
> +      white-space: pre;
I think this should be
```suggestion
      white-space: pre-wrap;
```

2022-11-11 04:25 UTC, catherineluse commented on shell/components/nav/WindowManager/ContainerLogs.vue
> +      white-space: pre;
updated

2022-11-11 09:57 UTC, votdev requested changes
This [code](https://github.com/rancher/dashboard/blob/740bc0fcc02204bc9050da00a7c9d2f526933ce4/shell/components/nav/WindowManager/ContainerLogs.vue#L605) must be kept
```
    .msg {
      white-space: pre;
```
otherwise this happens
![Peek 2022-11-11 10-56](https://user-images.githubusercontent.com/1897962/201315670-de5beb11-74f2-45f3-90cc-f7bf35aa87fd.gif)

2022-11-13 22:04 UTC, votdev approved these changes

2022-11-17 23:03 UTC, merged