Refactors sockets and moves reconnect logic and error handling into it.
rancher/dashboard pull request #7459
Opened 2022-11-15 16:32 UTC by Sean-McQ

WIP for now, still validating edge cases. Feel free to pull down and test, several ToDo's still in place.

2022-11-22 01:53 UTC, catherineluse commented
@Sean-McQ I'd like to review this PR, but I have found it difficult to reproduce the original issue using Colleen's steps. Do you have any tips to make it easier to repro the original issue?

2022-11-25 09:58 UTC, richard-cox requested changes
Haven't done a deep dive in to this yet, but making `shell/utils/socket.js` steve/norman specific breaks the other places it's used (epinio, harvester, streaming workload logs, shell to deployment). Easiest place to see is Workload list --> Deployment action menu --> Execute Shell

2022-11-28 15:14 UTC, Sean-McQ commented
> Haven't done a deep dive in to this yet, but making `shell/utils/socket.js` steve/norman specific breaks the other places it's used (epinio, harvester, streaming workload logs, shell to deployment). Easiest place to see is Workload list --> Deployment action menu --> Execute Shell

2022-11-28 15:18 UTC, Sean-McQ commented
For the most part, Steve/Norman are pretty fundamental to the way we use websockets so I still think it makes sense for some of their requirements to be baked into them but I do see where/how that breaks shells atm. Gonna work on a fix for that and put in an update here.

2022-11-30 03:16 UTC, Sean-McQ commented
As requested, new changes to the socket have been moved to a new class derived from the original socket class (ResourceWatcher) and the ResourceWatcher is in use by the subscribe Vuex methods.

2022-11-30 18:31 UTC, richard-cox requested changes
Haven't totally finished reviewing, but hit a functionally blocking bug (see comment in `resourceWatcher` `send(data) {` and will pick up the rest tomorrow

2022-12-19 11:53 UTC, richard-cox commented
Closing in favour of https://github.com/rancher/dashboard/pull/7719 / https://github.com/rancher/dashboard/pull/7671. There'll be another PR up that covers moving rancher socket subscription management into a worker

2022-12-19 11:53 UTC, closed without merging