Improve UX for cluster scoped private registry config
rancher/dashboard pull request #7508
Opened 2022-11-20 00:35 UTC by catherineluse

Addresses these issues:

- https://github.com/rancher/dashboard/issues/6919
- https://github.com/rancher/dashboard/issues/5146
- https://github.com/rancher/dashboard/issues/6875

Default view: 

<img width="1146" alt="Screenshot 2022-11-19 at 5 33 45 PM" src="https://user-images.githubusercontent.com/20599230/202877063-f7793dae-cf94-4cf6-b265-f53d06a94b76.png">

If cluster registry is enabled:
<img width="1144" alt="Screenshot 2022-11-19 at 5 34 41 PM" src="https://user-images.githubusercontent.com/20599230/202877076-95501447-1aca-48f7-afc9-a95214964a25.png">

If advanced options are expanded (docs link changes to K3s docs if a K3s version is selected):

<img width="894" alt="Screenshot 2022-11-19 at 5 35 15 PM" src="https://user-images.githubusercontent.com/20599230/202877099-caf067dc-3474-4594-93d1-91b1402c81df.png">

2022-11-21 20:48 UTC, catherineluse commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +      showCustomRegistryAdvancedInput: false,
the new values are:
```
showCustomRegistryInput:         false,
      showCustomRegistryAdvancedInput: false,
```

2022-11-22 22:15 UTC, mantis-toboggan-md requested changes
I have a couple suggestions for the SelectOrCreateAuthSecret component, but I know that is pre-existing code so if you want me to file a separate issue let me know.
I think it'd be nice if the style aligned more with the namespace dropdown:
![Screen Shot 2022-11-22 at 12 40 05 PM](https://user-images.githubusercontent.com/42977925/203406667-d374c0e5-6d76-4565-af50-3f2a5ad463e4.png)
![Screen Shot 2022-11-22 at 12 41 47 PM](https://user-images.githubusercontent.com/42977925/203406671-4863939b-0f22-49a9-b4e2-7d5f44aa7413.png)

My other issue with the component is the way it loads data (all secrets, sometimes all norman cloud creds too). It's using the `Loading` component, which blocks the user from interacting with the entire page until the data needed for a single dropdown is ready. The experience is a little nicer if the LabeledSelect `loading` prop is used instead (ie add`:loading="$fetchState.pending"`)

https://user-images.githubusercontent.com/42977925/203412965-be4e73d6-d5b9-4bb8-a99e-026828832dad.mov

There is a minor style issue with the 'x' button for configs:
![Screen Shot 2022-11-22 at 12 43 48 PM](https://user-images.githubusercontent.com/42977925/203407068-d60d7389-1929-4bd0-b515-6517efb8044f.png)

I also noticed that when I create a cluster with a registry auth config defined, then edit the cluster to remove that config, the change isn't saved.

2022-12-04 22:46 UTC, catherineluse commented
I've made these changes:

- Changed styling of the menu to create or select secret to be consistent with the dropdown for creating or selecting a namespace.
- Used loading prop instead of loading component.
- Fixed X button size/overlap issue.
- Removed "configs section" - it now says "Define the TLS and credential configuration for each registry hostname and mirror." This language is updated to convey that it includes the simple basic auth config in the list - you should ALL registry credential secrets and TLS options there, including the basic one. (Basically, clicking advanced options is revealing everything as it is in YAML.)
- When you delete an auth config, the change is now saved.

2022-12-07 18:39 UTC, mantis-toboggan-md approved these changes
LGTM

2022-12-07 20:59 UTC, mantis-toboggan-md commented
I just noticed that the style change to ArrayListGrouped looks off elsewhere in the UI:
![Screen Shot 2022-12-07 at 1 57 09 PM](https://user-images.githubusercontent.com/42977925/206294248-3fd6ac79-6100-4117-858a-04c8e83fb4d2.png)

2022-12-07 21:20 UTC, mantis-toboggan-md requested changes

2022-12-07 21:20 UTC, mantis-toboggan-md commented on shell/components/form/ArrayListGrouped.vue
> +        margin-right: -2.25em;
I think since this component is used full-width elsewhere it might be better to do something like add more padding to `.info-box`

2022-12-07 21:20 UTC, mantis-toboggan-md commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +                class="advanced"
Sorry I didn't notice this on my first review, but the contents of this tab don't fill the full width of the section like the other tabs' inputs do. Adding `col span-12` here and changing line 2224 to `span-12` would make this tab's content full-width.
![Screen Shot 2022-12-07 at 2 16 48 PM](https://user-images.githubusercontent.com/42977925/206298341-3d62f9fc-3f5f-4e8a-9d3e-3e34ff1a23f3.png)

2022-12-08 21:56 UTC, catherineluse commented
I've changed the columns to full width and adjusted the padding for the X button:

![Screenshot 2022-12-08 at 2 55 00 PM](https://user-images.githubusercontent.com/20599230/206575806-7549013b-8698-4da8-997e-846e2acf827c.png)

Here's the padding in the Ingress rules context:

![Screenshot 2022-12-08 at 2 51 20 PM](https://user-images.githubusercontent.com/20599230/206575878-d1743eb1-e9d0-4e41-a6cb-f9d74de22176.png)

2022-12-08 22:24 UTC, mantis-toboggan-md approved these changes

2022-12-08 22:26 UTC, merged