Add rancher dashboard version to "About" page
rancher/dashboard pull request #7516
Opened 2022-11-22 09:28 UTC by aalves08

Fixes #4217 

- Add rancher dashboard version to "About" page
- Replace copy of "backend version" link to just "About"
- Remove unused code from `TopLevelMenu` component

2022-11-25 11:48 UTC, richard-cox requested changes
Once this merges (and the drone build completes) we should validate that the dashboard version displays something sensible

2022-11-25 11:48 UTC, richard-cox commented on package.json
> +    "mem-dev": "source ./scripts/version && node --max-old-space-size=8192 ./node_modules/.bin/nuxt dev",
This needs to be applied to other dev like targets

2022-11-25 11:48 UTC, richard-cox commented on scripts/version
> +    export DASHBOARD_VERSION=$GIT_TAG
Thought about this for a while. I think we should rename or splash comments everywhere. It needs to be clear that `VERSION` is a more computer readable interpretation and `DASHBOARD_VERSION` is a more human readable one that can be used to display in the dashboard

2022-11-25 11:48 UTC, richard-cox commented on shell/nuxt.config.js
> +const dashboardVersion = process.env.DASHBOARD_VERSION;
Same concept here, we need to ensure people understand the difference between version and dashboard version. I think though we could be brave and remove `version` and `commit` from here.

2022-12-08 14:57 UTC, richard-cox requested changes
One minor change requested.

You might need to add a note for QA to the issue, to test in a `-head` build and also a tagged (i.e. release candidate) build

2022-12-08 14:57 UTC, richard-cox commented on scripts/version
> +    export DASHBOARD_VERSION=$GIT_TAG
good comments, but also needs to apply to nuxt.config.js `version` and `dashboardVersion`

2022-12-08 14:57 UTC, richard-cox commented on shell/nuxt.config.js
> +const dashboardVersion = process.env.DASHBOARD_VERSION;
Agree, they can both go

2022-12-12 14:44 UTC, aalves08 commented
@richard-cox I've deleted the `version` on `shell/nuxt.config.js` and I've added the comment there. Let me know if I am missing something 🙏

2022-12-14 09:48 UTC, merged