Move storybook
rancher/dashboard pull request #7611
Opened 2022-12-02 13:47 UTC by nwmac

Fixes #7329 

This PR moves the `.storybook` and `stories` folders under a new top-level `storybook` folder.

The new `storybook` folder contains its own `package.json` with `nohoist` set - so Storybook dependencies will not interfere with the top-level `node_modules` folder.

You can now developer dashboard and storybook easily from a checkout.

Docs and build scripts have been updated

2022-12-02 16:18 UTC, cnotv requested changes
Looks good, thank you for taking care of it. Only concern to me are the part related to the installation as you can read in the comment.

PS: Do not forget to rebase the incoming merges.

2022-12-06 09:38 UTC, nwmac commented on package.json
> +    "storybook": "cat storybook/moved.txt",
I'm okay with that - done

2022-12-06 09:38 UTC, nwmac commented on package.json
> +    "storybook": "cat storybook/moved.txt",
Done

2022-12-07 17:44 UTC, nwmac commented
Should all be good now @cnotv

2022-12-07 18:07 UTC, merged