Allow user to select Fleet repo protocol select.
rancher/dashboard pull request #7648
Opened 2022-12-08 08:12 UTC by Shavindra

### Summary
Fixes rancher/dashboard#7518

### Occurred changes and/or fixed issues
Requirement changed to display a banner instead.

### Technical notes summary
- Continuous Delivery > Git Repos > Add repository button on top right
- Banner should be displayed.

### Areas or cases that should be tested
![image](https://user-images.githubusercontent.com/1387263/217570814-a97e699b-666e-4020-8abe-eaf31c2738f2.png)

2022-12-19 10:31 UTC, richard-cox commented
@Shavindra The PR template isn't filled in, lint is failing and there's no reviewer requested. Can you update?

2022-12-20 13:14 UTC, kwwii commented
We should remove the "://" from the protocol label and also write them with all caps (HTTPS and SSH).

2022-12-20 13:15 UTC, kwwii commented
+1 if you can autodetect the type from the text entered by the user.

2023-01-18 11:09 UTC, nwmac requested changes

2023-01-18 11:09 UTC, nwmac commented on shell/assets/translations/en-us.yaml
> +        ssh: e.g. git@github.com:rancher/dashboard.git
Use the same fleet-examples repo, but with ssh protocol

2023-01-23 08:25 UTC, nwmac commented
@Shavindra You should mark the conversations as resolved when addressed and re-request a review when ready.

2023-01-23 08:35 UTC, nwmac commented
@Shavindra @kwwii I don't know if this is an improvement - we could have 'just' added a banner or tip saying that you can use either an https or ssh URL - we don't auto-detect the protocol with this change, so you can't just paste in a `git@` URL and have the protocol change to ssh - so you now have two steps.

I thought some of the auth options only applied to either https or ssh - but we don't seem to do anything to update those based on which protocol you select.

I think it would be better just to adda line saying https or ssh URLs can be used.

2023-01-23 08:36 UTC, nwmac requested changes
See comment

2023-02-10 08:56 UTC, bisht-richa approved these changes
LGTM

2023-02-10 09:26 UTC, nwmac approved these changes

2023-02-10 09:31 UTC, merged