Fix plugin navigation
rancher/dashboard pull request #7731
Opened 2022-12-16 11:04 UTC by cogor

Described in Issue #7730

2022-12-16 14:19 UTC, cnotv commented on shell/components/Tabbed/index.vue
> +      default: false,
You have to update all the use cases of Tabbed component if you want to revert this key. 
The alternative is that you set it true for the case you want to apply it.

2022-12-16 14:19 UTC, cnotv requested changes
Mind the E2E outcome.

2022-12-19 17:26 UTC, richard-cox requested changes
There should be a way to fix this without updating all references.

To help us with that we need to reproduce the bug (see comments in https://github.com/rancher/dashboard/issues/7730)

2022-12-20 18:41 UTC, richard-cox commented
Closing as per conversation in https://github.com/rancher/dashboard/issues/7730

2022-12-20 18:41 UTC, closed without merging