Fix multi select styling
rancher/dashboard pull request #7843
Opened 2023-01-05 10:07 UTC by bashofmann

### Summary
Fix multi select styling so that the form field expands if not all items fit into a single line anymore.

Fixes #7842

### Occurred changes and/or fixed issues
Instead of fixing the height of the select form field, the form field now has a `min-height` which allows the field to expand if necessary.

### Areas or cases that should be tested
Create a Logging ClusterFlow and pick a lot of containers or namespaces.

### Areas which could experience regressions
Form fields that use the Select component.

### Screenshot/Video
Before

![Bildschirm­foto 2023-01-05 um 10 53 22](https://user-images.githubusercontent.com/243056/210754536-765f2c53-cccf-40ee-bdf7-c13b47b9c788.png)

After

![Bildschirm­foto 2023-01-05 um 10 54 15](https://user-images.githubusercontent.com/243056/210754566-c1515468-56b6-4259-8384-ea4ff6d756b1.png)

2023-01-05 10:25 UTC, richard-cox commented
@torchiaf  Could you give this one a review, including a quick check in other places where the same component/style is used?

2023-01-05 10:25 UTC, torchiaf commented
> @torchiaf Could you give this one a review, including a quick check in other places where the same component/style is used?

Sure thing!

2023-01-05 12:21 UTC, torchiaf requested changes
I made a check where the `Select` component is used.

Unfortunately the fix breaks the layout of `ApplicationLogs` component. IMO We should investigate in deep if there are cases like this, because the select is used almost everywhere. 

before:
![image](https://user-images.githubusercontent.com/26394656/210779285-4fcb050b-2ade-44f5-9f22-c9e0bfd085af.png)

after:
![image](https://user-images.githubusercontent.com/26394656/210779116-6aa5a79b-441f-430f-bd52-33f0d883bd9a.png)


Other minor issue: statement `.unlabeled-select:not(.in-input)` is duplicated, we should remove one of them.

2023-01-05 12:52 UTC, bashofmann commented
I removed the duplication.

The ApplicationLog component is interesting. The height for the Select in this Component is overwritten to 30px, but of course min-height is not. I'll fix this and search for other places where the height is changed.

2023-01-05 13:34 UTC, bashofmann commented
The only places that I could find where the height of the select component is reduced are: ContainerLogs, ContainerShell, ApplicationLogs and ApplicationShell.

I fixed it there and also reduced min-height.

2023-01-12 19:28 UTC, torchiaf approved these changes
LGTM

2023-01-12 23:01 UTC, merged