Improve presentation of VM Built-in Extension
rancher/dashboard pull request #8004
Opened 2023-01-23 17:48 UTC by nwmac

Fixes #7995 

- Fixes the icon overlap issue
- Adds support for built-in extensions to override the display label
- Fixed info panel to use the display label not name
- Improved display of version number for built-in plugins to be consistent with others
- Updated Harvester Manager extension to have better name, description and icon

Extensions view:
![image](https://user-images.githubusercontent.com/1955897/214112037-69dba36d-6867-446b-a96c-a5a5c2de23e1.png)

Info panel:
![image](https://user-images.githubusercontent.com/1955897/214111938-c7e643ba-2665-4a34-b5cc-511ab8e88762.png)

2023-01-25 21:25 UTC, mantis-toboggan-md requested changes
This isn't part of the original issue but I'm complaining about it here anyway. I noticed that the extensions page switches to the 'available' tab if no extensions are installed, but that check appears to ignore the harvester manager plugin. I think it should default to the 'installed' tab if there are any plugins listed there regardless of whether they're built in or installed.

Aside from that and my comment about the description this PR looks good.

2023-01-25 21:25 UTC, mantis-toboggan-md commented on pkg/harvester-manager/package.json
> +  "description": "Provides Virtualization Management feature in Rancher Manager",
There should probably be a "the" before Virtualization

2023-02-08 01:44 UTC, krumware commented
Just a quick note to bring attention if relevant, harvester-manager imports currently break the extension starter
https://github.com/rancher/dashboard/issues/8008

2023-02-09 16:17 UTC, nwmac commented
@mantis-toboggan-md Fixed description - I'll create an issue for considering built-in extensions when making initial tab choice.

2023-02-09 16:19 UTC, mantis-toboggan-md approved these changes

2023-02-09 20:15 UTC, nwmac commented
@krumware Thanks - a fix for this is imminent

2023-02-09 20:15 UTC, merged