Add Outscale CSI into rancher UI
rancher/dashboard pull request #8172
Opened 2023-02-14 16:34 UTC by outscale-mdr

### Summary
This PR is to add [Outscale CSI](https://github.com/outscale/osc-bsu-csi-driver) into Rancher UI.

### Screenshot/Video

Preview:
<img width="969" alt="Capture d’écran 2023-02-14 à 17 32 57" src="https://user-images.githubusercontent.com/91073311/218799199-bbe65475-b512-43e7-8d11-7a2bf7ade587.png">
Proof:
<img width="932" alt="Capture d’écran 2023-02-14 à 17 32 46" src="https://user-images.githubusercontent.com/91073311/218799209-08b151e5-7c74-4448-bd02-36ef39c25f4a.png">

2023-04-19 14:22 UTC, richard-cox requested changes

2023-04-19 14:22 UTC, richard-cox commented on shell/edit/storage.k8s.io.storageclass/provisioners/bsu.csi.outscale.com.vue
> +      set(value) {
There's no `get` here, so when it's used in the `v-model` below there's lots of errors (on load and use)

2023-04-20 15:14 UTC, richard-cox commented on shell/models/storage.k8s.io.storageclass.js
> +    supported: true,
sorry, additional comment, supported will need to be removed as per https://www.suse.com/support/kb/doc/?id=000020481

Unsupported storage classes can be made visible by enabling the `unsupported-storage-drivers` Feature Flag (burger menu --> Global Setting --> Feautre Flags)

2023-04-21 11:32 UTC, outscale-mdr commented
Hi @richard-cox,

Thank you for the feedback, I will make the changes as soon as possible !

2023-05-09 10:53 UTC, richard-cox commented
@outscale-mdr Just an FYI, the cut off date for the next feature release is very roughly in a week

2023-05-15 13:29 UTC, outscale-mdr commented
Hello @richard-cox,

Sorry for the silence, I was off a long time. Here are the changes. if it is not still possible to include it in the next release, the one after is fine.

Thank you !

2023-05-15 14:40 UTC, richard-cox requested changes
I hit some issues with the LabelSelect that used to selec the secret key. Below should be the fix, can you confirm?

```
- shell/edit/storage.k8s.io.storageclass/provisioners/bsu.csi.outscale.com.vue -
index 6e87bd136..dc1d06f86 100644
@@ -24,7 +24,10 @@ export default {
   async fetch() {
     const secrets = await this.$store.dispatch('cluster/findAll', { type: SECRET });
 
-    this.secrets = secrets.filter(s => s._type === TYPES.OPAQUE).map(s => s.id).sort();
+    this.secrets = secrets.filter(s => s._type === TYPES.OPAQUE).map(s => ({
+      label: s.id,
+      value: s.id
+    })).sort((a, b) => a.label.localeCompare(b.label));
   },
   data() {
     const canListStorageClasses = this.$store.getters['cluster/canList'](SECRET);
@@ -93,7 +96,10 @@ export default {
     },
     keySecrets: {
       get() {
-        return `${ this.value.parameters['csi.storage.k8s.io/node-stage-secret-namespace'] }/${ this.value.parameters['csi.storage.k8s.io/node-stage-secret-name'] }`;
+        const ns = this.value.parameters['csi.storage.k8s.io/node-stage-secret-namespace'];
+        const name = this.value.parameters['csi.storage.k8s.io/node-stage-secret-name'];
+
+        return ns && name ? `${ ns }/${ name }` : this.secrets[0];
       },
       set(value) {
         const secret = value.split('/', 2);
@@ -143,7 +149,7 @@ export default {
           :options="encryptionOptions"
         />
         <LabeledSelect
-          v-if="canListStorageClasses && value.parameters.encrypted === 'true'"
+          v-if="canListStorageClasses && value.parameters.encrypted === 'true' && secrets.length"
           v-model="keySecrets"
           :options="secrets"
           :label="t('storageClass.outscale-bsu.encryption.secret')"
```

I also couldn't create a secret, regardless of what was in the form.  PostS to `k8s/clusters/<CLUSTER>/v1/storage.k8s.io.storageclasses` always failed with  400 `StorageClass in version \"v1\" cannot be handled as a StorageClass: json: cannot unmarshal number into Go struct field StorageClass.parameters of type string`

2023-05-16 14:31 UTC, outscale-mdr commented
Hello @richard-cox, 

Could we pause this PR to next release, I do not have time to dig into what is going on ?
In a few weeks, I will be able to have more time to focus on this PR.

Sorry about that

2023-05-16 14:36 UTC, richard-cox commented
No problem, just let us know if you have any questions

2023-06-28 12:45 UTC, richard-cox commented
@outscale-mdr Just an fyi, the timeframe for the next release is shorter than usual. There's about 3-4 weeks before we approach feature complete.

2024-07-01 09:40 UTC, richard-cox commented
Closing due to inactivity. Please re-open when ready to update

2024-07-01 09:40 UTC, closed without merging