[2.7.2] Handle nodeGroups undefined for  imported EKS cluster
rancher/dashboard pull request #8196
Opened 2023-02-17 10:35 UTC by Shavindra

### Summary
Forward port of rancher/dashboard#8222 

### Occurred changes and/or fixed issues
Handle `eksNodeGroups` being null / undefined.

### Areas or cases that should be tested
1. Create an EKS cluster in the AWS console, kube version 1.23/1.24.
2. Import this cluster into Rancher.
3. Go to the cluster information page.

### Screenshot/Video

2023-02-21 11:28 UTC, richard-cox requested changes
I'm trying to bring up an EKS cluster, can you confirm how you tested this?

2023-02-21 16:51 UTC, gaktive commented
Let's make sure we merge this into the right branch since this is for 2.6.11 so it's not just `master`.

2023-02-21 17:48 UTC, nwmac approved these changes

2023-02-22 12:57 UTC, nwmac approved these changes

2023-02-22 15:41 UTC, merged