Fix Grafana URLs in local cluster for new monitoring version
rancher/dashboard pull request #8347
Opened 2023-03-06 09:14 UTC by bashofmann

### Summary
Fixes https://github.com/rancher/dashboard/issues/8346

### Occurred changes and/or fixed issues
With the new version of Rancher-Monitoring, the embedded Grafana dashboards and links in the local cluster do not work anymore, but return a 404 from Grafana.

In all other clusters the links are correct.

This changes an exception in the creation of these links for the local cluster, which is not needed anymore in the new monitoring version >=102.0.0+up40.1.2.

### Areas or cases that should be tested
Embedded Grafana dashboards and Grafana links in the local cluster.

### Areas which could experience regressions
* Cluster Overview page
* Workload detail page
* Pod detail page
* Node detail page
* Grafana link on Monitoring detail page

2023-03-06 15:55 UTC, bashofmann commented
This also fixes project monitoring dashboards in the local cluster.
![Bildschirm­foto 2023-03-06 um 16 54 42](https://user-images.githubusercontent.com/243056/223162399-0f0d99c3-0095-42c3-8423-dd83d4e4ae90.png)

2023-03-07 10:54 UTC, richard-cox commented
@bashofmann Similar to the other PR, i've updated this and issue to 2.7 Q2. I think we need a fix for 2.7.2 as well, can you create the backported issue and PR?

In terms of the fix, we need to be able to support previous versions of the monitoring chart as well. Can you confirm the fix works for both old and new charts?

2023-03-07 12:51 UTC, bashofmann commented
@richard-cox Unfortunately, the old URL only works with the old version and the new one only with the new version :-(. I could check which version is installed there, but this looked a bit more complicated. I'll try to think about this a bit more, maybe there's something simpler. Do you have any idea of the top of your head?

2023-03-08 14:57 UTC, richard-cox commented
@bashofmann I've created https://github.com/rancher/dashboard/issues/8380 to backport the fix to 2.7.2. We're on a pretty tight deadline there.

To check which version of monitoring is installed you should be able to grab the specific installed app. This ONLY works if the user cannot change the namespace at install time (can't check out the moment, i haven't got a system that hasn't got monitoring installed, or previously installed)

So something like....
```
   const res = await this.$store.dispatch(`cluster/request`, { type: CATALOG.APP, id: 'cattle-monitoring-system/rancher-monitoring' });
    const currentVersion = res?.currentVersion 
```
You can use shell/utils/version.js `compare` to check if the currentVersion is before `102.0.0+up40.1.2`

2023-03-08 16:35 UTC, richard-cox requested changes
No comments on top of those in the PR, just aligning PR state with them

2023-03-09 16:59 UTC, bashofmann commented
@richard-cox I added the version compare in all places and also wrote a test to check if the comparison works correctly.

2023-04-18 09:43 UTC, richard-cox approved these changes

2023-04-18 09:44 UTC, merged