Added check box for truncate Hostnames
rancher/dashboard pull request #8397
Opened 2023-03-10 11:15 UTC by bisht-richa

### Summary
Fixes #8223

Checkbox added to the right of 'NodePort Service Port Range' in the 'Networking' tab for hostnames Truncate

### How to test
> Go to Cluster management > create > select DO 

> In Cluster Configuration section > click 'Networking' tab 

> It should have a check box with a label for hostnames Truncate

2023-03-22 09:44 UTC, nwmac commented
@bisht-richa Backend will add a new param per machine pool named `instanceNameLimit` to support this.

We are only allowing this to be set once per cluster, rather than per machine pool - so you will need to update this PR to add the above field to each machine pool if the user checks the box. It should be set to `15 and remove it from each pool if not.

For edit, you will need to look at each machine pool and see if the value is set, if it is set on any pool, then I would translate that to the checkbox being checked.

Backend PR for reference: https://github.com/rancher/rancher/compare/release/v2.7...jakefhyde:rancher:15-character-limit#diff-e05181e81036cad4014bb4843ea91837fa7dd238dc3434bc4fcc598c56db6428R31

2023-03-24 09:13 UTC, kwwii commented
Does this mean that we want to put the checkbox back into the Networking tab of the cluster creation UI?

![Screenshot 2023-03-24 at 10 12 18](https://user-images.githubusercontent.com/617368/227476049-4605e725-a67a-45af-a398-4f8ee0509ccb.png)

2023-03-31 14:30 UTC, Oats87 commented
@bisht-richa @nwmac the design for this has not been finalized, has it?

I just gave a preliminary review to the design document and notably we'll be making some pretty major changes to what we expect. Notably, the backend will allow the hostname limit to be something > 6 characters, and we'll provide the ability to set a cluster-wide default on `hostnameLimit` and the corresponding other field. The field names have not yet been finalized either.

2023-04-11 10:29 UTC, nwmac commented
@bisht-richa I think we can be unblocked now on the backend.

For the cluster-level setting, the setting will be `machinePoolDefaults.hostnameLengthLimit` - this will be the one that we need to set to 15, if the checkbox is checked.

Each machine pool can also have a `hostnameLengthLimit` field set - we aren't setting this, but if it is set, we will show a banner.

2023-04-11 10:30 UTC, nwmac commented on shell/edit/provisioning.cattle.io.cluster/MachinePool.vue
> +      v-if="value.pool.instanceNameLimit"
`instanceNameLimit` should now be `hostnameLengthLimit`

2023-04-11 10:33 UTC, nwmac commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +      if (this.truncateHostnames) {
This is incorrect - we no longer have to set on each pool.

We should now be setting `machinePoolDefaults.hostnameLengthLimit` on the cluster.

Note that `machinePoolDefaults` may not exist, so we need to add that object first.

if truncation not set, we should remove the `machinePoolDefaults` object if it is empty

2023-04-11 10:34 UTC, nwmac requested changes
@bisht-richa Can you update this - field names are now updated.

The behaviour needs updating to set this on the cluster, not the individual pools.

2023-04-11 10:34 UTC, nwmac commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +          out.filter((pool) => {
We should be picking this up from the cluster, not the pools

2023-04-14 08:46 UTC, nwmac approved these changes

2023-04-18 10:50 UTC, merged

2023-04-18 11:35 UTC, bisht-richa commented
@nwmac I will revert it.

2023-05-03 19:02 UTC, gaktive commented
Backend changes have made it now so we can ...unrevert.