Custom chart UIs show PSP switch on Kubernetes v1.25
rancher/dashboard pull request #8505
Opened 2023-03-23 13:38 UTC by cnotv

### Summary
Fixes #8434

### Occurred changes and/or fixed issues
PSP checkbox to be displayed if K8S < 1.25 or PSP is already enabled.
This is applied for the charts:
- OPA Gatekeeper
- Istio
- Logging
- Monitoring
- Rancher Backup

### Technical notes summary
- Moved markup within the component to avoid empty spaces
- Allowed to pass title for areas which require one
- Passed cluster object to parse version
- Extended tests

### Areas or cases that should be tested
All the charts above for clusters with K3/RKE2 and K8S < v1.25 or >= 1.25 and PSP disabled/enabled

### Areas which could experience regressions
Same as above.

### Screenshot/Video

2023-03-24 17:19 UTC, cnotv commented
@mantis-toboggan-md I have added the logic, tests, description and videos also for the standard charts.

2023-03-24 22:11 UTC, mantis-toboggan-md requested changes
The functionality of the pr looks good, I just had a question about how the current kubernetes version is determined

2023-03-24 22:11 UTC, mantis-toboggan-md commented on shell/components/ChartPsp.vue
> +      const clusterVersion = this.cluster?.metadata?.annotations?.['management.cattle.io/current-cluster-controllers-version'] || '';
This looks like a new way of getting the k8s version. Could the mgmt cluster `kubernetesVersion` getter be used here? eg const `clusterVersion = cluster.kubernetesVersion`

2023-03-27 15:56 UTC, mantis-toboggan-md approved these changes
LGTM

2023-03-27 16:02 UTC, merged