Changes to support custom node driver UI extensions
rancher/dashboard pull request #8735
Opened 2023-04-25 13:16 UTC by nwmac

This PR makes a few small changes, to better support custom node driver UI extensions.

Details TBC

2023-04-28 12:35 UTC, richard-cox requested changes
- Nav to create page for DO instance, add more than one pool, unselected pools show validation warning (red exclamation next to pool name in the tabs). 
- In `master`, it's impossible to invalidate the page (disable create button) due to machine pool config, even with absolute junk (remove all roles from all pools, deleting all pools, removing required fields, etc). Will create an issue

2023-04-28 12:35 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/MachinePool.vue
> +      :busy="busy"
disabled/busy should also apply to the `AdvancedSection` input fields below

2023-04-28 12:35 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +    // Track Machine Pool validation status
jsdoc

2023-05-11 08:08 UTC, nwmac commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +    // Only for extensions - extension can register a 'false' cloud credential to indicate that a cloud credential is not needed
Done

2023-05-11 08:09 UTC, nwmac commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +        uid:    name,
Will change to id

2023-05-11 08:14 UTC, nwmac commented on shell/edit/provisioning.cattle.io.cluster/rke2.vue
> +              :error="!machinePoolValidation[obj.uid]"
Fixed by defaulting new machine pools to be valid

2023-05-11 17:26 UTC, richard-cox requested changes
Tested DO (creating, viewing, editing, etc) and with a few workarounds for the merge issues (?) everything worked fine. Visually checked out the other changes and they look fine

2023-05-11 17:26 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/MachinePool.vue
> +    modeWithBusy() {
Not used anymore

2023-05-23 16:57 UTC, richard-cox approved these changes

2023-05-25 13:42 UTC, richard-cox approved these changes

2023-05-25 14:37 UTC, merged