Removed hasClass method
rancher/dashboard pull request #8752
Opened 2023-04-27 10:53 UTC by bisht-richa

After merging master 'hasClass` method was breaking UI. This PR is to fix it when you select rows in a table by pressing 'shift+j' or 'shift+k

2023-04-27 11:10 UTC, richard-cox requested changes
Where was this failing?

For cleaner code you can use 

```
if (row?.hasClass('row-selected')) {
```

2023-04-27 11:36 UTC, bisht-richa commented
> Where was this failing?
> 
> For cleaner code you can use
> 
> ```
> if (row?.hasClass('row-selected')) {
> ```



> Where was this failing?
> 
> For cleaner code you can use
> 
> ```
> if (row?.hasClass('row-selected')) {
> ```

@richard-cox in master after updating it.

2023-04-27 11:38 UTC, richard-cox commented
> @richard-cox in master after updating it.

Where in the dashboard? Is there a specific list or location of the click?

2023-04-27 11:53 UTC, richard-cox submitted a review, later dismissed

2023-04-28 12:01 UTC, richard-cox approved these changes

2023-04-28 12:02 UTC, merged