minor updates for extensions
rancher/dashboard pull request #8792
Opened 2023-05-04 15:26 UTC by aalves08

- docs minor update 
- add gitignore file to creator npm package

2023-05-04 19:46 UTC, jordojordo requested changes

2023-05-04 19:46 UTC, jordojordo commented on shell/creators/app/files/.gitignore
There's a lot in here that I don't think we should ignoring automatically. Maybe we should only ignore leftover files that are generated from developing/building extensions and let the user decide for further integrations.

2023-05-05 07:44 UTC, aalves08 commented on shell/creators/app/files/.gitignore
I've lightened it up quite a bit. I think the remaining items are "industry standards" and should be kept as a basic config.
Let me know if you feel it needs further changes. 🙏

2023-05-05 10:53 UTC, jordojordo commented on shell/creators/app/files/.gitignore
Looks good, thanks for the change 🧙

2023-05-05 10:53 UTC, jordojordo approved these changes

2023-05-08 09:07 UTC, merged