[Epinio] Adapt the UI to the new manifest API
rancher/dashboard pull request #8797
Opened 2023-05-05 16:04 UTC by torchiaf

### Summary
Fixes https://github.com/epinio/ui/issues/228
Fixes https://github.com/epinio/ui/issues/227

### Occurred changes and/or fixed issues

### Technical notes summary

There are some blocker issues before we can merge this PR; Some fields are missing in the `/applications` API response:

- `ApplicationOrigin.archive` field is missing 
- `ApplicationOrigin.path` is missing
- `ApplicationOrigin.container` is missing 
- for GitLab application we may want a field `id` to use as key to fetch GitLab repositories. Currently the field `ApplicationOrigin.git.repository` contains only the repo name as string.

2023-05-15 14:03 UTC, richard-cox requested changes
Haven't given this a full functional test yet, will save that until after EPINIO_APP_DATA has been removed. 

I did test a succesful deploy from github and download manifest. The manifest however, when loaded in the create app process, thinks it's git instead of github

2023-05-16 12:33 UTC, torchiaf commented on pkg/epinio/detail/applications.vue
> +import { AppUtils } from '@/pkg/epinio/utils/application';
Using `@pkg` breaks the app; is is also marked as error in VS code

2023-05-16 12:45 UTC, torchiaf commented on pkg/epinio/detail/applications.vue
> +      source:        AppUtils.getAppSource(this.value),
Agree, I'm going to move `getAppSource` and `getAppSourceInfo` in the applications model and leave the other utils functions in `application.ts` util.

2023-05-16 14:24 UTC, torchiaf commented on pkg/epinio/types.ts
>  export interface EPINIO_APP_DATA {
Yes, good point. I need to a refactoring.

2023-05-16 16:23 UTC, torchiaf commented
Thanks @richard-cox , I updated the code with the requested changes.
> will save that until after EPINIO_APP_DATA has been removed.
The EPINIO_APP_DATA is removed in this PR, so ti will resolve both issues in the PR description. Am I missing somenthing ?
> The manifest however, when loaded in the create app process, thinks it's git instead of github
We have this bug also in `epinio-dev`, so could we open a new issue for this ?

2023-05-19 16:40 UTC, richard-cox approved these changes
Code reviewed, however blocked from functional testing due to the git provider type changes brought in when our epinio instance was rebuilt. Will aim to get all PRs merged,  then test, then move issues to To Test.

With that in mind, we can ignore the two comments in this review

2023-05-19 16:40 UTC, richard-cox commented on pkg/epinio/edit/applications.vue
> +              v-if="source"
for neatness, can this be tied in to `showSourceTab`?

2023-05-19 16:40 UTC, richard-cox commented on pkg/epinio/models/application-action.js
> +  // Todo move to utils
ToDo (though not sure we need to move this outside of the file)

2023-05-19 16:40 UTC, merged