fix object overwrite & rerender
rancher/dashboard pull request #8809
Opened 2023-05-06 09:32 UTC by WuJun2016

### Summary
Using the management/find method here will cause the value in the store to overwrite the value in the machine pool (because the value of `machinePool[*].config` has not been cloned at this point).

Fixes #
- https://github.com/harvester/harvester/issues/3786

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-05-06 09:46 UTC, WuJun2016 commented
Hi @mantis-toboggan-md   Can this issue fix be merged into `2.7.4` ?

2023-05-09 10:45 UTC, richard-cox requested changes
The 2.7 Q2 release, currently `rancher/dashboard` `master`, will be the next release this can be included in

2023-06-01 19:51 UTC, mantis-toboggan-md submitted a review, later dismissed

2023-06-01 23:37 UTC, mantis-toboggan-md approved these changes

2023-06-01 23:37 UTC, mantis-toboggan-md commented
I added a comment to explain the change, otherwise LGTM

2023-06-01 23:37 UTC, merged