Remove `v-html` from project labels
rancher/dashboard pull request #8832
Opened 2023-05-09 23:07 UTC by rak-phillip

### Summary
This removes the need to use `v-html` when displaying project labels by shifting the `span` tag outside of the translations inside of `en-us.yaml` and into the vue template.

### Areas or cases that should be tested

#### Before

![image](https://github.com/rancher/dashboard/assets/835961/420989f6-31e0-4d75-90d0-e0ac90f3cdf8)

#### After

![image](https://github.com/rancher/dashboard/assets/835961/cef056a0-d165-45f9-9b23-9d5f2a8aca04)

2023-05-09 23:28 UTC, mantis-toboggan-md approved these changes
lgtm

2023-05-10 08:04 UTC, nwmac requested changes

2023-05-10 08:04 UTC, nwmac commented on shell/assets/translations/en-us.yaml
> +    project: "Project:"
The name param is here so that for rtl locales, - can't always assume that the name should go after the label.

2023-05-10 15:27 UTC, rak-phillip commented
@mantis-toboggan-md @nwmac I've updated this PR to utilize `DOMPurify`. Can you take another look?

2023-05-10 18:18 UTC, merged