Add initial value to empty object for rkeconfig.configMap[hostname] d…
rancher/dashboard pull request #8848
Opened 2023-05-11 07:02 UTC by smallteeths

### Summary
Fixes #
https://github.com/rancher/rancher/issues/41519

### Areas or cases that should be tested
1. Create custom rke2 cluster without select the `Skip TLS certificate` option.
2. Edit the rke2 cluster and select the `Skip TLS certificate` option.
3. When saving the RKE2 cluster, it is found that the "Skip TLS certificate" value is not passed to the backend.

### Areas which could experience regressions

Vue.js's watcher mechanism is based on the getter and setter of JavaScript objects. When an object is set to be reactive, Vue rewrites the getter and setter of the object through Object.defineProperty() or ES6's Proxy so that it can receive notifications and trigger the corresponding watcher when the property value changes. The issue occurs when we bind an empty object to the data object of a Vue instance because Vue does not automatically set the getter and setter for the properties of the object. Therefore, when you add a property to the object and assign it a value during component creation, Vue is not aware of this change because the property of the object has not been set to be reactive. As a result, it is necessary to initialize the corresponding property value.

2023-06-27 12:35 UTC, richard-cox commented
This is a general bug fix, no special UX required

2023-07-14 15:50 UTC, richard-cox requested changes
One minor change, then looks good.

The computed property `defaultAddValue` should remove and instead initialised and set in `data`. That can then be used when ensuring existing values have the defaults (not sure why these aren't persisted, but change is safe). So something like...

```
  data() {
    const configMap = this.value.spec.rkeConfig?.registries?.configs || {};
    const entries = [];

    const defaultAddValue = {
      hostname:             '',
      authConfigSecretName: null,
      caBundle:             '',
      insecureSkipVerify:   false,
      tlsSecretName:        null,
    };

    for ( const hostname in configMap ) {
      if (configMap[hostname]) {
        configMap[hostname].insecureSkipVerify = configMap[hostname].insecureSkipVerify ?? defaultAddValue.insecureSkipVerify;
        configMap[hostname].authConfigSecretName = configMap[hostname].authConfigSecretName ?? defaultAddValue.authConfigSecretName;
        configMap[hostname].caBundle = configMap[hostname].caBundle ?? defaultAddValue.caBundle;
        configMap[hostname].tlsSecretName = configMap[hostname].tlsSecretName ?? defaultAddValue.tlsSecretName;
      }
      entries.push({
        hostname,
        ...configMap[hostname],
      });
    }

    return { entries, defaultAddValue };
  },
```

2023-07-19 09:10 UTC, richard-cox commented
@smallteeths Please note we are approaching bug complete for our next milestone 2.7q3

2023-07-19 10:34 UTC, richard-cox approved these changes

2023-07-19 10:35 UTC, richard-cox commented
@smallteeths looks good! i'll shepherd the PR through our CI and merge once passed.

2023-07-19 12:45 UTC, richard-cox commented
@smallteeths I don't have permission to push changes to this PR. Could you make the following change

```
--------------- cypress/e2e/po/pages/explorer/api-services.po.ts ---------------
index dec45a912..c2786e126 100644
@@ -16,5 +16,5 @@ export class APIServicesPagePo extends PagePo {
 
   waitForRequests() {
-    APIServicesPagePo.goToAndWaitForGet(this.goTo.bind(this), ['/v1/apiregistration.k8s.io.apiservices']);
+    APIServicesPagePo.goToAndWaitForGet(this.goTo.bind(this), ['/v1/apiregistration.k8s.io.apiservices?exclude=metadata.managedFields']);
   }
```

It will be fixed in `master` soon, but this will avoid a rebase when it does

2023-07-20 01:25 UTC, smallteeths commented
> @smallteeths I don't have permission to push changes to this PR. Could you make the following change
> 
> ```
> --------------- cypress/e2e/po/pages/explorer/api-services.po.ts ---------------
> index dec45a912..c2786e126 100644
> @@ -16,5 +16,5 @@ export class APIServicesPagePo extends PagePo {
>  
>    waitForRequests() {
> -    APIServicesPagePo.goToAndWaitForGet(this.goTo.bind(this), ['/v1/apiregistration.k8s.io.apiservices']);
> +    APIServicesPagePo.goToAndWaitForGet(this.goTo.bind(this), ['/v1/apiregistration.k8s.io.apiservices?exclude=metadata.managedFields']);
>    }
> ```
> 
> It will be fixed in `master` soon, but this will avoid a rebase when it does

done

2023-07-21 09:04 UTC, richard-cox approved these changes

2023-07-21 09:04 UTC, merged