HARVESTER: correct the metrics url
rancher/dashboard pull request #8875
Opened 2023-05-15 08:09 UTC by DaiYuzeng

### Summary

### Occurred changes and/or fixed issues

#### Testing Monitoring Version: `100.1.0+up19.0.3`

I find out the metrics url would be added the prefix `/k8s/clusters/${ clusterId }` even if the version of monitoring is older than `102.0.0+up40.1.2`.

It seems like `monitoringVersion` is `undefiend` when it is used by function `computeDashboardUrl`, maybe this is the root cause?
![image](https://github.com/rancher/dashboard/assets/15041915/212a2150-74cd-48ad-9ba5-f05f763c257e)

And I think the function `computeUrl` may emit always before the async fetch function. So I put the logic of getting monitoring version into `data` function.

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-05-15 08:52 UTC, richard-cox commented
We need to check where the component is used, and if the resource will always be there (switching from dispatching `find` to a getter)

2023-05-16 13:20 UTC, richard-cox commented
@DaiYuzeng I couldn't reproduce this with RKE2 1.24, Monitoring 101.0.0+up19.0.3 and viewing metrics on the Cluster homepage or, workload, pod or node detail pages. On all of those metrics loaded correctly. Could you provide some steps to pre-produce?

2023-05-19 17:28 UTC, richard-cox requested changes
Syncing state here with our slack conversation.

For anyone who's stumbled on this we've worked together and agreed some updates

2023-05-22 02:56 UTC, DaiYuzeng commented
Thanks for your comments! According to our slack conversation, I'll close this PR at first.

2023-05-22 02:56 UTC, closed without merging