supply plugin built-in property
rancher/dashboard pull request #8890
Opened 2023-05-16 09:51 UTC by DaiYuzeng

### Summary

### Occurred changes and/or fixed issues

https://github.com/harvester/harvester/issues/3895

### Technical notes summary

### Areas or cases that should be tested

#### Reproduce steps

1. Go to harvester cluster
2. Go to rancher `Users & Authentications`
3. Go to harvester cluster
4. Log out
5. Log in

### Areas which could experience regressions

### Screenshot/Video

2023-05-16 10:05 UTC, richard-cox requested changes

2023-05-16 10:05 UTC, richard-cox commented on shell/core/plugins.js
> +            plugin.builtin = true;
Only plugins that are included at build time should have the `builtin` flag. With the flag on it'll stop the plugin from being unloaded when logging out.

Think the problem here is that the dashboard is failing to recognise the route is associated with the harvester plugin. It should be doing this, loading the plugin and then allowed navigation to continue.

That code is in `shell/middleware/authenticated.js` and the line that should succeed is `const newLocation = await dynamicPluginLoader.check({ route, store });`

2023-07-11 07:41 UTC, DaiYuzeng commented on shell/core/plugins.js
> -        delete plugins[plugin.name];
I think deleting the member of plugins by `plugin.name` may be not accurate. After apply this change, the issue seems to be solved.

@richard-cox Please take a re-review when you are free, thanks!

2023-07-11 07:42 UTC, DaiYuzeng commented on shell/core/plugins.js
> -        delete plugins[plugin.name];
cc @WuJun2016 thanks!

2023-07-14 13:57 UTC, richard-cox approved these changes

2023-07-14 13:58 UTC, merged