Add HorizontalPodAutoscaler scaling behavior support
rancher/dashboard pull request #9033
Opened 2023-06-02 12:01 UTC by bashofmann

### Summary
Kubernetes added additional functionality to HorizontalPodAutoscalers to configure the autoscaling behavior. This has been stable since Kubernetes 1.23.

Documentation https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
API Reference https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec

Fixes #9032

### Occurred changes and/or fixed issues
* Adds form fields to edit the autoscaling behavior in the HPA edit form
* Adds autoscaling behavior information on the HPA detail page

### Areas or cases that should be tested
HPA creation/edit form, HPA detail page.

### Areas which could experience regressions
HPA creation/edit form, HPA detail page.

### Screenshot/Video
<img width="1255" alt="Bildschirmfoto 2023-06-02 um 13 40 46" src="https://github.com/rancher/dashboard/assets/243056/0f6c872e-77f9-44fa-9ae1-ab20ce001786">
<img width="1266" alt="Bildschirmfoto 2023-06-02 um 13 37 51" src="https://github.com/rancher/dashboard/assets/243056/5da1f4ad-e168-4a76-ba9b-1b1bb745cb36">

2023-06-30 10:54 UTC, richard-cox requested changes
Solid PR! There's some minor visual things, @kwwii can give the final review there though (the change is as per description, one new 'behavior' tab when creating/editing a hpa plus one new 'behavior' tab when viewing the detail of a hpa) 

- Edit Page: There needs to be a gap between the checkbox and policy
  - ![image](https://github.com/rancher/dashboard/assets/18697775/386969c1-08bf-482f-9520-58c9c0050ece)
  - ![image](https://github.com/rancher/dashboard/assets/18697775/144503e4-0d90-413f-a456-b24cf3757b84)
- Detail Page: There's some differences between the right column compared to similar on the Metrics tab. 
  - no vertical spacing between lines
  - value isn't in bold 
  - there's no separator between columns
  - ![image](https://github.com/rancher/dashboard/assets/18697775/dbadf1c9-ad9f-4004-a040-fbbf4de1173a)
  - ![image](https://github.com/rancher/dashboard/assets/18697775/53edccac-05a4-406f-9b57-a19f6b5db71e)
- Comment only - Required fields are used inline with other places in the form. However none are tied to whether the create/save button is enabled. We'll create a separate issue for that

2023-07-10 14:49 UTC, bashofmann commented
I made the requested changes

<img width="1010" alt="Bildschirmfoto 2023-07-10 um 16 48 15" src="https://github.com/rancher/dashboard/assets/243056/f0791336-4947-4d67-bbaa-bce4d2370f50">
<img width="1214" alt="Bildschirmfoto 2023-07-10 um 16 48 06" src="https://github.com/rancher/dashboard/assets/243056/6334039e-5c17-4efb-ae80-9a08a311db69">

2023-07-12 12:22 UTC, richard-cox approved these changes
LGTM. I'll double check with @kwwii and we'll get this in.

2023-07-12 15:06 UTC, richard-cox commented
Chatted with Ken, we'll improve how the detail page tabs look via https://github.com/rancher/dashboard/issues/9308

2023-07-12 15:06 UTC, merged