Wire in extension table column feature to cluster `node` list and other hardcoded places
rancher/dashboard pull request #9186
Opened 2023-06-23 08:42 UTC by aalves08

Fixes #8674 

- add logic to support new table cols via extensions hook on `resource table` instead of `type-map` so that we can capture tables/resources with locally defined headers like the `nodes` list

## How to test
- create a new extension/package on rancher dashboard by running the following command: `yarn create @rancher/pkg test`
- edit the `index.ts` file of the newly added test extension/package with the following code:
```
import { importTypes } from '@rancher/auto-import';
import { IPlugin, TableColumnLocation } from '@shell/core/types';

// Init the package
export default function(plugin: IPlugin) {
  // Auto-import model, detail, edit from the folders
  importTypes(plugin);

  // Provide plugin metadata from package.json
  plugin.metadata = require('./package.json');

  // Load a product
  // plugin.addProduct(require('./product'));
  plugin.addTableColumn(
    TableColumnLocation.RESOURCE,
    { resource: ['node', 'catalog.cattle.io.app'] },
    {
      name:     'some-prop-col',
      labelKey: 'generic.comingSoon',
      getValue: (row: any) => {
        return `${ row.id }-DEMO-COL-STRING-ADDED!`;
      },
      width:  100,
      sort:   ['stateSort', 'nameSort'],
      search: ['stateSort', 'nameSort'],
    }
  );
}
```
- run your local Rancher Dashboard and go to `local` -> `nodes` and see if a new column called `Coming Soon` appears
- go to `local` -> `apps` -> `installed apps` and see if a new column called `Coming Soon` appears
 
## Screenshots
![Screenshot 2023-06-23 at 09 37 28](https://github.com/rancher/dashboard/assets/97888974/cdab4821-6588-4d6c-b348-f6d7f298967f)
![Screenshot 2023-06-23 at 09 37 37](https://github.com/rancher/dashboard/assets/97888974/1ca88730-bd0c-4956-bed5-f09568f527a5)

2023-06-23 20:25 UTC, codyrancher submitted a review, later dismissed

2023-06-27 17:13 UTC, richard-cox requested changes

2023-07-06 10:23 UTC, aalves08 commented on shell/components/ResourceTable.vue
> +      const type = this.schema?.id ? this.schema?.id : this.$route?.params?.resource ? this.$route?.params?.resource : undefined;
updated. Thanks for the input!

2023-07-06 10:58 UTC, aalves08 commented on shell/store/type-map.js
> -      if (store.$plugin?.getUIConfig) {
updated! 🖖

2023-07-12 13:35 UTC, merged