Extension support for custom provisioning
rancher/dashboard pull request #9246
Opened 2023-06-30 13:07 UTC by nwmac

WIP

This is work-in-progress changes to allow Extensions to add custom provisioning UI into Dashboard without needing to use the NodeDriver approach.

2023-07-10 12:13 UTC, richard-cox commented
Linking forked example repo https://github.com/richard-cox/provisioning containing updated example and new digital ocean provisioners

2023-07-10 15:57 UTC, richard-cox commented
There's been a few updates, see https://github.com/richard-cox/provisioning for new extensions supporting them

2023-07-10 21:13 UTC, mantis-toboggan-md requested changes

2023-07-11 14:42 UTC, richard-cox commented on shell/edit/provisioning.cattle.io.cluster/index.vue
> +          tag:         ext.tag
Good shout. I've added the docs to IClusterProvisioner. Also left out iconClass for the moment

2023-07-11 14:43 UTC, richard-cox commented on docusaurus/docs/extensions/api/common.md
> +|`customParams` | Object | ResourceTab only, when configured by that instance. Key value object which must match the object supplied to the instance of ResourceTab. Can be used to only show feature g
i've changed this to `context`. As it turns out we do need one for query params, so also added `queryParam`

2023-07-11 14:44 UTC, richard-cox commented on docusaurus/docs/guide/custom-dev-build.md
> +> It's important to get this right. If there's a typo or any other issue the Rancher UI will become unavailable. If this happens, whilst your UI session is still alive, go to `<rancher url>/v3/settin
I've added this as an alternative method, though stuck with `ui-offline-preferred` `true` as it's a good catch all case

2023-07-11 14:48 UTC, richard-cox commented
@mantis-toboggan-md I've updated the PR following the review comments. As per comments I've added another extension point to allow additional tabs to the `Cluster Configuration` section. I've also tidied a few things up, and fixed the user of `t` in the provisioner. 

Just gonna start looking at CI failures now

2023-07-11 17:24 UTC, mantis-toboggan-md approved these changes

2023-07-11 20:50 UTC, richard-cox commented on shell/core/types-provisioning.ts
> +  icon: any;
oops, missing this, made optional in previous change

2023-07-11 21:17 UTC, merged