Added router to rediect github auth
rancher/dashboard pull request #9262
Opened 2023-07-04 11:23 UTC by bisht-richa

### Summary
Fixes #9138

Fixed issue - Unable to use Auth Providers when running locally

### To test
setup github auth provider

2023-07-04 12:22 UTC, nwmac commented
This used to work pre-Nuxt removal - this was handled by `shell/server/server-middleware.js`.

This was removed when we removed Nuxt - although the `server-middleware.js` file is still in the codebase. It looks like `serverMiddleware` in `shell/vue.config.js` is never used.

This needs to be wired in ONLY when running in dev locally.

We should be able to write serverMiddleware back into vue.config via `setupMiddlewares` on `devServer` - see: https://cli.vuejs.org/config/#devserver and https://webpack.js.org/configuration/dev-server/#devserversetupmiddlewares

2023-07-12 13:18 UTC, richard-cox requested changes
This hasn't covered part of the request from https://github.com/rancher/dashboard/issues/9138#issuecomment-1611703585
  - the process to add server middleware via the old `serverMiddleware` array is still in `shell/vue.config.js`. At the very least `serverMiddleware.push(path.resolve(dir, SHELL, 'server', 'server-middleware'));` should be removed
  - there's no clear way forward to address that now defunct old method using the `serverMiddleware` array (specifically the other parts that don't work in post nuxt world). Can you create an issue to cover them?

2023-07-13 08:12 UTC, bisht-richa commented
> * there's no clear way forward to address that now defunct old method using the `serverMiddleware` array (specifically the other parts that don't work in post nuxt world).

I have removed unused code and created an issue for `serverMiddleware` array :  https://github.com/rancher/dashboard/issues/9312

2023-07-14 14:34 UTC, richard-cox approved these changes

2023-07-14 14:35 UTC, merged