locationConfig hash param
rancher/dashboard pull request #9514
Opened 2023-08-10 15:37 UTC by aalves08

Fixes #9511 

- add hash param to `locationConfig` object in extensions to allow fine-tune of application of an extension point 
- **Sneaky fix**: change logic around extension table cols to better reflect col location based on page user is browsing and not just resource, because same resource can be in multiple pages, but extra table col may only be meaningful in a specific page **->** 
_this will introduce breaking change as target is now different. I believe it's for the best as this allows us to selectively target tables inside resource detail page, which combined with the new `hash` parameter, allows for a finer control of the application of any extension enhancement._

### Areas or cases that should be tested
- create a new package `yarn create @rancher/pkg test`
- on the `index.ts` file for the newly created package, replace the code with the following:
```
import { importTypes } from '@rancher/auto-import';
import { IPlugin, TableColumnLocation } from '@shell/core/types';

// Init the package
export default function(plugin: IPlugin): void {
  // Auto-import model, detail, edit from the folders
  importTypes(plugin);

  // Provide plugin metadata from package.json
  plugin.metadata = require('./package.json');

  plugin.addTableColumn(
    TableColumnLocation.RESOURCE,
    {
      resource: ['provisioning.cattle.io.cluster'], mode: ['detail'], hash: ['node-pools']
    },
    {
      name:     'test-col',
      label:       'test col',
      getValue: (row: any) => {
         return 100;
      },
    }
  );
}
```
- Go to `cluster management`, click on `local` cluster to see it's details, make sure `test col` appears on the list of `machine pools` (before the changes to the table col mechanism, one would target this table by setting the `locationConfig` to `{ resource: ['management.cattle.io.node'] }`.
- Check other tabs to make sure `test col` doesn't appear on other table of the same details page

FYI @richard-cox @nwmac

2023-08-11 13:47 UTC, aalves08 commented
I know we are really late in the release process, but is there any chance that this can go in into the 2.7.7 release? Had to ask...  SUMA extension will make use of this mechanism. @richard-cox @nwmac

2023-08-18 20:46 UTC, jordojordo requested changes
One small wording change, otherwise lgtm.

2023-08-18 20:46 UTC, jordojordo commented on docusaurus/docs/extensions/api/table-columns.md
> +>**IMPORTANT NOTE:** on **Rancher version v2.8.0** we've introduced breaking changes to the behaviour of this extension enhancement (Table Columns), as it before you would target the resource name of
> as it before you would target

This should be "previously, you would target".

2023-08-25 11:24 UTC, aalves08 commented
@jordojordo when you have some spare time, can you approve this? I need this to go in so that I can save the work done on the SUMA extension as it was mostly done using `yarn link` to this branch. 🙏

2023-08-25 11:44 UTC, jordojordo approved these changes

2023-08-25 13:41 UTC, merged