add growl message to display warning messages from response headers
rancher/dashboard pull request #9581
Opened 2023-08-23 10:29 UTC by aalves08

### Summary
Fixes #8502 

### Occurred changes and/or fixed issues

- add growl message to display warning messages from response headers
- updated style of growl to better show long messages (title margin to text, icon margin to text, larger growl width)

### Technical notes summary

- This was the only mechanism that we have of "easy access" to display warnings from response headers. Also, these types of warnings are non-persistent (they don't exist on the object resource), so we can't show them on the details screen (ex: in this particular case `DaemonSets`, but you have the related events).

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-08-24 17:09 UTC, richard-cox requested changes
- Something that can be done as part of this PR, ensure that if opt.method === 'PUT' we make it to the `handleValidationWarnings` function and it's also handled when determining create / update. To reproduce this create / edit any resource via YAML
- Unrelated to this PR, YAML editing error messages are broken https://github.com/rancher/dashboard/issues/9592
- i've tried for a while to get any other type of warning header than validation and this PRs message. will continue with that tomorrow. Will also work out if there's a _super simple_ way to tweak the filter used to determine if the warning goes in a growl. We've had a lot of issues in the past where spurious growls bite us real hard, so would like a way for customers to either disable or configure it.

2023-08-25 15:21 UTC, richard-cox commented on shell/plugins/steve/actions.js
> +      const relevantWarnings = warnings.filter((w) => !w.includes('299 - unknown field')) || [];
n/a

2023-08-25 15:21 UTC, richard-cox commented on shell/plugins/steve/actions.js
> +      const relevantWarnings = warnings.filter((w) => !w.includes('299 - unknown field')) || [];
n/a given new changes

2023-08-25 15:23 UTC, richard-cox approved these changes
I've updated a lot of things, more detail in the commit message. These all need a good review though, @aalves08 if you're happy with the changes this can go in.

2023-08-28 10:38 UTC, aalves08 commented
Uau @richard-cox , nice job with this PR! 👏 you went all out with this one! I've reviewed your code changes + tested the functionality and all works as expected. I'm going to merge this. Thank you very much for your contribution. 🙇

2023-08-28 10:39 UTC, aalves08 commented
Ah, you need to re-approve it @richard-cox ! I can't, as a PR owner, so that this can be merged. 🙏

2023-08-29 08:47 UTC, richard-cox approved these changes

2023-08-29 08:54 UTC, merged