Add bulk addition to string list component
rancher/dashboard pull request #9709
Opened 2023-09-14 11:54 UTC by s0nea

### Summary
Fixes #9707

Add bulk addition option to string list component.

### Screenshot/Video

[rd.webm](https://github.com/rancher/dashboard/assets/8761082/5e341626-c84f-4b1e-907e-c6f3f779826e)

2023-10-02 09:51 UTC, torchiaf requested changes
The bulkable functionality works great, just a couple of comment about possible test/code imporvements

2023-10-02 09:51 UTC, torchiaf commented on pkg/rancher-components/src/components/StringList/StringList.vue
> +    addValueToItems(items: string[], value: string, index?: number): string[] {
I think the `items` parameter may be decoupled from the return value here:
```
const newItems = [...items];
...
return newItems;
```
and change the input wherever `addValueToItems` is called: `addValueToItems([...this.items]) -> addValueToItems(this.items)`

2023-10-02 09:51 UTC, torchiaf commented on pkg/rancher-components/src/components/StringList/StringList.vue
> +        const items = index !== -1 ? this.addValueToItems([...this.items], value, index) : [...this.items];
see comment on `addValueToItems` below

2023-10-02 09:51 UTC, torchiaf commented on pkg/rancher-components/src/components/StringList/StringList.test.ts
> +      it('should show warning if one of the values is a duplicate', async() => {
Could you please add a new `it()` block to test the case of duplicate items inside bulk items?
example:
```
const newValue = 'test;test';
```

2023-10-09 13:36 UTC, s0nea commented
> The bulkable functionality works great, just a couple of comments about possible test/code improvements.

@torchiaf thank you for your review! I think I addressed all of your comments. Would you mind taking another look at it?

2023-10-11 07:23 UTC, torchiaf approved these changes
LGTM

2023-10-13 16:28 UTC, rak-phillip reviewed
@s0nea can we bump the rancher components version so that we will be ready to publish a release once this merges?

2023-10-13 16:38 UTC, s0nea commented
> @s0nea can we bump the rancher components version so that we will be ready to publish a release once this merges?

@rak-phillip yes, thank you for mentioning it! I pushed an update.

2023-10-25 19:30 UTC, rak-phillip approved these changes

2023-10-25 21:26 UTC, merged