Add automatically default value for deployment PVC
rancher/dashboard pull request #9717
Opened 2023-09-15 13:04 UTC by cnotv

### Summary
Fixes #9585

### Occurred changes and/or fixed issues
Default value is now automatically assigned after fetching the data.

### Technical notes summary
Unit test has been created but it's not possible to use it till we do not integrate `fetch()` in the test suite.

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

https://github.com/rancher/dashboard/assets/5009481/c3cc93cf-1d7c-47a5-9698-d184acec7635

2023-09-21 16:51 UTC, torchiaf requested changes
- The e2e test need to be verified, we could probably just skip the e2e tests and address them in a new issue.
- PVC creation looks good when creating a new Deployment from scratch, but it seems to be still broken when edit a deployment and add a new PVC:

![image](https://github.com/rancher/dashboard/assets/26394656/57261369-faf3-4339-a7eb-7d4fb50e6f8d)

I think this case should be covered by this fix.

2023-09-21 16:51 UTC, torchiaf commented on shell/edit/workload/storage/persistentVolumeClaim/persistentvolumeclaim.vue
> +    isCreatePV(neu, old) {
`old` is never used, it can be removed.

2023-09-21 17:50 UTC, cnotv commented
The E2E unfortunately is failing for everyone 😬

2023-09-22 15:41 UTC, cnotv commented
> * PVC creation looks good when creating a new Deployment from scratch, but it seems to be still broken when edit a deployment and add a new PVC:

> I think this case should be covered by this fix.

Totally agree and nice catch. Not sure why I was restricting it to creation only.

2023-09-25 13:18 UTC, torchiaf approved these changes
Approved once the e2e tests complete with success.

2023-09-26 17:14 UTC, merged