save method in model fixes payload, validator catches the rest
rancher/dashboard pull request #9758
Opened 2023-09-22 14:16 UTC by Sean-McQ

### Summary
Fixes #

### Occurred changes and/or fixed issues

### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-09-22 17:27 UTC, richard-cox requested changes
This issue was discussed in grooming but you may not have been there. We need to
- understand if grants are need either `resource` + `api group` OR `non-resource urls`
  - this looks to be the case, but needs confirming https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#policyrule-v1-rbac-authorization-k8s-io
- if so, change the ux such that the user can only enter one set or the other

At the moment
- the user can enter any or none of the resource apigroup or non-resource url fields
- for me no validation warning was shown at any point
  - i couldn't track which `roleTemplateRules` was meant to be used. from what i can tell only one is referenced in code
  -  shell/utils/validators/formRules/index.ts  roleTemplateRules or shell/utils/validators/role-template.js roleTemplateRules
- on `Create` if there is a non-resource both resource and api group are removed. we don't know what the user wanted, so are guessing

2023-09-22 17:27 UTC, richard-cox commented on shell/models/management.cattle.io.roletemplate.js
> +    norman.save();
as it doesn't return the result, any failures are ignored

2023-09-27 10:09 UTC, Sean-McQ commented
The docs say `Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"), but not both.` which seems pretty definitive. APIGroups isn't required but should auto-populate when a resource is selected from the dropdown. At least one verb is required.

One note: The API does allow the creation of a roletemplate without any resource grants and I can't find any documentation indicating that a roletemplate with no resource grants is invalid so I'm not going to disable save on that condition.

2023-09-27 16:29 UTC, richard-cox approved these changes
After playing around i spotted some unrelated issues we should tackle later

- after adding a `Resource` it's impossible to remove. the entire row has to be removed
- cluster --> view role --> `Config` tab --> api groups and non-resource urls input fields are editable (no `mode`?)
- we need to add an addition input field & validation for the policy `resourceNames` (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#policyrule-v1-rbac-authorization-k8s-io)
- after adding a new grant the warning for empty verb is shown. this shouldn't be shown, as an empty grant is currently valid

2023-09-27 17:40 UTC, merged