Improve Extensions documentation
rancher/dashboard pull request #9896
Opened 2023-10-11 10:23 UTC by aalves08

### Summary
Fixes #9481 

### Occurred changes and/or fixed issues

- Improve extension docs in order to include information about `cluster-level` products
- Add info about `LocationConfig` wildcard param for resource `*`
- Fix broken Getting Started example (missing route definition because of changes to custom 404 pages done a while ago)
- Fix Developer Load block as the env variable `EXCLUDE_PKGS` doesn't work on a local dev env anymore (very old docs)
- Fix multiple parts of docs
- Improve types definition to prevent linter complains on `top-level` and `cluster-level` products examples
- bump shell version

> Note: Tried to extend `RouteConfig` type multiple times, but always hit some kind of problem, so opted to go with a more generic `Object` definition in types in a couple of areas. `RouteConfig` doesn't have/allow `params` route param, which is strange, imo.
 
### Technical notes summary

### Areas or cases that should be tested

### Areas which could experience regressions

### Screenshot/Video

2023-10-11 10:23 UTC, aalves08 commented
FYI @nwmac

2023-10-11 13:58 UTC, jordojordo requested changes

2023-10-11 13:58 UTC, jordojordo commented on docusaurus/docs/extensions/usecases/cluster-level-product.md
> +import { IPlugin } from '@shell/core/types';
Might make sense to add the file location as a comment within the code block:

```ts
// ./index.ts
import { importTypes } from '@rancher/auto-import';
...
```

```ts
// ./product.ts
import { IPlugin } from '@shell/core/types';
...
```

2023-10-11 13:58 UTC, jordojordo commented on docusaurus/docs/extensions/usecases/cluster-level-product.md
> +One above example we are registering 2 pages: a resource page called `YOUR_K8S_RESOURCE_NAME` and a custom page called `CUSTOM_PAGE_NAME`. These need to be reflected in the routes definition that is
"In the example above, ..."

2023-10-11 13:58 UTC, jordojordo commented on docusaurus/docs/extensions/usecases/cluster-level-product.md
> +A full working example of this code, which can be deployed as an Extension on you Rancher Dashboard, can be found on the [Rancher examples repo](https://github.com/rancher/ui-plugin-examples). Just f
"how to _add_ the repo..."

2023-10-11 14:43 UTC, aalves08 commented on docusaurus/docs/extensions/api/nav/routing.md
> +> Note: Noticed that we didn't need to define the parameter `resource` under `meta`? Since it a wildcarded parameter on the path and we haven't defined `cluster` so that the context of the cluster th
Just to reinforce the idea, but then again, when is it enough? Gonna clear it 🙏

2023-10-11 15:20 UTC, aalves08 commented on docusaurus/docs/extensions/extensions-getting-started.md
> +> Note: In a different Rancher UI, you should be able to follow the steps in the previous section, but instead use the URL from the output above in the Developer Load dialog.
deleted

2023-10-12 12:35 UTC, jordojordo approved these changes
lgtm!

2023-10-12 16:47 UTC, merged

2023-10-16 10:27 UTC, richard-cox commented on docusaurus/docs/extensions/api/nav/products.md
> +| `inStore` | String |  Which store should the product be registered on. Use `management` for a top-level product and `cluster` for a cluster-level product |
That's not quite right for non-rancher store based products (like epinio)